### ISSUE TITLE
top doesn't quit correctly

### ISSUE THREAD

**Issue by Glog78** [contour-terminal/contour#1040]
### Contour Terminal version

0.3.11-makepkg-a79661de

### Installer source

Github: source code cloned

### Operating System

arch linux

### Architecture

x86-64

### Other Software

top

### Steps to reproduce

1.) start top
2.) press q
(optional Enter gives an indication where the cursor is placed)

![image](https://user-images.githubusercontent.com/7598856/219865025-ab5c129f-9291-44f8-857c-19f27dd8e7d2.png)
^^ top running 

![image](https://user-images.githubusercontent.com/7598856/219865046-6774e1c0-48a2-42f5-a876-80729cdcdce6.png)
^^ top after quit and 2 times pressed enter 

### Expected Behavior

the whole top get's moved one up and the command line shows below

### Actual Behavior

only a few lines at the top gets moved up and the positioning for further commands is screwed till calling clear.

**Comment by Utkarsh-khambra** [comment]
Hi, I can't reproduce it. Could you mention what is the version of top that you are using

**Comment by Yaraslaut** [comment]
I think its not connected to the top, i am getting similar errors from time to time with different tools, example lldb : 
![image](https://user-images.githubusercontent.com/44506630/219880440-c384b949-6ce5-46d4-af67-abb0dc58e552.png)

**Comment by Glog78** [comment]
top -v
  procps-ng 3.3.17

**Comment by Glog78** [comment]
https://termbin.com/nvopg << contour debug '*' and ctrl+c right after it happend
https://termbin.com/l3s1m << also contour.yml  ... it might be connected ???

**Comment by Glog78** [comment]
Ok i found the bug 

```
history:
  limit: -1
```

ist causing this behavior for me ... changed it to positive value and i couldn't reproduce anymore

**Comment by christianparpart** [comment]
Wow. nice catch. And thanks for fixing it @Utkarsh-khambra :)

**Comment by Glog78** [comment]
fixed as far as i can see in https://github.com/contour-terminal/contour/commits/fix/1040
