### ISSUE TITLE
Hovering mouse on an `OSC 8` hyperlink when scolled up forces scroll down

### ISSUE THREAD

**Issue by whisperity** [contour-terminal/contour#1084]
### Contour Terminal version

0.3.12.4932

### Installer source

Github: CI actions

### Operating System

Ubuntu 22.04

### Architecture

x86-64

### Other Software

bash 5.1.16(1)-release (x86_64-pc-linux-gnu)
zsh 5.8.1 (x86_64-ubuntu-linux-gnu)

### Steps to reproduce

1. Execute: `clear; printf '\e]8;;http://example.com\e\\This is a link!\e]8;;\e\\\n'; seq 1 100`
2. Press <kbd>Shift</kbd>-<kbd>Home</kbd> to scroll to top (or scroll manually)
3. Hover over `This is a link!`

### Expected Behavior

The hovering is decorated and then I can execute <kbd>Ctrl</kbd>-<kbd>Mouse1</kbd> to open it?

### Actual Behavior

The viewport jumps down to the bottom, making the link inaccessible!

### Additional notes

Happens with both my customised but also with a default-created configuration.

**Comment by christianparpart** [comment]
that fix can come easily with a unit test to cover it :)

**Comment by whisperity** [comment]
Ubuntu 20.04 & Contour 0.3.10.4591 (installed from GHA as usual) does **not** exhibit bogus behaviour. This should narrow the bisection interval a little bit.

**Comment by christianparpart** [comment]
I think we can closes this now, with #1090 being merged. :)
