### ISSUE TITLE
Sixels not working in zellij.

### ISSUE THREAD

**Issue by ferdinandyb** [contour-terminal/contour#1107]
### Contour Terminal version

Contour Terminal Emulator 0.3.12-master-7963c6d7

### Installer source

Github: source code cloned

### Operating System

Ubuntu 22.04

### Architecture

x86-64

### Other Software

zellij 0.36.0

❯ img2sixel --version
img2sixel 1.10.3

configured with:
  libcurl: no
  libpng: no
  libjpeg: no
  gdk-pixbuf2: no
  GD: no

### Steps to reproduce

Open zellij and try to cat an image with img2sixel.

### Expected Behavior

The image shows properly

### Actual Behavior

Nothing happens.

### Additional notes

In a previous build (like maybe a month old) there was a different (also buggy behaviour). I tested in plain contour without zellij and in wezterm with zellij, both work.

**Comment by christianparpart** [comment]
Looks like Zellij is said to support sixel, but the following tested terminals simply won't show sixel images from within Zellij (while showing them from outside)

- Contour
- Xterm (vt340 mode)
- Konsole (23.04.1)

Looks like an ZelliJ issue maybe? 🤔

**Comment by Utkarsh-khambra** [comment]
I can see sixel images in contour, the only buggy behavior I see it that dimensions of images are wrong because now the drawable area in terminal is reduced because some columns and lines reserved by zellij.

**Comment by Utkarsh-khambra** [comment]
>the only buggy behavior I see it that dimensions of images are wrong because now the drawable area in terminal is reduced because some columns and lines reserved by zellij.

Zellij doesn't seem to parse raster attributes as well, which is the reason zellij is getting aspect ratio of image. So there isn't any buggy behavior from contour side.

**Comment by christianparpart** [comment]
@ferdinandyb I think we should sadly close this ticket again. It's not in our domain to fix this and Zellij seems not willing enough to fix this. 🤔 😢
