### ISSUE TITLE
Update contour.yml config file to match actually existing keys

### ISSUE THREAD

**Issue by Marenz** [contour-terminal/contour#1125]
Through constant updates, config files become out-dated and start missing keys or contain keys that have been removed or renamed.

This issue is about providing a way to auto-fix those keys, either automatically or by specific user request..

**Comment by Yaraslaut** [comment]
We wanted to make it happen at some point,  the issue with that is that at the moment `yaml-cpp` API does not allow  user to write comments to the files, meaning that if we try to update config file of the user it will delete all comments in the file.
Maybe @christianparpart  have some ideas about that

**Comment by Yaraslaut** [comment]
Will be implemented as part of  https://github.com/contour-terminal/contour/issues/1282
