### ISSUE TITLE
Building error of contour-terminal with fmt soversion bump to 10 on Fedora rawhide

### ISSUE THREAD

**Issue by topazus** [contour-terminal/contour#1127]
### Contour Terminal version

0.3.12.262

### Installer source

GitHub: release page

### Operating System

Fedora rawhide

### Architecture

x86-64

### Steps to reproduce

The fmt library will update to 10.0.0 version, the following build error of contour-terminal appeared:

```bash
[60/123] /usr/bin/g++ -DBOOST_STACKTRACE_USE_ADDR2LINE=1 -DCONTOUR_STACKTRACE_ADDR2LINE=1 -DFMT_HEADER_ONLY=1 -DHAVE_BACKTRACE -DHAVE_BACKTRACE_SYMBOLS -DHAVE_CXXABI_H -DHAVE_DLADDR -DHAVE_DLFCN_H -DHAVE_DLSYM -DHAVE_EXECINFO_H -DHAVE_SYS_SELECT_H -DHAVE_UNWIND_H -DLIBTERMINAL_LOG_TRACE=1 -DLIBTERMINAL_NAME=\"contour\" -DLIBTERMINAL_VERSION_MAJOR=0 -DLIBTERMINAL_VERSION_MINOR=3 -DLIBTERMINAL_VERSION_PATCH=12 -DLIBTERMINAL_VERSION_STRING=\"0.3.12\" -I/builddir/build/BUILD/contour-0.3.12.262/src -O2 -flto=auto -ffat-lto-objects -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-U_FORTIFY_SOURCE,-D_FORTIFY_SOURCE=3 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1  -m64   -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -fno-omit-frame-pointer -mno-omit-leaf-frame-pointer -O2 -g -DNDEBUG -std=c++20 -fdiagnostics-color=always -maes -MD -MT src/vtbackend/CMakeFiles/vtbackend.dir/Terminal.cpp.o -MF src/vtbackend/CMakeFiles/vtbackend.dir/Terminal.cpp.o.d -o src/vtbackend/CMakeFiles/vtbackend.dir/Terminal.cpp.o -c /builddir/build/BUILD/contour-0.3.12.262/src/vtbackend/Terminal.cpp
FAILED: src/vtbackend/CMakeFiles/vtbackend.dir/Terminal.cpp.o 
/usr/bin/g++ -DBOOST_STACKTRACE_USE_ADDR2LINE=1 -DCONTOUR_STACKTRACE_ADDR2LINE=1 -DFMT_HEADER_ONLY=1 -DHAVE_BACKTRACE -DHAVE_BACKTRACE_SYMBOLS -DHAVE_CXXABI_H -DHAVE_DLADDR -DHAVE_DLFCN_H -DHAVE_DLSYM -DHAVE_EXECINFO_H -DHAVE_SYS_SELECT_H -DHAVE_UNWIND_H -DLIBTERMINAL_LOG_TRACE=1 -DLIBTERMINAL_NAME=\"contour\" -DLIBTERMINAL_VERSION_MAJOR=0 -DLIBTERMINAL_VERSION_MINOR=3 -DLIBTERMINAL_VERSION_PATCH=12 -DLIBTERMINAL_VERSION_STRING=\"0.3.12\" -I/builddir/build/BUILD/contour-0.3.12.262/src -O2 -flto=auto -ffat-lto-objects -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-U_FORTIFY_SOURCE,-D_FORTIFY_SOURCE=3 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1  -m64   -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -fno-omit-frame-pointer -mno-omit-leaf-frame-pointer -O2 -g -DNDEBUG -std=c++20 -fdiagnostics-color=always -maes -MD -MT src/vtbackend/CMakeFiles/vtbackend.dir/Terminal.cpp.o -MF src/vtbackend/CMakeFiles/vtbackend.dir/Terminal.cpp.o.d -o src/vtbackend/CMakeFiles/vtbackend.dir/Terminal.cpp.o -c /builddir/build/BUILD/contour-0.3.12.262/src/vtbackend/Terminal.cpp
/builddir/build/BUILD/contour-0.3.12.262/src/vtbackend/Terminal.cpp: In member function 'void terminal::Terminal::updateIndicatorStatusLine()':
/builddir/build/BUILD/contour-0.3.12.262/src/vtbackend/Terminal.cpp:608:90: error: cannot convert 'std::chrono::_V2::system_clock::time_point' {aka 'std::chrono::time_point<std::chrono::_V2::system_clock, std::chrono::duration<long int, std::ratio<1, 1000000000> > >'} to 'time_t' {aka 'long int'}
  608 |     rightString += fmt::format("{:%H:%M} ", fmt::localtime(std::chrono::system_clock::now()));
      |                                                            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~
      |                                                                                          |
      |                                                                                          std::chrono::_V2::system_clock::time_point {aka std::chrono::time_point<std::chrono::_V2::system_clock, std::chrono::duration<long int, std::ratio<1, 1000000000> > >}
In file included from /builddir/build/BUILD/contour-0.3.12.262/src/vtbackend/Terminal.cpp:30:
/usr/include/fmt/chrono.h:444:38: note:   initializing argument 1 of 'tm fmt::v10::localtime(time_t)'
  444 | inline std::tm localtime(std::time_t time) {
      |                          ~~~~~~~~~~~~^~~~
```

fmt soversion bump announcement: https://lists.fedoraproject.org/archives/list/devel@lists.fedoraproject.org/thread/GLKMEVMVOAROPTBRBNSZKU4RCL2BCVJV/
build url: https://koji.fedoraproject.org/koji/taskinfo?taskID=102702637
build log: https://kojipkgs.fedoraproject.org//work/tasks/2637/102702637/build.log

### Actual Behavior

successful build

**Comment by Yaraslaut** [comment]
Thanks a lot @topazus for monitoring this.
We are not having this line at the moment it was fixed here : https://github.com/contour-terminal/contour/commit/782fb7248d6fe643e7163bf57b0bcef50a81a8f7

Here is [godbolt](https://godbolt.org/#g:!((g:!((g:!((h:codeEditor,i:(filename:'1',fontScale:14,fontUsePx:'0',j:1,lang:c%2B%2B,selection:(endColumn:95,endLineNumber:6,positionColumn:95,positionLineNumber:6,selectionStartColumn:95,selectionStartLineNumber:6,startColumn:95,startLineNumber:6),source:'%23include+%3Cfmt/chrono.h%3E%0A%0Aint+main()+%7B%0A++//fmt::print(%22%7B:%25H:%25M%7D+%22,+fmt::localtime(std::chrono::system_clock::now()))%3B+ERROR%0A++fmt::print(%22%7B:%25H:%25M%7D%5Cn+%22,+fmt::localtime(std::chrono::system_clock::to_time_t(std::chrono::system_clock::now())))%3B+//+fix+%0A++fmt::print(%22%7B:%25H:%25M%7D%5Cn+%22,+fmt::localtime(std::time(nullptr)))%3B+//+what+we+have+at+the+moment%0A++%0A%7D%0A'),l:'5',n:'0',o:'C%2B%2B+source+%231',t:'0')),k:50,l:'4',n:'0',o:'',s:0,t:'0'),(g:!((g:!((h:compiler,i:(compiler:g122,deviceViewOpen:'1',filters:(b:'0',binary:'1',binaryObject:'1',commentOnly:'0',debugCalls:'1',demangle:'0',directives:'0',execute:'0',intel:'0',libraryCode:'0',trim:'1'),flagsViewOpen:'1',fontScale:14,fontUsePx:'0',j:1,lang:c%2B%2B,libs:!((name:fmt,ver:trunk)),options:'-O',overrides:!(),selection:(endColumn:1,endLineNumber:1,positionColumn:1,positionLineNumber:1,selectionStartColumn:1,selectionStartLineNumber:1,startColumn:1,startLineNumber:1),source:1),l:'5',n:'0',o:'+x86-64+gcc+12.2+(Editor+%231)',t:'0')),k:50,l:'4',m:50,n:'0',o:'',s:0,t:'0'),(g:!((h:output,i:(compilerName:'x86-64+gcc+12.2',editorid:1,fontScale:14,fontUsePx:'0',j:1,wrap:'1'),l:'5',n:'0',o:'Output+of+x86-64+gcc+12.2+(Compiler+%231)',t:'0')),header:(),l:'4',m:50,n:'0',o:'',s:0,t:'0')),k:50,l:'3',n:'0',o:'',t:'0')),l:'2',n:'0',o:'',t:'0')),version:4)  with example how we can fix at as well as present version of this line.

Anyway we need to release contour before fmt update,  @topazus how much time do we have before that?

**Comment by topazus** [comment]
> We are not having this line at the moment it was fixed here : [782fb72](https://github.com/contour-terminal/contour/commit/782fb7248d6fe643e7163bf57b0bcef50a81a8f7)

Thanks for the quick response. Ah, I also have seen this commit. I will make this commit as a patch to pass the build.
successful build: https://koji.fedoraproject.org/koji/taskinfo?taskID=102704040

**Comment by Yaraslaut** [comment]
> > We are not having this line at the moment it was fixed here : [782fb72](https://github.com/contour-terminal/contour/commit/782fb7248d6fe643e7163bf57b0bcef50a81a8f7)
> 
> Thanks for the quick response. Ah, I also have seen this commit. I will make this commit as a patch to pass the build. successful build: https://koji.fedoraproject.org/koji/taskinfo?taskID=102704040

Great that this is resolved now :)
Also, I think that in soonish we will make new release with few bug fixes: https://github.com/contour-terminal/contour/milestone/8

**Comment by christianparpart** [comment]
@topazus is it actually okay to bump the requirement for fmtlib to >= 10.0.0 or could that cause problems for older Fedora versions?

**Comment by christianparpart** [comment]
Update: I just realised that the code changes being planned (adapting fmtlib custom formatters to latest API changes) are also working on fmtlib 9.1.0 :)
