### ISSUE TITLE
dpi_scale problem

### ISSUE THREAD

**Issue by Yaraslaut** [contour-terminal/contour#1137]
### Contour Terminal version

Contour Terminal Emulator 0.3.13-master-e60326e5

### Installer source

Github: source code cloned

### Operating System

Arch

### Architecture

x86-64

### Steps to reproduce

set dpi_scale to 2 in config file

### Actual Behavior

![image](https://github.com/contour-terminal/contour/assets/44506630/49f04506-36f4-4cfb-8596-0f6bd71db1da)

### Additional notes

For comparison dpi_scale equal to 1
![image](https://github.com/contour-terminal/contour/assets/44506630/bc078cd8-bd1b-4da4-8b7f-ded6b48468fe)

**Comment by christianparpart** [comment]
I propose to remove that. Users should use don't size to configure don't size. This is a legacy workaround when dpi scale on Mac was really hard to understand for me wrt Qt and retina displays 

I would suggest to get rid of this logic all together instead. What do you think?

If there are future DPI issues, we should actually fix those.

**Comment by Yaraslaut** [comment]
> I propose to remove that. Users should use don't size to configure don't size. This is a legacy workaround when dpi scale on Mac was really hard to understand for me wrt Qt and retina displays
> 
> I would suggest to get rid of this logic all together instead. What do you think?
> 
> If there are future DPI issues, we should actually fix those.

sure, we can get rid of this configuration entry. I was just trying to look how it will affect this issue https://github.com/contour-terminal/contour/issues/1022

**Comment by christianparpart** [comment]
She used `dpi_scale: 1.0`. I don't think so. 🤔

**Comment by Yaraslaut** [comment]
> She used `dpi_scale: 1.0`. I don't think so. 🤔

I was thinking that dpi_scale can affect this bug and decided to check how it will look if I have double dpi
