### ISSUE TITLE
Some Ligatures seems to be not properly rendered

### ISSUE THREAD

**Issue by SBHattarj** [contour-terminal/contour#1143]
### Contour Terminal version

0.3.13-master-8c338b15

### Installer source

Github: source code cloned

### Operating System

Fedora Linux 38

### Architecture

x86-64

### Steps to reproduce

Just try using the ligatures for "===", "==", "!=", "!==", "</" they will only render one character width

### Expected Behavior

the ligatures should be renedered as multiple character width
![Screenshot from 2023-07-24 16-57-12](https://github.com/contour-terminal/contour/assets/79201315/05a8d073-4b93-4721-b1df-e70c99ba1f67)

### Actual Behavior

the ligatures are rendered as one character width
![Screenshot from 2023-07-24 16-58-49](https://github.com/contour-terminal/contour/assets/79201315/3be9db6e-f818-4565-bed1-c669479cd126)

**Comment by uspasojevic96** [comment]
Question, do you have strict_spacing set to true?

**Comment by christianparpart** [comment]
Hey @SBHattarj. Many thanks for the report. that should work in fact, i use these ligatures a lot myself, using `JetBrains Mono Nerd Font` font family.

What font family did you use?

@Yaraslaut I wonder if that could maybe be caused by #1139. I'll check ASAP.

**Comment by uspasojevic96** [comment]
It's definitely bugged on latest master

**Comment by Yaraslaut** [comment]
> Hey @SBHattarj. Many thanks for the report. that should work in fact, i use these ligatures a lot myself, using `JetBrains Mono Nerd Font` font family.
> 
> What font family did you use?
> 
> @Yaraslaut I wonder if that could maybe be caused by #1139. I'll check ASAP.

You are right, I just checked
