### ISSUE TITLE
Allow Arrow keys to be remaped like in tmux 

### ISSUE THREAD

**Issue by SBHattarj** [contour-terminal/contour#1147]
## Abstract
I had been using tmux and I have a remap there which maps ctrl + (h,j,k,l) to arrows. 

This makes it much faster to navigate through the different commands, but, sometimes I don't use tmux, and I would like to be able to use those remaps outside of tmux. 

As this terminal already has a way to define remaps of keystrokes, having this could be great, the terminal overall is the best out of the ones I used, so I think it'd be great to have this feature.

## Motivation

A quality of life improvement, Just to make it a little bit faster to work on the terminal when not using tmux.

**Comment by Yaraslaut** [comment]
Hi, great to hear that you enjoy contour :) 
This feature is definetely doable, I will add this to the milestone

**Comment by Yaraslaut** [comment]
@SBHattarj  
Here is input mapping that you can use to get this behaviour 
```
    - { mods: [Control],        key: H,             action: SendChars, chars: '\x1B[D'}
    - { mods: [Control],        key: J,             action: SendChars, chars: '\x1B[B'}
    - { mods: [Control],        key: K,             action: SendChars, chars: '\x1B[A'}
    - { mods: [Control],        key: l,             action: SendChars, chars: '\x1B[C'}
```

**Comment by SBHattarj** [comment]
> @SBHattarj Here is input mapping that you can use to get this behaviour
> 
> ```
>     - { mods: [Control],        key: H,             action: SendChars, chars: '\x1B[D'}
>     - { mods: [Control],        key: J,             action: SendChars, chars: '\x1B[B'}
>     - { mods: [Control],        key: K,             action: SendChars, chars: '\x1B[A'}
>     - { mods: [Control],        key: l,             action: SendChars, chars: '\x1B[C'}
> ```

Ohh, great, will try this. Thanks for letting me know.

**Comment by christianparpart** [comment]
@SBHattarj with the solution above, I think we can close this, right? In case you need any further support, just continue messaging here, or join us on Discord.

p.s.: You might be interested in only conditionally having the above mappings, such that it won't confuse you when you are inside vim or so. See the `mode` documentation in key mappings. You might be interested in `~Alt` (not alternate screen, i.e. primary screen apps, e.g. your shell but not vim/etc.)
