### ISSUE TITLE
show_title_bar options doesn't work as expected

### ISSUE THREAD

**Issue by rhcher** [contour-terminal/contour#1153]
### Contour Terminal version

Contour Terminal Emulator 0.3.13-master-59df9d6b

### Installer source

Github: source code cloned

### Operating System

Windows 11 wsl2 Arch

### Architecture

x86-64

### Steps to reproduce

Setting the show_title_bar option to true:
![image](https://github.com/contour-terminal/contour/assets/50723480/ba26cf3d-92c1-4f50-97ac-00308380a60e)

set to false:
![image](https://github.com/contour-terminal/contour/assets/50723480/dca37387-ef10-49cd-a31e-b7a304c16e09)

### Expected Behavior

When I set show_title_bar option to false, title will disappear.

### Actual Behavior

When I set show_title_bar option to false, title still exit.

**Comment by Yaraslaut** [comment]
Hm, I am not sure that contour can change this, usually this  behavior defined by window manager. Maybe @christianparpart  can correct me

**Comment by uspasojevic96** [comment]
This is Windows related, for linux this works properly, not sure if it's possible to remove decorations on Windows

**Comment by Utkarsh-khambra** [comment]
I can also repro this if I run contour under Linux virtual box vm in windows.

**Comment by Utkarsh-khambra** [comment]
Okay this is also present on Linux, on Gnome.
