### ISSUE TITLE
Repeatedly outputting `BEL` doesn't produce any sound

### ISSUE THREAD

**Issue by Utkarsh-khambra** [contour-terminal/contour#1162]
### Contour Terminal version

Contour Terminal Emulator 0.3.13-master-362a2868

### Installer source

Github: source code cloned

### Operating System

Fedora 38

### Architecture

x86-64

### Steps to reproduce

Run `for i in $(seq 20);do printf '\a'; sleep 1; done` in bash 

### Expected Behavior

Contour should ring bell every one second.

### Actual Behavior

Contour doesn't produce any sound.

### Additional notes

Other ways this can be repro'd is by doing `printf'\a' ` a bunch of time in shell, after a while no sound is produced for BEL character.

**Comment by Utkarsh-khambra** [comment]
Looks like it's related to SoundEffect qml type, instead using MediaPlayer type works well. @christianparpart  and @Yaraslaut  do we need the lower latency provided by SoundEffect type?

**Comment by christianparpart** [comment]
No we don't. It's just a bell !-)
