### ISSUE TITLE
Protect user from accidentally pasting too large input

### ISSUE THREAD

**Issue by christianparpart** [contour-terminal/contour#1198]
@Marenz just found out, that when pasting too big text data to Contour, it will freeze (or at least looks like this).

After a short investigation, we found out that the data to be pasted was still being pasted, it just takes very long. Most likely because the way we do it is certainly not most efficient.

## Action items

- [ ] Ask the user something like: "Are you sure you want to paste {X amount} characters?" in a Yes/No dialog and only continue pasting on Yes, abort otherwise.
- [ ] If the content is really to be pasted, make sure it's more efficiently done and NOT blocking the GUI thread

**Comment by Yaraslaut** [comment]
I noticed that `BracketedPaste` decmode restrict pasting more than one screen of text and is enabled by default, so if i for example start with 
```
echo "
> 
```
I can not paste large text. I am not sure what to do with this, maybe @christianparpart  or @j4james you can help out with what is the right solution for this one
