### ISSUE TITLE
DECSCPP causes the terminal to hang

### ISSUE THREAD

**Issue by j4james** [contour-terminal/contour#1205]
### Contour Terminal version

0.3.12.262

### Installer source

GitHub: release page

### Operating System

Ubuntu Linux 22.04

### Architecture

x86-64

### Steps to reproduce

Attempt to use the [`DECSCPP`](https://vt100.net/docs/vt510-rm/DECSCPP.html) sequence to set the terminal width, e.g. from a bash shell:

```bash
printf "\e[132\$|"
```

### Expected Behavior

The width of the terminal should change.

### Actual Behavior

The width remains as it was, but the terminals hangs. There is no further output, and it doesn't respond to keypresses. If I try to close the window, I get a message from the OS saying "This window is not responding. Do you want to force the application to exit, or wait for it to respond?"

**Comment by christianparpart** [comment]
On a very quick look, the GUI thread (Qt) and the Terminal I/O thread both try to acquire the lock on the terminal object and wait. This is the freeze I also noticed. What I could not figure out in an instant is why both wait, as in, who's holding the lock. Good question. Many thanks, @j4james. We'll investigate that. This used to work. I wonder if it's possible to add it to our headless integration test suite. 🤔
