### ISSUE TITLE
Contour doesn't start with Qt5

### ISSUE THREAD

**Issue by uspasojevic96** [contour-terminal/contour#1209]
### Contour Terminal version

0.3.13-master-4189e91a

### Installer source

Github: source code cloned

### Operating System

Gentoo

### Architecture

x86-64

### Steps to reproduce

Build `contour` with Qt5, when you attempt to run it you will be greeted by this lovely message:

```
Warning: QQmlApplicationEngine failed to load component ((null):0, (null))
Warning: qrc:/contour/ui/main.qml:30:5: Type Terminal unavailable (qrc:/contour/ui/main.qml:30, (null))
Warning: qrc:/contour/ui/Terminal.qml:92:5: AudioOutput is not a type (qrc:/contour/ui/Terminal.qml:92, (null))
```

### Expected Behavior

Contour runs

### Actual Behavior

Contour doesn't run

### Additional notes

The reason for this is because `AudioOutput` doesn't exist on Qt5, it's Qt6 QML type, for Qt5 there is something called `Audio`

Qt5: https://doc.qt.io/qt-5/qml-qtmultimedia-audio.html
Qt6: https://doc.qt.io/qt-6/qml-qtmultimedia-audiooutput.html

**Comment by Yaraslaut** [comment]
One of the issues is that QML types for audio between Qt5 and Qt6 changed significantly, and setting `AudioOutput` or `Audio` in dependence of qt version is not enough since further differences appear in `MediaPlayer`
