### ISSUE TITLE
OS/X emoji size too small (due to HighDPI screens)

### ISSUE THREAD

**Issue by christianparpart** [contour-terminal/contour#1215]
seems like we are taking the  DPI into account when loading the colored emoji font face in the open_shaper implementation.

**Comment by Yaraslaut** [comment]
Was it fixed in https://github.com/contour-terminal/contour/pull/1216 ?

**Comment by christianparpart** [comment]
@Yaraslaut oh yes, you were right, i forgot to close it. thanks. :)

**Comment by erf** [comment]
Seems like the emojis are still small in the latest release

**Comment by christianparpart** [comment]
Oh interesting. Many thanks for your interest, @erf.

<img width="597" alt="image" src="https://github.com/contour-terminal/contour/assets/56763/c53c87af-e1b4-4e68-bb82-733f50ae2f67">


This is how it is for me on latest version. I wonder what might have caused this for you to still be small. Hmmm... Would you mind sharing a little bit more info? I might be able to direct you to some logging hints tomorrow (too tired now) :)

**Comment by erf** [comment]
Here is a screenshot. It only seem to happen on an external monitor using a m1 macbook.

![Screenshot 2023-12-20 at 00 18 46](https://github.com/contour-terminal/contour/assets/1562523/9f3e5546-89ec-4104-8338-7f136e1b26b4)

If i'm on my internal montor it seem ok - but notice the heart emojis does only take up a single col width .. i've enabled mode 2027

<img width="787" alt="Screenshot 2023-12-20 at 00 28 57" src="https://github.com/contour-terminal/contour/assets/1562523/8d26f3e7-4d96-4485-9068-ca74db9a22e4">

**Comment by christianparpart** [comment]
Hi,

<img width="873" alt="image" src="https://github.com/contour-terminal/contour/assets/56763/5d00b4f0-92b5-4b3c-860e-427e4a6be8b3">
So this is how it looks like on my M1. It should work (tm). I think it may of course be a system installation deviation between your M1 and my M1. Do you use a custom emoji font (anywhere)? Would you mind sharing your contour.yml config (the font configuration part at least)?

On the DPI issue that you're facing on an external monitor, I think we may need a drop-out ticket, that specifically addresses that issue. I am not having an external display next to me, but I will check ASAP as well. Many thanks for reporting (and sorry for the inconveniences :) )

**Comment by erf** [comment]
Hey, i just used the default config file. The heart issue seem to be in my editor (but also in vim, nvim), but if i `cat` the file it seem ok ... untill i drag the mouse and select that line .. very weird . i made a screen recording:

https://github.com/contour-terminal/contour/assets/1562523/83d2758c-9a3a-40cd-9942-96988208318f

**Comment by christianparpart** [comment]
Yeah, this one we'll be tracking in #1375. Many thanks :)
