### ISSUE TITLE
Consider integrating window alerting with the bells

### ISSUE THREAD

**Issue by Ne02ptzero** [contour-terminal/contour#1247]
Hello!

I currently have this patch running locally for my terminals:
```diff
diff --git a/src/contour/ui.template/Terminal.qml.in b/src/contour/ui.template/Terminal.qml.in
index 05dca56a..ada218fd 100644
--- a/src/contour/ui.template/Terminal.qml.in
+++ b/src/contour/ui.template/Terminal.qml.in
@@ -194,6 +194,7 @@ ContourTerminal
         if(bellSoundEffect.playbackState === MediaPlayer.PlayingState)
             bellSoundEffect.stop()
         bellSoundEffect.play()
+        Window.window.alert(0)
     }

     function updateFontSize() {
```

Which enables the visual cues with my window manager when a bell is ringed from a terminal (Please note that I use the `bell: "off"` in my configuration, as I do not want any sounds). This feature is used by weechat (When an highlights pops, or a DM), mutt (When I receive a new mail), or many scripts where I added `echo "\a"` at the end to notify me that the script is done (Big compilations are the prime example of this).

![2023-10-10_264x39_scrot](https://github.com/contour-terminal/contour/assets/6032832/3f4a1c46-9725-404e-ba74-cd960241eac0)
(In this example, I'm in another workspace and the terminal is raising an alert).

I'm fully aware that the above diff is pretty basic, and cannot be merged as-is. I'm open to directions/cues for properly implementing this upstream, as I'm sure I'm not the only one used to this feature from different terminal emulators.

**Comment by uspasojevic96** [comment]
Thanks for the idea and willingness to implement this, here is a checklist that I came up with on the fly:

- [ ] Create config option for window alerts
- [ ] Create function in QML which would be called to run window alerts
- [ ] Create C++ function which would trigger QML function on specific event
