### ISSUE TITLE
Mirror, something messed up!!!

### ISSUE THREAD

**Issue by sonulohani** [contour-terminal/contour#125]
## Description

Screenshot is enough

![image](https://user-images.githubusercontent.com/2958681/87248176-99df7e00-c475-11ea-8aa7-3255cfc31fbc.png)

## Environment

- Contour Version or Git commit hash: 823fdbab98588322d33ee05197e2ab6bf6e89d74
- Operating System (name / distribution / version): Windows 10 2004
- Contour configuration: Default
- TERM environment variable:
- Compiler version: MSVC 16

## Steps to Reproduce

Just compile and launch.

**Comment by christianparpart** [comment]
Haha nice. Thanks for the report. I will be checking tonight.

**Comment by christianparpart** [comment]
Have a look at https://github.com/christianparpart/contour/commit/5bd4a26eee783470d36deba3184b7420f39be952

The cmake variable `LIBTERMINAL_VIEW_NATURAL_COORDS` should be set to `ON`. This is some work-in-progress change of mine reversing the Y-axis in OpenGL (I failed at that, last week, and decided to cmake-disable these new code paths to work on them later).

**Comment by Yaraslaut** [comment]
Is it still a valid issue? @sonulohani

**Comment by sonulohani** [comment]
I don't know. I don't use windows anymore.

**Comment by Yaraslaut** [comment]
> 

Oh, great chose :) 
Hope you are having a good experience with contour on OS that you are using at the moment.
I am closing the issue as completed then, since this is not happening at the moment on Windows.
