### ISSUE TITLE
Truncated % symbols

### ISSUE THREAD

**Issue by cqexbesd** [contour-terminal/contour#1262]
### Contour Terminal version

0.4.0-master-616315cc

### Installer source

Github: source code cloned

### Operating System

Arch Linux as of approx a week ago

### Architecture

x86-64

### Steps to reproduce

Type `%`

### Actual Behavior

![image](https://github.com/contour-terminal/contour/assets/6312149/e1c0ece8-404d-4355-949e-8b382bc74c7c)

The truncation occurs when using the `SF Mono` or `LiberationMono` font.

**Comment by christianparpart** [comment]
@Yaraslaut didn't we recently work on texture atlas wrt vertical bar? that smells related.

**Comment by Yaraslaut** [comment]
we did, https://github.com/contour-terminal/contour/issues/1022  issue was LCD rendering, this looks more like font fallback fault for me

**Comment by Yaraslaut** [comment]
I can not reproduce it, so it seems this is font fallback
![image](https://github.com/contour-terminal/contour/assets/44506630/e38b0264-ddd5-4cc9-9c01-cc119decc6d9)

**Comment by christianparpart** [comment]
IIRC @cqexbesd is running a really small font size at only 96dpi. This is also why is underline at small font sizes looks so creepy. I can look at it once feeling less sick and back in the office, so I can investigate with him together at his desk :)

**Comment by christianparpart** [comment]
> I can not reproduce it, so it seems this is font fallback. This is LiberationMono

I think this requires a small enough font to be reproducible.

**Comment by Yaraslaut** [comment]
I tried to reproduce this with small font (down to 5 pt) and still can not reproduce this behavior, @cqexbesd if you still have this bug, output of `contour debug "font.render,vt.rasterizer,font.textshaping"` can give us some hints

**Comment by cqexbesd** [comment]
I just updated to the latest master and I can't reproduce it anymore either so I think it has been fixed. Thanks!
