### ISSUE TITLE
Printing over 2nd cell in wide character should delete wide character

### ISSUE THREAD

**Issue by mitchellh** [contour-terminal/contour#1268]
### Contour Terminal version

brew installed, unsure

### Installer source

something else (please specify below)

### Operating System

macOS 14

### Architecture

AArch64

### Steps to reproduce

```
#!/usr/bin/env bash
printf "橋"
printf "\033[D"
printf "X"
read
```

### Expected Behavior

Terminal state should be ` X` (note space prefix) according to behavior matching xterm, iTerm, urxvt, libvte-based terminals.

### Actual Behavior

Terminal state became `橋X` with the wide character taking 1 cell instead of 2.

**Comment by christianparpart** [comment]
thanks, will do!
