### ISSUE TITLE
DPI adjustment at least sometimes broken

### ISSUE THREAD

**Issue by christianparpart** [contour-terminal/contour#1299]
At least I noticed that on MacOS, where I am clearly having an HiDPI screen (192x192 DPI) and I frequently attach/detach/re-attach a different screen with a different DPI value.

What should happen is, that the font size remains the same, and thus, the cell dimensions are not touched at all.

What does happen is, that the front size is either crazy big or crazy small.

This also leads to bad calculation of mouse position to grid cell mapping.

I am experiencing this issue on MacOS/X the most, but it's most likely an issue on any platform, which can adapt to DPI changes live (e.g. KDE Plasma / Windows)

**Comment by whisperity** [comment]
Windows 10 does the same when switching between screen configurations. It's either related to DPI or automatic scaling.

**Comment by sfc9982** [comment]
Something may help:

https://doc.qt.io/qt-6/highdpi.html
https://forum.qt.io/topic/136604/how-can-i-make-my-app-ignore-window-s-high-dpi-scaling/8
https://github.com/Chatterino/chatterino2/issues/4552

**Comment by christianparpart** [comment]
Hey @sfc9982, sorry for the late reply, I somehow must have skipped it. We sadly must not ignore hidpi scaling settings, as otherwise, standard GUI elements (like scrollbar or popup windows) would not look nice on a high dpi screen. I finally found the root cause of the issue and have it fixed in #1365. This was the last major blocker for the next release.
