### ISSUE TITLE
Bypass conpty when using ssh.

### ISSUE THREAD

**Issue by ferdinandyb** [contour-terminal/contour#1319]
## Abstract

`conpty` makes a lot of trouble on Windows. Just skip it entirely and connect to the remote machine directly. It would be even greater if somehow you could ssh into WSL and skip conpty there as well.

## Motivation

We all know conpty is trouble and if you are only using the terminal to access linux, it really does not seem necessary to have it in the loop.

**Comment by christianparpart** [comment]
This would be a feature we could make available on all platforms, not just Windows. But Windows (due to its ConPTY limitations) would be most benefiting from it. I finally see a good reason why a terminal should provide support for directly connecting to an SSH server.
