### ISSUE TITLE
Ctrl+Keypad Plus seem not to work 

### ISSUE THREAD

**Issue by Glog78** [contour-terminal/contour#1325]
### Contour Terminal version

0.4.0.r4132.31248d53

### Installer source

Github: source code cloned

### Operating System

Arch

### Architecture

x86-64

### Other Software

none

### Steps to reproduce

I have the following lines in my input mapping:
    - { mods: [Control],        key: Plus,                action: IncreaseFontSize }
    - { mods: [Control],        key: Minus,             action: DecreaseFontSize }

Press ctrl + (Numpad) Plus or ctrl + (Numpad) Minus

### Expected Behavior

Resizing the Font Size 

### Actual Behavior

Nothing

### Additional notes

Works with the regular Minus and Plus and worked with the last version i  used.

**Comment by christianparpart** [comment]
nice, finaally somebody that actually uses the keypad. Was this **ever** working? When introducing CSIu keyboard protocol,  I noticed that we didn't really properly implement keypad encoding, and that in the Qt frontend side of life, we didn't even have the mappings for it. So (post 0.3.12 release) I killed it, and just revived the backend-side of it just yesterday night (#1324). Looks like I need to further invest in getting the frontend side working (again), as well.

```yaml
- { mods: [Control], key: Plus, action: IncreaseFontSize }
- { mods: [Control], key: Minus, action: DecreaseFontSize }
```

ok, lemme get a full-sized keyboard, to repro and finish the implementation then. :)

**Comment by Glog78** [comment]
Thank you for looking into it. Yes it was working but please don't ask me which version of 0.3.x.

**Comment by Glog78** [comment]
Thanks for fixing :) works now

**Comment by Glog78** [comment]
btw there seems to be a regression ... at least in current versions and i dunno since when version the numpad doesn't work again

**Comment by Yaraslaut** [comment]
I will reopen it, just in case so we will not forget about it
also, new release is coming soon, you can check if this is fixed on master, if not, we will investigate further

**Comment by Glog78** [comment]
Contour Terminal Emulator 0.4.4-master-34289b23

    - { mods: [Control],        key: Numpad_Add,     action: IncreaseFontSize }
    - { mods: [Control],        key: Numpad_Plus,    action: IncreaseFontSize }
    - { mods: [Control],        key: Plus,           action: IncreaseFontSize }
    - { mods: [Control],        mouse: WheelUp,      action: IncreaseFontSize }
    - { mods: [Control],        key: Numpad_Subtract,action: DecreaseFontSize }
    - { mods: [Control],        key: Numpad_Minus,   action: DecreaseFontSize }
    - { mods: [Control],        key: Minus,          action: DecreaseFontSize }
    - { mods: [Control],        mouse: WheelDown,    action: DecreaseFontSize }

Numpad doesn't work.

**Comment by Yaraslaut** [comment]
@Glog78  will be fixed on master soon
