### ISSUE TITLE
SSH'ing causes backspace and other keys to break

### ISSUE THREAD

**Issue by peterwilli** [contour-terminal/contour#1329]
### Contour Terminal version

0.3.12

### Installer source

something else (please specify below)

### Operating System

Arch Linux

### Architecture

x86-64

### Other Software

OpenSSH_9.5p1, OpenSSL 3.1.4 24 Oct 2023

### Steps to reproduce

See https://asciinema.org/a/619888

1. Open Contour
2. Log in with SSH
3. Try backspace

### Expected Behavior

The text is being erased

### Actual Behavior

It seems the last characters get echoed back to me

**Comment by uspasojevic96** [comment]
Change TERM or add contour terminfo on target remote

**Comment by peterwilli** [comment]
> Change TERM or add contour terminfo on target remote

I just figured that out! I solved it with adding `TERM=xterm-256color` to `~/.zshrc` on the client. (If you use bash you have to put it in `~/.bashrc`)

**Comment by peterwilli** [comment]
> Hey @peterwilli I generally highly recommend installing the `contour` terminfo to remote hosts. Maybe we should provide that as single downloadable file on the release page for such cases. At least if you're using one of the more advanced functionalities. :)

First of all, thanks for making such an awesome terminal! I love it so much, best of alacritty and usual desktop terminal emulators!

And yeah, perhaps that is better, but this is not always an option for those that SSH into servers that they don't have admin access to (assuming that one needs that for adjusting terminfo) or are otherwise read-only

**Comment by Yaraslaut** [comment]
> > Hey @peterwilli I generally highly recommend installing the `contour` terminfo to remote hosts. Maybe we should provide that as single downloadable file on the release page for such cases. At least if you're using one of the more advanced functionalities. :)
> 
> First of all, thanks for making such an awesome terminal! I love it so much, best of alacritty and usual desktop terminal emulators!
> 
> And yeah, perhaps that is better, but this is not always an option for those that SSH into servers that they don't have admin access to (assuming that one needs that for adjusting terminfo) or are otherwise read-only

Here is a list of places that you can place your terminfo file 
```
       Libraries that read terminfo entries are expected to check in succession

       •   a location specified with the TERMINFO environment variable,

       •   $HOME/.terminfo,

       •   directories listed in the TERMINFO_DIRS environment variable,

```
for contour you can place it in `$HOME/.terminfo/c/contour`.
