### ISSUE TITLE
terminal_size in config ignored

### ISSUE THREAD

**Issue by Glog78** [contour-terminal/contour#1338]
### Contour Terminal version

Contour Terminal Emulator 0.4.0-makepkg-ad0159b1

### Installer source

Github: source code cloned

### Operating System

Arch

### Architecture

x86-64

### Other Software

none / maybe kde

### Steps to reproduce

setup a terminal size of 150x40 in ~/.config/contour.yml (main profile)

terminal_size:
  columns:·150
  lines:·40

### Expected Behavior

the starting window to be 150x40

### Actual Behavior

the starting window is 80x25

### Additional notes

i checked that there is no pre definition setting from kde on the window. 

![image](https://github.com/contour-terminal/contour/assets/7598856/ad4a48d0-9d4d-4529-8335-36e1b5e6d801)

**Comment by uspasojevic96** [comment]
This is fixed with https://github.com/contour-terminal/contour/commit/3682106fa45829b84e98ab77c0ef13bb799ad73d

**Comment by christianparpart** [comment]
Yeah, sorry for the inconveniences, @Glog78 :)

**Comment by Glog78** [comment]
fixed

**Comment by Glog78** [comment]
Ok i guess the current implementation of calculating the window size ignores a dpi setting in kde ( see attached screenshot )

If i define terminal size to 85x35 with a 14+ sized font the window has some space on the right side and on the lower side.

<img width="522" height="105" alt="Image" src="https://github.com/user-attachments/assets/f753ed1e-363e-4ef4-8a79-1d3c51cbeeb8" />
