### ISSUE TITLE
Extra fast scrolling when using trackpad

### ISSUE THREAD

**Issue by 0x5c** [contour-terminal/contour#1360]
### Contour Terminal version

Contour Terminal Emulator 0.4.0

### Installer source

Github: source code cloned

### Operating System

VoidLinux

### Architecture

x86-64

### Other Software

Built with Qt 6

### Steps to reproduce

Open contour, use trackpad to scroll

### Expected Behavior

The rate of scroll events matches other terminals, and the scrolling isn't jittery (no flashing through up/down/up/down/...)

### Actual Behavior

The rate of scroll events is too fast, to the point of being mostly unusable. The scroll events are also frequently alternating up/down fast when the movement of the fingers on the trackpad is at the limit of the trackpad's sensing precision.

### Additional notes

This also happens with the latest release (`v0.3.12.262`).
Normal mouse scrollwheels don't seem to be affected. The trackpoint on my laptop might also be affected but it's much harder to tell.

**Comment by christianparpart** [comment]
@0x5c: we've just merged a fix to master. Is it possible for you to confirm that it is also working for **you**?

Otherwise, we're about to release ASAP 0.4.1 as well.

**Comment by 0x5c** [comment]
I can confirm that the fix works perfectly, applied as a patch on top of 0.4.0 along with the margins one.
