### ISSUE TITLE
CSI u mode confuses neovim

### ISSUE THREAD

**Issue by classabbyamp** [contour-terminal/contour#1373]
### Contour Terminal version

0.4.0

### Installer source

Github: source code cloned (Void package, technically)

### Operating System

Void Linux

### Architecture

x86-64

### Other Software

neovim 0.9.4
vim-surround at this commit, I think: https://github.com/tpope/vim-surround/tree/baf89ad26488f6a7665d51b986f5c7ad2d22b30b

### Steps to reproduce

1. set keyboard layout to non-ANSI QWERTY (I'm using Canadian French, e.g. `setxkbmap -layout ca`)
2. enter neovim 
3. enter insert mode and type `'a'`
4. leave insert mode, put the cursor over the `a`, and type `cs'"` to change the surrounding `'` to `"`

### Expected Behavior

buffer contains `"a"`

### Actual Behavior

buffer contains `<80><fc>^B"a<80><fc>^B"`

### Additional notes

See also:
- https://github.com/tpope/vim-surround/issues/313
- https://codeberg.org/dnkl/foot/pulls/1017

I believe this is caused by CSI u mode not having the semantics neovim expects. Following the semantics foot uses in the above PR will probably fix this. On my layout, `"` is <kbd>Shift</kbd> + <kbd>2</kbd> (and `'` is <kbd>Shift</kbd> + <kbd>,</kbd>, so this can be reproduced with other combinations of characters like `cs"'`)

**Comment by christianparpart** [comment]
Merry christmas, @classabbyamp . I have fixed this now and it works for me (i could repro it using German keyboard layout as well). I would still like you to confirm that it also works for YOU. :)

You may need to rebuild from source. Please ping us, if you need some kind of assistance.

**Comment by classabbyamp** [comment]
can confirm that it is fixed with that patch, thanks!
