### ISSUE TITLE
Better default bell sound

### ISSUE THREAD

**Issue by erf** [contour-terminal/contour#1378]
## Abstract

The default bell sound '\u0007' is bad to my ears 

## Motivation

Change default bell sound to default macOS sound

## Specification

Use same sound as on Terminal.app and iTerm2.app

**Comment by whisperity** [comment]
In general, it would be better if the default behaviour of the bell was to trigger the DE-specific default notification sound, with the option to override it in Contour.

**Comment by Yaraslaut** [comment]
What if we use this bell sound ? 
https://commons.wikimedia.org/wiki/File:Bicycle-bell-2.wav
