### ISSUE TITLE
`.zip` release is no longer available

### ISSUE THREAD

**Issue by T-727** [contour-terminal/contour#1389]
### Contour Terminal version

0.4.0.6245

### Installer source

GitHub: release page

### Operating System

Windows 11 23H2

### Architecture

x86-64

### Other Software

scoop 0.3.1

### Steps to reproduce

Hey! this isn't really an issue to "reproduce" so I'll just use this field to explain the problem.

I noticed that my package manager ([scoop](https://github.com/ScoopInstaller/Scoop)) hasn't automatically updated [it's contour manifest](https://github.com/ScoopInstaller/Extras/tree/master/bucket/contour.json).
I tried to investegate and looks like it tried to look for the `.zip` and didn't find it, and indeed `.zip` releases were removed in https://github.com/contour-terminal/contour/commit/7ea39920fe76a48e63f15a2ed6a4a7ecf0cf73df right before the `0.4.0.6245` release.
This is a bit problematic because the `.msi` release cannot be silently extracted, instead the user has to face the "unknown publisher" dialog and click stuff to proceed since the `.msi` doesn't have a security certificate.

### Expected Behavior

Keep `.zip` release for Windows or use security certificates.
Or in case I haven't looked hard enough please point me to the relevant discussion 😅

### Actual Behavior

`.zip` releases are no longer available

### Additional notes

Thanks for making great stuff!

**Comment by christianparpart** [comment]
Hey @T-727 Oh many thanks. We'll soon be releasing 0.4.1 (this year ASAP). We'll be re-adding .zip files for Windows again. Many thanks for your feedback. Is it okay to wait for a couple of more days for 0.4.1 to also include a win64 ZIP package?

Have nice Christmas days.

**Comment by T-727** [comment]
> We'll be re-adding .zip files for Windows again.
Great! Thank you so much.
> Is it okay to wait for a couple of more days for 0.4.1 to also include a win64 ZIP package?
Absolutely, take your time.

Thanks also for the quick response 😄 
And happy holidays to you too
