### ISSUE TITLE
Segfault on Ubuntu

### ISSUE THREAD

**Issue by ferdinandyb** [contour-terminal/contour#1405]
### Contour Terminal version

Contour Terminal Emulator 0.4.2-master-20f76b90

### Installer source

Github: source code cloned

### Operating System

 Ubuntu 22.04.3 LTS

### Architecture

x86-64

### Steps to reproduce

Build from scratch as per the README. Try to run from another terminal.

### Actual Behavior

```
❯ contour
Gtk-Message: 16:21:17.252: Failed to load module "xapp-gtk3-module"
Warning: QGLXContext: Failed to create dummy context ((null):0, (null))
[error] Default output device doesn't support 16 Bit signed integer PCM
Warning: QRhiGles2: Failed to create temporary context ((null):0, (null))
Warning: QRhiGles2: Failed to create context ((null):0, (null))
Warning: Failed to create RHI (backend 2) ((null):0, (null))
Fatal: Failed to initialize graphics backend for OpenGL. ((null):0, (null))
[1]    3351126 IOT instruction (core dumped)  contour
```

**Comment by Yaraslaut** [comment]
This is what I see on  Ubuntu 22.04.03:
![image](https://github.com/contour-terminal/contour/assets/44506630/ce58d7ee-1581-42c2-9e21-4440fabf71b8)
Other than that, Contour starts well
Do you have something specific on your system @ferdinandyb  ?

**Comment by ferdinandyb** [comment]
I have Regolith (i3), but that's the only thing I can think of.

**Comment by Yaraslaut** [comment]
I tested with Regolith and with X11 session contour starts, i could not try with Wayland since it crashed and could not open environment inside vm.

**Comment by ferdinandyb** [comment]
On Wed Jan 10, 2024 at 16:47, Yaraslau ***@***.***> wrote:
> I tested with Regolith and with X11 session contour starts, i could not try with Wayland since it crashed and could not open environment inside vm.

I have honestly no idea ...

**Comment by ferdinandyb** [comment]
So a lesson has been learned here. If you update the kernel or the GPU drivers on your machine, do yourself a favour and restart the computer.

**Comment by whisperity** [comment]
@ferdinandyb I mean, can't Contour catch the fact that the context didn't initialise and at least show an error hinting at possible reasons (this one included)?

**Comment by ferdinandyb** [comment]
Well, sure, ideally it would exit with an error code instead of a segfault at least, better, explicitly complain about OpenGL.
