### ISSUE TITLE
weechat input line behaives strange

### ISSUE THREAD

**Issue by Glog78** [contour-terminal/contour#1416]
### Contour Terminal version

0.4.2-master-20f76b90

### Installer source

Github: source code cloned

### Operating System

Arch

### Architecture

x86-64

### Other Software

weechat 4.2.0 git master

### Steps to reproduce

start weechat
input: /connect freenode

### Expected Behavior

/connect freenode

### Actual Behavior

it shows & the cursor seems to be positioned wrong
/connectfreenode

### Additional notes

I did a check with urxvt to see if it is contour or weechat and urxvt is ok
TERM="contour"
COLORTERM="truecolor"
contour.yml -> https://paste.rs/JP5A4

**Comment by christianparpart** [comment]
Good morning. I thought I just fixed that (PR merged last night). I will check with weechat.

P.s. I did not check your version hash suffix (I am on phone right now), but maybe the fix was merged after you updated last time. :)

**Comment by Glog78** [comment]
fixed with latest build :) thanks for the hint i didn't checked the commit messages this night. Have a great day.
