### ISSUE TITLE
SSH should not ask for password if the key is not protected with one.

### ISSUE THREAD

**Issue by ferdinandyb** [contour-terminal/contour#1425]
### Contour Terminal version

Contour Terminal Emulator 0.4.0.6088

### Installer source

something else (please specify below)

### Operating System

Windows 11

### Architecture

x86-64

### Steps to reproduce

Set up an SSH profile with an ssh key that is not password protected.

### Actual Behavior

If you use an ssh profile contour will ask for a password even if there is no password. Pressing enter on the password prompt works, but it should not be necessary.

**Comment by christianparpart** [comment]
I think the only way to find out that an SSH key without a password doesn't need one is by first trying with an empty password, and if that fails, ask for one. 🤔 I wonder what the other SSH clients are doing in such cases.

Am I assuming correctly that now (for the time being), you simply hit enter to continue and then it works?

**Comment by ferdinandyb** [comment]
On Sat Jan 27, 2024 at 23:12, Christian Parpart ***@***.***> wrote:
> I think the only way to find out that an SSH key without a password doesn't need one is by first trying with an empty password, and if that fails, ask for one. 🤔 I wonder what the other SSH clients are doing in such cases.
>
> Am I assuming correctly that now (for the time being), you simply hit enter to continue and then it works?

Exactly.
