### ISSUE TITLE
Improve documentation on hyperlink decorations

### ISSUE THREAD

**Issue by christianparpart** [contour-terminal/contour#1437]
we apparently miss that in the docs/website as well as the default contour.yml configuration file:

possible values are:

- underline
- dotted-underline
- double-underline
- curly-underline
- dashed-underline
- overline
- crossed-out
- framed
- encircle (i think that one is not realy implemented)

**Comment by saliaku** [comment]
can i help contribute ?

**Comment by uspasojevic96** [comment]
@saliaku yes you can, there is sample config in https://github.com/contour-terminal/contour/blob/master/src/contour/contour.yml where you can update the comments for the decorations

**Comment by christianparpart** [comment]
@saliaku Many thanks for your interest. We really highly appreciate that. Also, you may want to join our Discord for some somewhat more realtime communication :)

**Comment by saliaku** [comment]
I am happy to contribute if only you could tell me exactly what to do , I currently use debian 12 on my laptop

**Comment by christianparpart** [comment]
Have python around, so you can run the documentation website locally, then do this:

```sh
virtualenv .venv               # create a virtual env for python packages
source .venv/bin/activate      # see for alternative files extensions, depending on your shell)
mkdocs serve -a 127.0.0.1:8080 # will spawn a tiny website on localhost:8080
```

edit the files, which @uspasojevic96 mentioned (or any other documentation file) and then fire up your web browser and have it pointing to http://127.0.0.1:8080/ to prove-read.

You can deactivate the virtual python environment via `deactivate` and re-activate it whenever you resume working by rerunning the above `source ...` command again.

**Comment by saliaku** [comment]
virtual env up and runnig 
have made the necessary comments pls do check

**Comment by christianparpart** [comment]
Create a PR so we can :)

It is late night there now. I will check up later then :)

**Comment by saliaku** [comment]
I still havent got the hang of contributing , I would be awake for some more hours for sure

**Comment by christianparpart** [comment]
What time zone are you inz we can screen share help you via discord Tomorrow. I should be somewhat available during the day and late evening (UTC+1 here - Germany). P.s.: do not commit the .venv folder but only the changes you have made.

**Comment by saliaku** [comment]
I am in IST( +5:30 ) would be available after 12 noon IST

**Comment by saliaku** [comment]
I will be free in 3 hours

**Comment by christianparpart** [comment]
> I will be free in 3 hours

Join me in https://discord.gg/ncv4pG9 in channel #ASMR-coding :)

**Comment by saliaku** [comment]
is this issue closed ?

**Comment by uspasojevic96** [comment]
it will auto close when merge happens
