### ISSUE TITLE
possible values of hyperlink decoration are undocumented

### ISSUE THREAD

**Issue by ferdinandyb** [contour-terminal/contour#1440]
The possible values from discord:

- underline
- dotted-underline
- double-underline
- curly-underline
- dashed-underline
- overline
- crossed-out
- framed
- encircle (i think that one is not realy implemented)

**Comment by Yaraslaut** [comment]
Duplicate of https://github.com/contour-terminal/contour/issues/1437 :)

**Comment by ferdinandyb** [comment]
damn sorry
