### ISSUE TITLE
Add key bindings documentation to the web page

### ISSUE THREAD

**Issue by Yaraslaut** [contour-terminal/contour#1442]
We currently have information regarding key bindings available in the configuration [file](https://github.com/contour-terminal/contour/blob/master/src/contour/contour.yml). However, there is a lack of corresponding details on our website, http://contour-terminal.org/. We need to update the web page to include this information.

**Comment by saliaku** [comment]
on it :+1:  please do let me know which all file are to be changed

**Comment by Yaraslaut** [comment]
> on it 👍 please do let me know which all file are to be changed @Yaraslaut

for key bindings we need to create a separate file similar to [profiles](https://github.com/contour-terminal/contour/blob/master/docs/configuration/profiles.md)

**Comment by saliaku** [comment]
yaa i will look into this, would appreciate if I could get some more help :bow:

**Comment by christianparpart** [comment]
@saliaku maybe it helps if you read through the existing documentation (on source level). It's not much, we don't have much yet, so it shouldn't take long at all.

This should give you a good understanding on how to extend it. 

On top of that, feel free to ask questions on Discord, in `#contour-dev` or `#contour` chat. :)

**Comment by Yaraslaut** [comment]
@saliaku  is there any updates? do you need any help?
