### ISSUE TITLE
Monitor scaling behaves weird on Windows.

### ISSUE THREAD

**Issue by ferdinandyb** [contour-terminal/contour#1465]
### Contour Terminal version

Contour Terminal Emulator 0.4.3.6442

### Installer source

GitHub: release page

### Operating System

Windows

### Architecture

x86-64

### Steps to reproduce

Have two monitors where one is set to 100% scale and the other to 125% scale. Open contour on the 100% scale monitor and move it to the other one.

### Actual Behavior

This is how contour looks on the 100% scale monitor:
![image](https://github.com/contour-terminal/contour/assets/6343487/3e5af98b-e16f-4d5a-af99-78c2a8bbe5da)

And this is how it looks on the 125% scale monitor:
![image](https://github.com/contour-terminal/contour/assets/6343487/6846c568-615b-4ed5-9d27-0c62e5e59229)

The horizontal distance between characters is somehow squished.

Here's another view on the 125% scale monitor, where the top one was opened on the 125% scale monitor, while the other one was opened on the 100% scale and move to the 125% scale:
![image](https://github.com/contour-terminal/contour/assets/6343487/3a5b9a41-ba4c-4773-83f3-23a581df424a)

**Comment by Yaraslaut** [comment]
Can be connected to https://github.com/contour-terminal/contour/issues/940

**Comment by christianparpart** [comment]
This is an interesting one. I actually implemented responding to monitor changes (and thus, responding to DPI changes) in the frontend code. But I obviously did something wrong there. At least it worked back then when we only used Qt Widgets. We need to re-assure how this should be working when using QML I think... 🤔

**Comment by ferdinandyb** [comment]
@christianparpart I just grabbed the later msi from https://github.com/contour-terminal/contour/actions/runs/8314676103, because I thought #1487  might fix this and indeed it did.

**Comment by Yaraslaut** [comment]
> @christianparpart I just grabbed the latest msi from https://github.com/contour-terminal/contour/actions/runs/8314676103, because I thought #1487 might fix this and indeed it did.

Thanks for checkin @ferdinandyb  :) 
I am closing this issue then
