### ISSUE TITLE
Ubuntu 22.04 Debian package missing dependency on libssh2

### ISSUE THREAD

**Issue by pdietl** [contour-terminal/contour#1471]
### Contour Terminal version

0.4.3.6442

### Installer source

GitHub: release page

### Operating System

Ubuntu 22.04.3 LTS

### Architecture

x86-64

### Steps to reproduce

wget https://github.com/contour-terminal/contour/releases/download/v0.4.3.6442/contour-0.4.3.6442-ubuntu22.04-amd64.deb
sudo apt remove libssh2-1
sudo apt install ./contour-0.4.3.6442-ubuntu22.04-amd64.deb
contour
# contour: error while loading shared libraries: libssh2.so.1: cannot open shared object file: No such file or directory

### Expected Behavior

For `libssh2` to be installed automatically as a dependency of the Debian package.

### Actual Behavior

Contour won't launch unless I manually install `libssh2-1`.

**Comment by Yaraslaut** [comment]
what if you include `--fix-broken` as `apt` argument, will it resolve this issue?

**Comment by Yaraslaut** [comment]
contour uses libssh2 when user specify remote server instead of shell and we can not make debian to install additional packages from inside package itself, thus i am closing this one
