### ISSUE TITLE
Compiling contour 0.4.3.6442 on Gentoo

### ISSUE THREAD

**Issue by echo2go** [contour-terminal/contour#1490]
### Contour Terminal version

0.4.3.6442

### Installer source

Github: source code cloned

### Operating System

Gentoo

### Architecture

x86-64

### Steps to reproduce

I wanted to update my old Contour package on Gentoo. 
So, here my steps in detail:
```
# whoami 
root
# cd /tmp/
# wget https://github.com/contour-terminal/contour/archive/refs/tags/v0.4.3.6442.zip
# unzip v0.4.3.6442.zip
# cd contour-0.4.3.6442/
# ./scripts/install-deps.sh
./scripts/install-deps.sh: line 45: /tmp/word: Permission denied
./scripts/install-deps.sh: line 47: /tmp/word: Permission denied
./scripts/install-deps.sh: line 49: /tmp/word: Permission denied
Don't know how to fetch from the internet.
# df /tmp
Filesystem     1K-blocks  Used Available Use% Mounted on
tmpfs           12582912 31856  12551056   1% /tmp
#
```
something is preventing access to the internet. And If I use the "autogen.sh" ...
```
# ./autogen.sh
+ '[' -e ../../autogen.sh ']'
++ command -v realpath
+ '[' -x /usr/bin/realpath ']'
+++ dirname ./autogen.sh
++ realpath .
+ ROOTDIR=/tmp/contour-0.4.3.6442
+ CXX=g++
++ basename g++
+ CXX_NAME=g++
+ BUILD_TYPE=Debug
++ uname -m 
++ uname -s 
+ BUILD_DIR=/tmp/contour-0.4.3.6442/target/x86_64-Linux-g++-Debug
+ EXTRA_CMAKE_FLAGS=' -DLIBUNICODE_UCD_BASE_DIR=/tmp/contour-0.4.3.6442/_ucd'
+ test x = x
+ QTVER=6
+ test v6 = v6 
+ EXTRA_CMAKE_FLAGS=' -DLIBUNICODE_UCD_BASE_DIR=/tmp/contour-0.4.3.6442/_ucd -DCONTOUR_QT_VERSION=6'
+ case "$OSTYPE" in 
+ echo 'EXTRA_CMAKE_FLAGS:  -DLIBUNICODE_UCD_BASE_DIR=/tmp/contour-0.4.3.6442/_ucd -DCONTOUR_QT_VERSION=6'
EXTRA_CMAKE_FLAGS:  -DLIBUNICODE_UCD_BASE_DIR=/tmp/contour-0.4.3.6442/_ucd -DCONTOUR_QT_VERSION=6
+ exec cmake /tmp/contour-0.4.3.6442 -DCMAKE_BUILD_TYPE=Debug -DCMAKE_CXX_COMPILER=g++ -DLIBTERMINAL_BUILD_BENCH_HEADLESS=ON -DPEDANTIC_COMPILER=ON -DPEDANTIC_COMPILER_WERROR=ON -DCMAKE_CXX_STANDARD=20 -DCODE_SIGN_CERTIFICATE_ID= -DLIBUNICODE_UCD_BASE_DIR=/tmp/contour-0.4.3.6442/_ucd -DCONTOUR_QT_VERSION=6 -B /tmp/contour-0.4.3.6442/target/x86_64-Linux-g++-Debug -GNinja
-- [Version] version source: /tmp/contour-0.4.3.6442/metainfo.xml
-- [Version] version triple: 0.4.3
-- [Version] version string: 0.4.3
-- The CXX compiler identification is GNU 13.2.1
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/g++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- [ccache] Disabled: Not found.
-- [clang-tidy] Disabled.
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
-- Found Threads: TRUE
-- addr2line: /usr/bin/addr2line
-- No sanitizer enabled.
-- No 3rdparty libraries found at /tmp/contour-0.4.3.6442/_deps/sources
-- Found HarfBuzz: /usr/lib64/libharfbuzz.so
-- Found Freetype: /usr/lib64/libfreetype.so (found version "2.13.2")
CMake Error at cmake/ContourThirdParties.cmake:137 (find_package):
  By not providing "Findlibunicode.cmake" in CMAKE_MODULE_PATH this project
  has asked CMake to find a package configuration file provided by
  "libunicode", but CMake did not find one.

  Could not find a package configuration file provided by "libunicode"
  (requested version 0.4.0) with any of the following names:

    libunicodeConfig.cmake
    libunicode-config.cmake

  Add the installation prefix of "libunicode" to CMAKE_PREFIX_PATH or set
  "libunicode_DIR" to a directory containing one of the above files.  If
  "libunicode" provides a separate development package or SDK, be sure it has
  been installed.
Call Stack (most recent call first):
  CMakeLists.txt:103 (include)


-- Configuring incomplete, errors occurred!
#
```

Could someone help?

### Actual Behavior

no compilation possible. See at "Steps to reproduce" for more infos.

**Comment by Yaraslaut** [comment]
Hm, i think this is due to ` #! /bin/sh ` that we use inside the script. 
you can try to run  `bash ./scripts/install-deps.sh` to get dependencies, also @uspasojevic96 might have some idea

**Comment by echo2go** [comment]
OK. I have found the reason. A file /tmp/world was there. I have removed it and it runs

**Comment by Yaraslaut** [comment]
> OK. I have found the reason. A file /tmp/world was there. I have removed it and it runs

oh, i see. Also, you can use cmake presets to compile instead of autogen.sh script

**Comment by Yaraslaut** [comment]
> OK. I have found the reason. A file /tmp/world was there. I have removed it and it runs

And as a side note, you might have some issues with GCC 13.2. I have them on Arch with GCC 13.2 so you might want to use clang for this, or older version

**Comment by uspasojevic96** [comment]
Use clang to compile on gentoo

**Comment by echo2go** [comment]
ok. Many thanks I will try :)

**Comment by Yaraslaut** [comment]
> at the compiling phase it runs with gcc. Everything is compiled without a failure but the binary build/src/contour/contour isn't run. It starts but no Window will open. I will see how i switch to clang and try to compile with it.
> 
> Clang is installed
> 
> ```
> # which clang
> /usr/lib/llvm/17/bin/clang
> ```
> 
> Is it possible to use clang in the `cmake -S . -B build -G Ninja` command?

You need to specify compiler with `cmake -S . -B build -G Ninja -D CMAKE_CXX_COMPILER=clang++`

**Comment by echo2go** [comment]
Thanks. That work!
But if I test the binary i got the same problem like with gcc. No window is openend

```
$ /tmp/contour-0.4.3.6442/build/src/contour/contour
Warning: QQmlApplicationEngine failed to load component ((null):0, (null))
Warning: qrc:/contour/ui/main.qml:30:5: Type Terminal unavailable (qrc:/contour/ui/main.qml:30, (null))
Warning: qrc:/contour/ui/Terminal.qml:8:1: module "Qt5Compat.GraphicalEffects" is not installed (qrc:/contour/ui/Terminal.qml:8, (null))
Warning: qrc:/contour/ui/Terminal.qml:6:1: module "QtMultimedia" is not installed (qrc:/contour/ui/Terminal.qml:6, (null))
Warning: qrc:/contour/ui/Terminal.qml:8:1: module "Qt5Compat.GraphicalEffects" is not installed (qrc:/contour/ui/Terminal.qml:8, (null))
Warning: qrc:/contour/ui/Terminal.qml:6:1: module "QtMultimedia" is not installed (qrc:/contour/ui/Terminal.qml:6, (null))
```

**Comment by echo2go** [comment]
I took a look at the package from https://packages.debian.org/sid/qml6-module-qt5compat-graphicaleffects and it fits with the gentoo package dev-qt/qtgraphicaleffects.
```
# qlist dev-qt/qtgraphicaleffects       
/usr/lib64/qt5/qml/QtGraphicalEffects/ZoomBlur.qml
/usr/lib64/qt5/qml/QtGraphicalEffects/ThresholdMask.qml
/usr/lib64/qt5/qml/QtGraphicalEffects/RecursiveBlur.qml
/usr/lib64/qt5/qml/QtGraphicalEffects/RectangularGlow.qml
/usr/lib64/qt5/qml/QtGraphicalEffects/RadialGradient.qml
/usr/lib64/qt5/qml/QtGraphicalEffects/RadialBlur.qml
/usr/lib64/qt5/qml/QtGraphicalEffects/OpacityMask.qml
/usr/lib64/qt5/qml/QtGraphicalEffects/MaskedBlur.qml
/usr/lib64/qt5/qml/QtGraphicalEffects/LinearGradient.qml
/usr/lib64/qt5/qml/QtGraphicalEffects/LevelAdjust.qml
/usr/lib64/qt5/qml/QtGraphicalEffects/InnerShadow.qml
/usr/lib64/qt5/qml/QtGraphicalEffects/HueSaturation.qml
/usr/lib64/qt5/qml/QtGraphicalEffects/Glow.qml
/usr/lib64/qt5/qml/QtGraphicalEffects/GaussianBlur.qml
/usr/lib64/qt5/qml/QtGraphicalEffects/GammaAdjust.qml
/usr/lib64/qt5/qml/QtGraphicalEffects/FastBlur.qml
/usr/lib64/qt5/qml/QtGraphicalEffects/DropShadow.qml
/usr/lib64/qt5/qml/QtGraphicalEffects/Displace.qml
/usr/lib64/qt5/qml/QtGraphicalEffects/DirectionalBlur.qml
/usr/lib64/qt5/qml/QtGraphicalEffects/Desaturate.qml
/usr/lib64/qt5/qml/QtGraphicalEffects/ConicalGradient.qml
/usr/lib64/qt5/qml/QtGraphicalEffects/Colorize.qml
/usr/lib64/qt5/qml/QtGraphicalEffects/ColorOverlay.qml
/usr/lib64/qt5/qml/QtGraphicalEffects/BrightnessContrast.qml
/usr/lib64/qt5/qml/QtGraphicalEffects/Blend.qml
/usr/lib64/qt5/qml/QtGraphicalEffects/plugins.qmltypes
/usr/lib64/qt5/qml/QtGraphicalEffects/qmldir
/usr/lib64/qt5/qml/QtGraphicalEffects/libqtgraphicaleffectsplugin.so
/usr/lib64/qt5/qml/QtGraphicalEffects/private/GaussianMaskedBlur.qmlc
/usr/lib64/qt5/qml/QtGraphicalEffects/private/GaussianMaskedBlur.qml
/usr/lib64/qt5/qml/QtGraphicalEffects/private/GaussianInnerShadow.qmlc
/usr/lib64/qt5/qml/QtGraphicalEffects/private/GaussianInnerShadow.qml
/usr/lib64/qt5/qml/QtGraphicalEffects/private/GaussianGlow.qmlc
/usr/lib64/qt5/qml/QtGraphicalEffects/private/GaussianGlow.qml
/usr/lib64/qt5/qml/QtGraphicalEffects/private/GaussianDirectionalBlur.qmlc
/usr/lib64/qt5/qml/QtGraphicalEffects/private/GaussianDirectionalBlur.qml
/usr/lib64/qt5/qml/QtGraphicalEffects/private/FastMaskedBlur.qmlc
/usr/lib64/qt5/qml/QtGraphicalEffects/private/FastMaskedBlur.qml
/usr/lib64/qt5/qml/QtGraphicalEffects/private/FastInnerShadow.qmlc
/usr/lib64/qt5/qml/QtGraphicalEffects/private/FastInnerShadow.qml
/usr/lib64/qt5/qml/QtGraphicalEffects/private/FastGlow.qmlc
/usr/lib64/qt5/qml/QtGraphicalEffects/private/FastGlow.qml
/usr/lib64/qt5/qml/QtGraphicalEffects/private/DropShadowBase.qmlc
/usr/lib64/qt5/qml/QtGraphicalEffects/private/DropShadowBase.qml
/usr/lib64/qt5/qml/QtGraphicalEffects/private/qmldir
/usr/lib64/qt5/qml/QtGraphicalEffects/private/libqtgraphicaleffectsprivate.so
# 
```
So, the question is why he doesn't find/use it?

**Comment by uspasojevic96** [comment]
> I took a look at the package from https://packages.debian.org/sid/qml6-module-qt5compat-graphicaleffects and it fits with the gentoo package dev-qt/qtgraphicaleffects.
> 
> ```
> # qlist dev-qt/qtgraphicaleffects       
> /usr/lib64/qt5/qml/QtGraphicalEffects/ZoomBlur.qml
> /usr/lib64/qt5/qml/QtGraphicalEffects/ThresholdMask.qml
> /usr/lib64/qt5/qml/QtGraphicalEffects/RecursiveBlur.qml
> /usr/lib64/qt5/qml/QtGraphicalEffects/RectangularGlow.qml
> /usr/lib64/qt5/qml/QtGraphicalEffects/RadialGradient.qml
> /usr/lib64/qt5/qml/QtGraphicalEffects/RadialBlur.qml
> /usr/lib64/qt5/qml/QtGraphicalEffects/OpacityMask.qml
> /usr/lib64/qt5/qml/QtGraphicalEffects/MaskedBlur.qml
> /usr/lib64/qt5/qml/QtGraphicalEffects/LinearGradient.qml
> /usr/lib64/qt5/qml/QtGraphicalEffects/LevelAdjust.qml
> /usr/lib64/qt5/qml/QtGraphicalEffects/InnerShadow.qml
> /usr/lib64/qt5/qml/QtGraphicalEffects/HueSaturation.qml
> /usr/lib64/qt5/qml/QtGraphicalEffects/Glow.qml
> /usr/lib64/qt5/qml/QtGraphicalEffects/GaussianBlur.qml
> /usr/lib64/qt5/qml/QtGraphicalEffects/GammaAdjust.qml
> /usr/lib64/qt5/qml/QtGraphicalEffects/FastBlur.qml
> /usr/lib64/qt5/qml/QtGraphicalEffects/DropShadow.qml
> /usr/lib64/qt5/qml/QtGraphicalEffects/Displace.qml
> /usr/lib64/qt5/qml/QtGraphicalEffects/DirectionalBlur.qml
> /usr/lib64/qt5/qml/QtGraphicalEffects/Desaturate.qml
> /usr/lib64/qt5/qml/QtGraphicalEffects/ConicalGradient.qml
> /usr/lib64/qt5/qml/QtGraphicalEffects/Colorize.qml
> /usr/lib64/qt5/qml/QtGraphicalEffects/ColorOverlay.qml
> /usr/lib64/qt5/qml/QtGraphicalEffects/BrightnessContrast.qml
> /usr/lib64/qt5/qml/QtGraphicalEffects/Blend.qml
> /usr/lib64/qt5/qml/QtGraphicalEffects/plugins.qmltypes
> /usr/lib64/qt5/qml/QtGraphicalEffects/qmldir
> /usr/lib64/qt5/qml/QtGraphicalEffects/libqtgraphicaleffectsplugin.so
> /usr/lib64/qt5/qml/QtGraphicalEffects/private/GaussianMaskedBlur.qmlc
> /usr/lib64/qt5/qml/QtGraphicalEffects/private/GaussianMaskedBlur.qml
> /usr/lib64/qt5/qml/QtGraphicalEffects/private/GaussianInnerShadow.qmlc
> /usr/lib64/qt5/qml/QtGraphicalEffects/private/GaussianInnerShadow.qml
> /usr/lib64/qt5/qml/QtGraphicalEffects/private/GaussianGlow.qmlc
> /usr/lib64/qt5/qml/QtGraphicalEffects/private/GaussianGlow.qml
> /usr/lib64/qt5/qml/QtGraphicalEffects/private/GaussianDirectionalBlur.qmlc
> /usr/lib64/qt5/qml/QtGraphicalEffects/private/GaussianDirectionalBlur.qml
> /usr/lib64/qt5/qml/QtGraphicalEffects/private/FastMaskedBlur.qmlc
> /usr/lib64/qt5/qml/QtGraphicalEffects/private/FastMaskedBlur.qml
> /usr/lib64/qt5/qml/QtGraphicalEffects/private/FastInnerShadow.qmlc
> /usr/lib64/qt5/qml/QtGraphicalEffects/private/FastInnerShadow.qml
> /usr/lib64/qt5/qml/QtGraphicalEffects/private/FastGlow.qmlc
> /usr/lib64/qt5/qml/QtGraphicalEffects/private/FastGlow.qml
> /usr/lib64/qt5/qml/QtGraphicalEffects/private/DropShadowBase.qmlc
> /usr/lib64/qt5/qml/QtGraphicalEffects/private/DropShadowBase.qml
> /usr/lib64/qt5/qml/QtGraphicalEffects/private/qmldir
> /usr/lib64/qt5/qml/QtGraphicalEffects/private/libqtgraphicaleffectsprivate.so
> # 
> ```
> 
> So, the question is why he doesn't find/use it?

I will give you exact packages needed tomorrow, i am exclusively using Qt6 on my gentoo

**Comment by Yaraslaut** [comment]
> Many thanks. It works :) Your support is outstanding!
> 
> My steps:
> 
> ```
> # cat /etc/portage/package.use/contour 
> dev-qt/qtmultimedia widgets qml
> dev-qt/qt5compat qml
> # emerge --newuse --update --deep --quiet --ask @world
> [ebuild  N    ] media-libs/assimp-5.2.5-r1 
> [ebuild  N    ] dev-qt/qtquicktimeline-6.6.2 
> [ebuild   R   ] dev-qt/qt5compat-6.6.2 
> [ebuild  N    ] dev-qt/qtquick3d-6.6.2 
> [ebuild   R   ] dev-qt/qtmultimedia-5.15.12 
> [ebuild   R   ] dev-qt/qtmultimedia-6.6.2 
> 
> Would you like to merge these packages? [Yes/No] 
> >>> Verifying ebuild manifests
> >>> Emerging (1 of 6) media-libs/assimp-5.2.5-r1::gentoo
> >>> Installing (1 of 6) media-libs/assimp-5.2.5-r1::gentoo
> >>> Completed (1 of 6) media-libs/assimp-5.2.5-r1::gentoo
> >>> Emerging (2 of 6) dev-qt/qtquicktimeline-6.6.2::gentoo
> >>> Installing (2 of 6) dev-qt/qtquicktimeline-6.6.2::gentoo
> >>> Completed (2 of 6) dev-qt/qtquicktimeline-6.6.2::gentoo
> >>> Emerging (3 of 6) dev-qt/qt5compat-6.6.2::gentoo
> >>> Installing (3 of 6) dev-qt/qt5compat-6.6.2::gentoo
> >>> Completed (3 of 6) dev-qt/qt5compat-6.6.2::gentoo
> >>> Emerging (4 of 6) dev-qt/qtquick3d-6.6.2::gentoo
> >>> Installing (4 of 6) dev-qt/qtquick3d-6.6.2::gentoo
> >>> Completed (4 of 6) dev-qt/qtquick3d-6.6.2::gentoo
> >>> Emerging (5 of 6) dev-qt/qtmultimedia-5.15.12::gentoo
> >>> Installing (5 of 6) dev-qt/qtmultimedia-5.15.12::gentoo
> >>> Completed (5 of 6) dev-qt/qtmultimedia-5.15.12::gentoo
> >>> Emerging (6 of 6) dev-qt/qtmultimedia-6.6.2::gentoo
> >>> Installing (6 of 6) dev-qt/qtmultimedia-6.6.2::gentoo
> >>> Completed (6 of 6) dev-qt/qtmultimedia-6.6.2::gentoo
> #
> ```

Can we close this issue now?

**Comment by echo2go** [comment]
> 
> Can we close this issue now?

Yes :)
