### ISSUE TITLE
please support appimage file, the modern command all in AppImage

### ISSUE THREAD

**Issue by newyorkthink** [contour-terminal/contour#1494]

**Comment by uspasojevic96** [comment]
From what I saw, this already exists, just wasn't released yet, it was implemented in March of this year.

https://github.com/contour-terminal/contour/issues/586

**Comment by Yaraslaut** [comment]
> From what I saw, this already exists, just wasn't released yet, it was implemented in March of this year.
> 
> #586

This is right, next release will have AppImage 
Thus closing this issue
