### ISSUE TITLE
Mac OS Monterey Support

### ISSUE THREAD

**Issue by kobzar** [contour-terminal/contour#1502]
### Contour Terminal version

0.4.3.6442

### Installer source

something else (please specify below)

### Operating System

macOS Monterey 12.3.4

### Architecture

x86-64

### Steps to reproduce

╰─>$ brew info contour
==> contour: 0.4.3.6442
https://github.com/contour-terminal/contour/
Not installed
From: https://github.com/Homebrew/homebrew-cask/blob/HEAD/Casks/c/contour.rb
==> Name
contour
==> Description
Terminal emulator
==> Artifacts
contour.app (App)
contour.app/Contents/MacOS/contour (Binary)
contour.app/Contents/Resources/shell-integration/shell-integration.zsh -> /usr/local/share/zsh/site-functions/_contour (Binary)
contour.app/Contents/Resources/terminfo/63/contour -> ~/.terminfo/63/contour (Binary)
==> Analytics
install: 99 (30 days), 298 (90 days), 949 (365 days)

contorur

“contour.app” can’t be opened because Apple cannot check it for malicious software.

You can’t use this version of the application “contour.app” with this version of macOS.
You have macOS 12.7.4. The application requires macOS 13.0 or later.

### Actual Behavior

contorur

“contour.app” can’t be opened because Apple cannot check it for malicious software.

You can’t use this version of the application “contour.app” with this version of macOS.
You have macOS 12.7.4. The application requires macOS 13.0 or later.

**Comment by Yaraslaut** [comment]
Hi @kobzar, see https://github.com/contour-terminal/contour/issues/1421 you can get some info on how to run contour on macos at the moment, and we hope that in future releases everything will be smooth

**Comment by kobzar** [comment]
> Hi @kobzar, see #1421 you can get some info on how to run contour on macos at the moment, and we hope that in future releases everything will be smooth

This is not security problem. I was allow it to run but as you can see the last message is 

You have macOS 12.7.4. The application requires macOS 13.0 or later.

**Comment by Yaraslaut** [comment]
> > Hi @kobzar, see #1421 you can get some info on how to run contour on macos at the moment, and we hope that in future releases everything will be smooth
> 
> This is not security problem. I was allow it to run but as you can see the last message is
> 
> You have macOS 12.7.4. The application requires macOS 13.0 or later.

I see, you can try building from source to see if we support macOS 12.7.4 at the moment, I doubt that we are going to include support for older versions of  os since it will delay us from using newest c++ standard

**Comment by Yaraslaut** [comment]
Do you have any updates @kobzar ?

**Comment by kobzar** [comment]
> Do you have any updates @kobzar ?

Witch updates you are wait from me? I am user not a contour developer.

**Comment by Yaraslaut** [comment]
> > Do you have any updates @kobzar ?
> 
> Witch updates you are wait from me? I am user not a contour developer.

We are not packaging contour for macOS, so if brew tells you that your os is not supported, you have two options
1) try to install from source and see if everything is alright and use contour
2) ask package maintainers if they can lower required macOS version for contour and then install it through brew
