### ISSUE TITLE
Flatpak version out of date

### ISSUE THREAD

**Issue by puresick** [contour-terminal/contour#1509]
The flatpak package on flathub is outdated. Currently it is on version 0.3.12.

**Comment by Yaraslaut** [comment]
Hi, @puresick  we will try to update Flatpak at some point, but at the moment please use other means to install contour.

**Comment by cebas** [comment]
Hi, same issue here. As flatpak is old, I tried to install contour-0.4.3.6442-ubuntu22.04-amd64.deb but found dependency problems on Ubuntu 24.04. (requires libyaml-cpp0.7, but 0.8 is installed and seems that contour don't like it...)
When are you planning the release of a 24.04 deb?

**Comment by christianparpart** [comment]
I've finally taken the time to look at the Flathub Contour PR (https://github.com/flathub/org.contourterminal.Contour/pull/16) again. And despite now being latest stable (0.4.3) plus some minor tweaks, the reason why it failed back in time, now magically went away (flathub builder host related).

Give it a couple of hours until Flathub itself picks it up in the app store.

NB: It's quite some time when we've last released 0.4.3 (February) and we have a couple of good changes in the next (0.4.4) ahead. I think it's time to release this one soonish, to make them publically easier available.

If there's anything not working, please feel free to contact us, or directly join our Discord. :)
