### ISSUE TITLE
Neovim causes contour to resize.

### ISSUE THREAD

**Issue by kierun** [contour-terminal/contour#1516]
### Contour Terminal version

0.4.3

### Installer source

something else (please specify below)

### Operating System

Fedora 39

### Architecture

x86-64

### Other Software

NVIM v0.11.0-dev-194+g6c7677e5d

### Steps to reproduce

1. Open a contour terminal.
2. Run `/usr/bin/tput cols`, get 86 — let's call that `x`.
3. Run `nvim test.md`, exit.
4. Run `/usr/bin/tput cols`, get 138 — It should be more than `x` above.

### Expected Behavior

The terminal must not resize.

### Actual Behavior

The terminal is resized.

### Additional notes

Here is a GIF of the behaviour:

![nvim-contour-bug](https://github.com/contour-terminal/contour/assets/3079575/4b13fd74-47ae-428d-b50f-3f2d156b49b2)

In addition, this behaviour does not appear under tmux.

**Comment by Yaraslaut** [comment]
Hi @kierun, can you please also provide output of `contour debug "gui.display,vt.trace.sequence"` during this bug? It would help us a lot, on my system i can not reproduce this bug, so it will require some time to figure out exact reason without debug output.

**Comment by kierun** [comment]
And here is the same thing using tmux: 
[contour=tumx.log](https://github.com/user-attachments/files/15739329/contour.tumx.log)

**Comment by uspasojevic96** [comment]
Can you try clean neovim without plugins?

**Comment by kierun** [comment]
> Can you try clean neovim without plugins?

I tried with `nvim --clean` and … Well, how about that! The issue disappears.

WOT?

**Comment by uspasojevic96** [comment]
Start investigating your plugins and let us know which one is it xD

**Comment by kierun** [comment]
Here is the culprit: `require("noice").setup({})`… Actually, it's not. It's `"MunifTanjim/nui.nvim"` which is a dependency of [noice](https://github.com/folke/noice.nvim). 

[Linked bug](https://github.com/MunifTanjim/nui.nvim/issues/370)

**Comment by kierun** [comment]
> Start investigating your plugins and let us know which one is it xD

I was on it. The rabbit hole was a little deeper than I thought! :scream:

**Comment by uspasojevic96** [comment]
Relevant bug https://github.com/folke/noice.nvim/issues/688

**Comment by uspasojevic96** [comment]
I'll close this issue, please reopen it if there is some evidence that bug is on contour side
