### ISSUE TITLE
Add support for blurred background on Wayland desktops (KDE, GNOME)

### ISSUE THREAD

**Issue by christianparpart** [contour-terminal/contour#1526]
Currently, when running contour in KDE Plasma for Wayland, I'm getting the following error message:

```
[error] Could not set X11 property info for "_KDE_NET_WM_BLUR_BEHIND_REGION" to 0.
[error] Could not set X11 property info for "_MUTTER_HINTS" to "blur-provider=sigma:60,brightness:0.9".
```

This is obviously because it's not an X11 desktop, but Wayland instead. We need to figure out how to do blurred (transparent) background on these desktops.

**Comment by Yaraslaut** [comment]
Dup of https://github.com/contour-terminal/contour/issues/1265
So i will close it
