### ISSUE TITLE
Support for Indic scripts

### ISSUE THREAD

**Issue by shreevatsa** [contour-terminal/contour#1533]
## Abstract

Support for non-Latin scripts, such as Indic scripts like Devanagari and Kannada, seems to be missing in Contour, at least on macOS. I just [tried](https://shreevatsa.net/post/terminal-indic/) a bunch of terminals on macOS, and Contour is the worst of them (zero font support), which is surprising given the mention of Unicode Grapheme cluster support etc. I'm not sure whether I've done anything incorrectly (whether this is a bug report or feature request). This is what it looks like:

![image](https://github.com/contour-terminal/contour/assets/767530/b15dd899-c4aa-4dec-98dd-79b01e2fb990)

where `sample.txt` is:

```
ತನ್ನ ಒಂದು ಸತ್ಯಸಂಕಲ್ಪದಂತೆ ಸೃಷ್ಟಿಯಲ್ಲಿ ವ್ಯವಸ್ಥೆಯಿಲ್ಲದೆ ತನ್ನ
```

## Motivation

Output from programs like `diff`, or for that matter `ls`, should work even when file contents or filenames contain Indic-script characters.

## Specification

There is no specification; I believe no terminal renders these scripts correctly (though mlterm comes closest). Still, I'd hope that Contour could be at least as good as other terminals.

**Comment by Yaraslaut** [comment]
hi @shreevatsa
Here is what i see for your text on my system 
![image](https://github.com/contour-terminal/contour/assets/44506630/22d24206-9b31-41ce-8c0f-03059aa7130b)

you need to setup fonts accordingly in contour config file. And `contour debug font.textshaping` might give you some additional info

**Comment by christianparpart** [comment]
I think you might have `strict_spacing` set to `true`. Try setting it to `false` :)

**Comment by shreevatsa** [comment]
Thank you @Yaraslaut and @christianparpart. It is heartening to know that some amount of support exists in principle.

For what it's worth, I was not able to get it to work on macOS:

```
➜  ~ contour debug font.textshaping
Warning: Could not find the Qt platform plugin "cocoa" in "" ((null):0, (null))
Fatal: This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.
 ((null):0, (null))
[1]    73822 abort      contour debug font.textshaping
```

and

```
➜  ~ contour font-locator
[error] The configured text shaping engine CoreText does not yet support font feature settings. Ignoring.
Matching fonts using  : CoreText
Font description      : (family=monospace weight=Regular slant=Roman spacing=Proportional, strict_spacing=no)
Number of fonts found : 1
  path /System/Library/Fonts/Menlo.ttc
```

**Comment by christianparpart** [comment]
@shreevatsa I just checked. I'm having the same output as you on MacOS, but it works flawlessly on non-MacOS (same software version).

So the only difference is how we discover fonts, on MacOS. This is something I can investigate tonight (I'm out with family during the day). I keep you posted.

I'd like to note one very important thing though (having quickly scanned through your blog article), which is: Unicode is *not* specified for terminals. Not at all. This is all undefined implementation dependant behaviour. We (as in some terminal developers) try indeed to get to the current century, when it comes to Unicode. Every TE has its own priorities there. For us for example, we focus on complex grapheme cluster support, especially related to emoji, but also on ligature support. Which is both very well supported in Contour.
Languages like Hebrew, RTL, etc.

I don't like MacOS falling behind in font fallback (this is the issue here). I'll look into it later.

**Comment by christianparpart** [comment]
@shreevatsa the given PR above actually implements proper font fallback on MacOS. Thanks for reporting this. :)

**Comment by shreevatsa** [comment]
Thank you so much! 

To clarify:

- Yes I understand terminal behaviour is not specified with Unicode, in particular (in this case) for complex scripts and trying to force them into the grid-of-cells assumption of terminals. I appreciate that Contour here intends to support Unicode better than other terminals! In fact, while searching around I found some very sensible comments by you on another repo (https://github.com/alacritty/alacritty/issues/3975) which is what emboldened me to report this here. :-)
- Sorry about "zero font support" — what I meant was that we speakers/readers of languages with complex scripts have, over the years, come to recognize several "levels" of support for our scripts, in various environments' text stacks: (0) no font loaded at all, glyphs are shown as question marks/boxes/tofu (LastResort/.notdef), (1) some font is used, but the glyphs are just laid out next to each other with no CTL reordering, (2) text rendered mostly correctly and readably, with some corner cases that can be read with guesswork, (3) text rendered properly. I imagine readers of Arabic recognize further levels with RTL support, and with terminals I now realize there are further complications with rendering to the grid.
- Thanks for clarifying that Unicode Grapheme cluster support refers to grapheme cluster segmentation — I must say we are all thankful for emoji, the "trojan horse" of Unicode support (in a good way: many programs that would otherwise not care about Unicode end up implementing varying levels of support for the sake of emojis, which ends up benefiting all the world's languages).

Back to this issue: building from source after #1536 (following the steps from this comment: https://github.com/contour-terminal/contour/issues/1510#issuecomment-2183374781), I can confirm that after the recent PR, there is some positive change as font fallback seems to be working:

<img width="384" alt="image" src="https://github.com/contour-terminal/contour/assets/767530/cdceef0f-da2f-4140-9e77-76a4d78138f7">

(The rendering isn't great, with characters overlapping etc, but most other terminals have similar issues, and I understand that implementing something better, when there isn't even any specification yet, may not be within scope. In the meantime on a personal note, I was able to get my work done using eshell, which is not a terminal emulator (thankfully), and doesn't try to force text to a grid.)

**Comment by shreevatsa** [comment]
Just for completeness, some concrete numbers for an example (from another repo https://github.com/wez/wezterm/issues/1333#issuecomment-1006328144): in the example there, the text "বাংলা ভাষা" has, at a font size where the space character (and thus one "cell") is 8 pixels wide:

- `বাং` 7+4+6=17 pixels (=17/8=2.125 cells)
- `লা` 10+4=14 pixels (=14/8=1.75 cells)
- ` ` 8 pixels (=1 cell)
- `ভা` 10+4=14 pixels (=14/8=1.75 cells)
- `ষা` 8+4=12 pixels (=12/8=1.5 cells)

So ideally this would be 65 pixels = 8.125 cells wide, but if that's not possible, what I as a reader would prefer would be for cell-alignment to happen at word boundaries (so `বাংলা` = 17 + 14 pixels = 3.875 cells would be rounded up to 4 cells, then a space, then `ভাষা` = 26 pixels = 3.25 cells would be either squeezed to 3 or rounded up to 4 cells).

I think Contour tries to render the whole thing 5 or 6 cells wide, as there are 5 graphemes and 6 glyphs (copy-pasted input was `echo বাংলা ভাষা | wc` — note there's a space before the `|`):

<img width="616" alt="image" src="https://github.com/contour-terminal/contour/assets/767530/eb0fdf13-c776-4bb1-a546-fdfc006fe1d7">

while Terminal and iTerm2 use 10 cells, rounding up each grapheme or maybe even each glyph (`বাং` 2.125 -> 3 cells, `লা` 1.75 -> 2 cells, ` ` 1 cell, `ভা` 1.75 -> 2 cells, `ষা` 1.5 -> 2 cells):

<img width="404" alt="image" src="https://github.com/contour-terminal/contour/assets/767530/4d6736d1-9aac-4bc5-a25f-0d179362d550">

<img width="404" alt="image" src="https://github.com/contour-terminal/contour/assets/767530/7901de18-1487-4d51-b294-4b9722ae9cde">

(renders better or more readable, but cursor movement goes haywire).

I understand there is no specification here and it's a research problem how best to render these.
