### ISSUE TITLE
Key mapping Ctrl+Shift+Tab not working.

### ISSUE THREAD

**Issue by csy19960309** [contour-terminal/contour#1578]
### Contour Terminal version

0.4.3

### Installer source

something else (please specify below)

### Operating System

Archlinux with kernel 6.9.10-zen1-1-zen

### Architecture

x86-64

### Other Software

tmux 3.4-9, wayland 1.23.0-1

### Steps to reproduce

Add _{ mods: [Control, Shift], key: Tab,           action: SendChars, chars: "test" }_ to config.

### Expected Behavior

It prints "test" to stdout.

### Actual Behavior

An actual _tab_ is printed. I mean, it's just like that I press the key TAB.

**Comment by Yaraslaut** [comment]
Hi @csy19960309, thanks for the bug report
