### ISSUE TITLE
Apple Silicon Only ?

### ISSUE THREAD

**Issue by AmnaSN** [contour-terminal/contour#1597]
The newest release is Apple Silicon native , but does that mean Intel compatibility is dropped?

**Comment by Yaraslaut** [comment]
Hi, GitHub changed default runners for macOS from x86 to arm, this is the reason why macos package is for arm now. So as long as compiler new enough to support c++20, contour can be compiled on macos, but we do not provide package for it

**Comment by Yaraslaut** [comment]
Hi @AmnaSN is there anything i can help you with at the moment? if not i will close the issue

**Comment by AmnaSN** [comment]
Thanks for your response. As a suggestion, it would be great to mention this information on your page somewhere(if you haven't already). 
You may close the issue.

**Comment by christianparpart** [comment]
@AmnaSN do you still have a non-ARM macOS?
Can you build contour yourself? Only do it if you'd have most of the toolchain available already. I'd not try to force any user to install a developer toolchain. I'd like to know though ;)

**Comment by yashisrani** [comment]
@AmnaSN  I guess , Intel Macbook's compatibility is not dropped ...

**Comment by whisperity** [comment]
@christianparpart @Yaraslaut It's a real big blunder if GitHub made this change without offering the option to be able to cross-compile for both architectures. Most of the core stuff on Mac, when inspected, become dual arch builds.
