### ISSUE TITLE
Exit `ViNormalMode` after yanking and map `Esc` key to exit normal mode

### ISSUE THREAD

**Issue by budimanjojo** [contour-terminal/contour#1604]
Currently `ViNormalMode` feels a little awkward to me. Usually we want to exit normal mode after yanking the selection (at least this is the behavior in `tmux` and `wezterm`).
And another one is (I don't know if separate issue is needed) map `Esc` key to exit vi mode. I know it's not the default behavior in `vi` but in `vi` we usually starts with Normal mode but we start in Insert mode here. And we don't enter normal mode with `Esc` key by default too like in `vi` here. `Esc` feels more natural to me and it's also the default behavior in `tmux` and `wezterm`.

**Comment by Yaraslaut** [comment]
Hi @budimanjojo, thanks for the feedback 
> Usually we want to exit normal mode after yanking the selection (at least this is the behavior in tmux and wezterm).`

I am not sure that this is a good default behaviour, we can customize it,  we already have similar customization for search mode
```
# Whether or not to switch from search mode into insert on exit
search_mode_switch: false
```

> map Esc key to exit vi mode

This is something that is we can add to increase qol of users

**Comment by budimanjojo** [comment]
Yeah I'm good with something similar to `search_mode_switch` option too. Thank you!

**Comment by Yaraslaut** [comment]
Everything is done in two separate PR, so i am closing this
