### ISSUE TITLE
create shell integration scripts

### ISSUE THREAD

**Issue by christianparpart** [contour-terminal/contour#163]
For at least bash and zsh

For preexec:
* Add vertical line marker
* Disable text reflow

For preexec:
* Enable text reflow

On init, maybe install functions to:
* display images (like icat)
* change profile to ...
* `vtsend` to send files to host terminal, landing in host's (configurable) Downloads folder

### Checklist

- [x] zsh
- [x] fish
- [x] bash

**Comment by christianparpart** [comment]
Let's do bash at a later time, when we also have users that use bash. :)

**Comment by whisperity** [comment]
Reopen the issue and put them into a milestone bucket called "future features" or something.

**Comment by christianparpart** [comment]
i.e. basically buying some more time without forgetting that one wanted to do that :)

**Comment by christianparpart** [comment]
@data-man I think in on of your screenshots I saw you using fish shell, is that right? Would you mind having a look at how easy it would be to add contour shell integration for fish?

**Comment by data-man** [comment]
> I saw you using fish shell, is that right?

Exactly!

> Would you mind having a look at how easy it would be to add contour shell integration for fish?

Will do!

**Comment by data-man** [comment]
Can we use some template engine for this?
E.g. https://github.com/pantor/inja or https://github.com/kainjow/Mustache (both are header-only).

**Comment by WSLUser** [comment]
Iterm2 has some shell integration scripts but not sure if those are exactly the same as you're looking at.

**Comment by Yaraslaut** [comment]
I suppose fish is done by this PR https://github.com/contour-terminal/contour/pull/1001 ?

**Comment by christianparpart** [comment]
yes, it is. :)

**Comment by christianparpart** [comment]
the question is if bash is relevant at all as of 2023. Most people seem to be using ZSH anyways, and Fish is the new rising star (in my opinion), people are more likely to drive away from bash. We might just close this ticket alltogether and wait for someone actually wanting bash completion. Then it can still be added. No need to create artificial maintenance burdens with no real users behind :)

**Comment by whisperity** [comment]
@christianparpart **Completion** or **integration**? Two different things. Bash integration would still be useful for cases where people just start a small job (e.g. in docker or a remote server) without a full developer environment but would still like to use at least the small features like the "jump to prompt". Really important feature even in maintenance activities, not just development.

(Personally, I'm using ZSH and will continue using ZSH, fish is too arcane for me, so I'd prefer if ZSH were kept in the front of the picture.)

**Comment by christianparpart** [comment]
@whisperity we can of course to the integration. I just forgot how to do it, I can't believe I did. thanks for raising the need. :-)
