### ISSUE TITLE
Contour macos dmg don't have release for intel macbooks, it can be installed for m's apple macbooks only

### ISSUE THREAD

**Issue by vkravets** [contour-terminal/contour#1636]
### Contour Terminal version

0.5.1.7247 

### Installer source

GitHub: release page

### Operating System

macOS Sanoma 14.6.1

### Architecture

x86-64

### Steps to reproduce

Download macOs DMG and try to install on Intel's macbook (before 2021)

### Expected Behavior

Contours successfully run on this macbook

### Actual Behavior

CPU architecture doesn't support for this application

**Comment by vkravets** [comment]
It seems GitHub Actions for the macos-14  runner using arm64 host. https://github.com/actions/runner-images?tab=readme-ov-file#available-images 
Intel host avlaible only for GitHub Teams or GitHub Enterprise.

can we use macos-13 for building intel version? is contour code hard linking to macos 14 only?

**Comment by Yaraslaut** [comment]
I am not sure that macos-13 provides compilers with c++20 support, but I think that we can use `macos-15-large` runners as an open source project (usage time is limited though, so better to use it only for release)

**Comment by Yaraslaut** [comment]
> > I think that we can use `macos-15-large` runners as an open source project (usage time is limited though, so better to use it only for release)
> 
> @Yaraslaut Why would we need a `-large` runner so much? Is that because of the Qt self-compilation? Wasn't that only for older Linux builds?

this is x86 runners, macos-15 is arm
```
macOS 15 beta 	macos-15-large 	[macOS-15](https://github.com/actions/runner-images/blob/main/images/macos/macos-15-Readme.md) 	Endpoint Badge
macOS 15 Arm64 beta 	macos-15 or macos-15-xlarge 	[macOS-15-arm64](https://github.com/actions/runner-images/blob/main/images/macos/macos-15-arm64-Readme.md) 	Endpoint Badge
```
