### ISSUE TITLE
Contour as library

### ISSUE THREAD

**Issue by ShalokShalom** [contour-terminal/contour#1669]
Hi there!

I consider to implement a terminal in [the Godot game engine](https://godotengine.org/)

The idea is to replace the central part here, the scripting editor, to use Helix and other tools.

![Bildschirmfoto_20241214_145537](https://github.com/user-attachments/assets/a4a4619e-5fa2-4a95-885f-0cf5ce2d11c2)

Is your terminal capable to be implemented? The engine is written in C++

**Comment by Yaraslaut** [comment]
Contour is separated into few parts, terminal handling is happening in `vtbackend` part (https://github.com/contour-terminal/contour/tree/master/src/vtbackend) and gui part is here `contour` (https://github.com/contour-terminal/contour/tree/master/src/contour)
