### ISSUE TITLE
Precondition failed in `TerminalDisplay.cpp`

### ISSUE THREAD

**Issue by T-727** [contour-terminal/contour#1684]
### Contour Terminal version

0.6.0.7452

### Installer source

GitHub: release page

### Operating System

Windows 10.0.26100

### Architecture

x86-64

### Steps to reproduce

open from the command line, nothing else

### Actual Behavior

The following message appears and the process aborts:
```shell
[D:\a\contour\contour\src\contour\display\TerminalDisplay.cpp:571] Precondition failed. width() > 1.0 && height
() > 1.0
```

### Additional notes

no custom config file was used

**Comment by christianparpart** [comment]
Hey @T-727. I think i know why this is happening to you and thus, I *should* have a fix for it.

Sorry for the inconveniences. I hope this will fix it for you.

**Comment by christianparpart** [comment]
@T-727 we should be releasing within the next 24 hours, so you could grab a new 0.6.1 release build quite soon. Please report back if it did indeed helps you starting up Contour on Windows 10 again. :)

**Comment by T-727** [comment]
Hi @christianparpart, works wonderfully!
Thank you and the team for the speedy service. 2 issues up, 2 issues down in less than a day is amazing 😄
