### ISSUE TITLE
CI: Add Arch Linux builds to CI testing and also upload to AUR on release.

### ISSUE THREAD

**Issue by christianparpart** [contour-terminal/contour#171]
See https://github.com/marketplace/actions/publish-aur-package

**Comment by ResuBaka** [comment]
For the action of publishing an PKGBUILD file to the aur you need in the best case an binary that is build with an arch linux system. For that I have create a PR (https://github.com/christianparpart/contour/pull/181) so we have build artifacts for arch linux systems.

**Comment by nations-Xiong** [comment]
How to install it on archlinux?
I downloaded the source and executed the `autogen.sh`. Biuld files bave been written to `./build`. 
What should I do next to install it on my arch?
Thank you!

**Comment by christianparpart** [comment]
> How to install it on archlinux?
> I downloaded the source and executed the `autogen.sh`. Biuld files bave been written to `./build`.
> What should I do next to install it on my arch?
> Thank you!

Hey @nations-Xiong, while this ticket here is actually meant for improving the ArchLinux GitHub CI action, I can at least try to respond here :)

You can have a look at how the GitHub workflow is handling that in:
    https://github.com/christianparpart/contour/tree/master/.github/archlinux

But the long story short should be something like:
```sh
pacman -Sy --noconfirm archlinux-keyring
pacman -Su --noconfirm gcc ninja cmake extra-cmake-modules qt5-base fontconfig harfbuzz git base-devel

git clone URL contour
cd contour
mkdir build
cmake \
  -S . -B build/ \
  -GNinja \
  -DCMAKE_INSTALL_PREFIX=/usr/local \
  -DCMAKE_BUILD_TYPE=RelWithDebInfo -DCMAKE_CXX_COMPILER=g++ \
  -DYAML_BUILD_SHARED_LIBS=OFF -DYAML_CPP_BUILD_CONTRIB=OFF \
  -DYAML_CPP_BUILD_TESTS=OFF -DYAML_CPP_BUILD_TOOLS=OFF \
  -DYAML_CPP_INSTALL=OFF

cmake --build build/
```

Then you should have a new binary in ./build/src/contour/contour that you can execute, such as:
```sh
./build/src/contour/contour help
```

to see the help, and to actually execute it, just ommit the `help` parameter
```sh
./build/src/contour/contour help
```

On the other hand, you should better install the whole package via:

```sh
cmake --install build/
```

Keep in mind, the above example would install contour into `/usr/local`, you can change that by replacing it to whatever you want as prefix, for example: `$HOME/usr/opt/contour` (that's what I do for local user installs).

**Comment by nations-Xiong** [comment]
Thank you so much! @christianparpart

**Comment by vnepogodin** [comment]
I've added contour in to the aur

https://aur.archlinux.org/packages/contour-git/

**Comment by uspasojevic96** [comment]
> I've added contour in to the aur
> 
> https://aur.archlinux.org/packages/contour-git/

Check AUR comments, `check()` part of PKGBUILD is failing. Can you fix it and submit PR since at the moment I don't have Arch Linux installed (even on VM)?

**Comment by vnepogodin** [comment]
Already fixed :smiley:

**Comment by vnepogodin** [comment]
> > I've added contour in to the aur
> > https://aur.archlinux.org/packages/contour-git/
> 
> Check AUR comments, `check()` part of PKGBUILD is failing. Can you fix it and submit PR (for GHA) since at the moment I don't have Arch Linux installed (even on VM)?

What kind of PR?

**Comment by uspasojevic96** [comment]
> > > I've added contour in to the aur
> > > https://aur.archlinux.org/packages/contour-git/
> > 
> > 
> > Check AUR comments, `check()` part of PKGBUILD is failing. Can you fix it and submit PR (for GHA) since at the moment I don't have Arch Linux installed (even on VM)?
> 
> What kind of PR?

For https://github.com/christianparpart/contour/tree/master/.github/archlinux so that we can improve scripts for CI

**Comment by vnepogodin** [comment]
ok. I will

**Comment by christianparpart** [comment]
Bei. Many thanks for the AUR work. I really appreciate that.

Can you please fix the upstream URL? It was just yesterday when we moved the set of repos into their own GitHub organization.

**Comment by vnepogodin** [comment]
yep I can

**Comment by vnepogodin** [comment]
https://github.com/contour-terminal/contour/pull/286#issue-682906202

**Comment by uspasojevic96** [comment]
@christianparpart I think this can be closed now

**Comment by christianparpart** [comment]
Thanks @vnepogodin for your work! :)
