### ISSUE TITLE
Action: SaveScreenshot / CopyScreenshot

### ISSUE THREAD

**Issue by christianparpart** [contour-terminal/contour#210]
since the logic is already there (for debugging purposes initially), we can provide an input mapping to let the user create screenshots of the current terminal screen on the fly.

- SaveScreenshot: takes a screenshot and saves it into a file with a given pattern
- CopyScreenshot: takes a screenshot and puts it into the system clipboard, see https://doc.qt.io/qt-5/qclipboard.html#setImage

**Comment by Yaraslaut** [comment]
Connected to https://github.com/contour-terminal/contour/issues/210
