### ISSUE TITLE
Configurable font fallback

### ISSUE THREAD

**Issue by christianparpart** [contour-terminal/contour#225]
It is said that `fontconfig` should be used for font fallback, but it seems that terminal emulators are not always using this recommended API for font fallback.

* kitty uses fontconfig only for retrieving the set of all fonts, then filters and prioritizes manually)
* wezterm seems to only support font fallback based on what the user has provided in the configs.
* What is konsole, gnome-terminal and alacritty doing?
* Not all fontconfig system configurations seem to be reliable (if any at all).

On top of using fontconfig for getting the list of fallback fonts maybe we could provide a manually provided list of font fallbacks too.

* Evaluate the usefulness of selecting font files based on codepoints / codepoint sequences (such as kitty does provide)
* Evaluate embedding Powerline glyphs (should be configurable, too)
* Evaluate embedding box drawing glyphs (should be configurable, too)

**Comment by Yaraslaut** [comment]
@eproxus  Thanks for the interest
I will add this into milestone for 2024 since I wanted to disable font fallback and if memory is correct  @Utkarsh-khambra as well

**Comment by Yaraslaut** [comment]
> > I will add this into milestone for 2023 since I wanted to disable font fallback
> 
> You mean rely on fontconfig only? Will this work on macOS?

Yes, only fontconfig, this will be naturally configurable, so if this does not work for macOS this option will not be available then. And for sure we will add other options for fallback. something like :
`auto` <- current behavior  
`priority` <- list of fonts that we need to check first and if not found proceed with the rest 
`list` <- user specified list of fonts that are used for fallback and not others
`none` <- do not try to find another font

**Comment by Yaraslaut** [comment]
Closing this one, now configuration allows some flexibility for font fallback and builtint fonts will be implemented in https://github.com/contour-terminal/contour/issues/170
