### ISSUE TITLE
Add "CSI u" extended keyboard mapping

### ISSUE THREAD

**Issue by christianparpart** [contour-terminal/contour#232]
See http://www.leonerd.org.uk/hacks/fixterms/

I wonder why the spec didn't make it runtime configurable, such as SM/RM to explicitly request that.

Should be configurable via contour config in `profiles.*.extended_keybboard_mapping: BOOL` or so.

https://sw.kovidgoyal.net/kitty/keyboard-protocol/ seems to be an updated one.

**Comment by WSLUser** [comment]
Iterm2 has this option available as a setting you can toggle on and off. Maybe seeing their implementation may help.

**Comment by christianparpart** [comment]
Correcting myself against `CSI u` and towards modifyOtherKeys from xterm https://invisible-island.net/xterm/manpage/xterm.html#VT100-Widget-Resources:modifyOtherKeys

**Comment by christianparpart** [comment]
`CSI u` is implemented on `master` branch.
