### ISSUE TITLE
strongly type the primitives

### ISSUE THREAD

**Issue by christianparpart** [contour-terminal/contour#258]
This is going to be the tracker ticket for the attempt to strongly type the primitive data types in order to improve code quality.

A non-exhaustive list of candidates could be:

- [x] absolute page line/column numbers
- [x] absolute history line/column numbers
- [x] relative line numbers
- [x] column & line count
- [ ] CSI/OSC parameter values 
- [ ] offsets in general
- [ ] booleans can be binary enum classes.
- [ ] ...?

There progress as well as the learnings must be documented (not just for a blog post).

Each underlying algebraic operation should be safe.

**Comment by Yaraslaut** [comment]
Close this one, we use https://github.com/contour-terminal/boxed-cpp
