### ISSUE TITLE
UI Enhancement: Use Uno

### ISSUE THREAD

**Issue by WSLUser** [contour-terminal/contour#261]
## Abstract

Uno allows multiple UI frameworks to be utilized in a cross-platform way. If you want a specific UI look consistently across different platforms, this platform allows it. For example, with the use of Uno, you can run WinUI on Linux and Mac with minor UI differences. See https://github.com/unoplatform/uno

## Motivation

This will allow UI updates to be added more consistently without the need to have various methods unique to each platform supported and could allow other platforms (such as Web) to be more easily supported as well.

**Comment by christianparpart** [comment]
Hey. Uni seems like an interesting project. But that is C#-only whereas Contour is written in C++. But sure that can integrate somehow. (Though, the actual workhorse part is a platform independent library)

The contour frontend is using Qt, which is also platform independent, like Uno.

Before that i used GLFW but i had series of issues with its input API, plus, it has no widgets. Qt fixed ask if that. :)

**Comment by WSLUser** [comment]
Yeah, it's doable, there's some C# within Windows Terminal too. QT is a good framework, maybe there's a way to use it with Uno but my UI of choice is actually WinUI. I've seen their posts showing off WinUI on Linux and Mac and it looked great, if different from the rest of the ecosystem.

**Comment by christianparpart** [comment]
> Yeah, it's doable, there's some C# within Windows Terminal too. QT is a good framework, maybe there's a way to use it with Uno but my UI of choice is actually WinUI. I've seen their posts showing off WinUI on Linux and Mac and it looked great, if different from the rest of the ecosystem.

I am currently focusing on stabelizing and making sure a good UX is covered with the next release (that should happen very soon, but I may delay for better quality). I do want to support Windows, though it is like a small step-brother right now. working on it - given enough time and patience.

The one last note, while I didn't plan to move away from Qt, one thing I always made very sure while developing on Contour: keeping the Qt dependencies as minimal as possible. So Qt is exclusively used for window creation and input handling. This idea design should make it ideally possible to provide other frontend toolkits, too, without dropping or duplicating frontend features. (Well, command palette would need to know what framework it's talking to, unless I plan to do that inside of OpenGL natively...).

**Comment by christianparpart** [comment]
> What if use Immediate Mode GUI libraries? E.g. Dear ImGui as the most popular.

I actually considered ImGui multiple times but that fixes only half of the issue. I still need a platform independent API to talk to für window creation and input handling.
