### ISSUE TITLE
New actions for scrollback clearing

### ISSUE THREAD

**Issue by data-man** [contour-terminal/contour#263]
## Motivation
`Konsole` has `Clear Scrollback` and `Clear Scrollback and Reset` actions in `Keyboard Shortcuts`.
This is useful for clearing during programs execution.

## Specification
In `Konsole` I'm using `Ctrl-Q` hotkey for `Clear Scrollback and Reset` action.

**Comment by WSLUser** [comment]
I think this is more of a shell's responsibility butI think Iterm2 also has something like this as well.

**Comment by data-man** [comment]
> I think this is more of a shell's responsibility 

No.
If I'm not mistaken, shells don't receive keystrokes while other programs are running.

**Comment by christianparpart** [comment]
> `Konsole` has `Clear Scrollback` and `Clear Scrollback and Reset` actions in `Keyboard Shortcuts`.

Oh, I think we can do that already:

```yaml
input_mapping:
  # "\e[3J" | ED - Erase in Display
  #       Parameter 3 for clearing the scrollback
  #       Parameter 1 for clearing from cursor position downwards
  # "\e[H"  | CUP - Cursor Position
  # "\ec"   | RIS - Reset to Initial State
  - { mods: [Control], key: Q, action: WriteScreen, chars: "\e[H\e[J\e[3J\ec" }
  - { mods: [Control], key: Q, action: SendChars, chars: "\n" }
  # ...
```
This <kbd>Ctrl</kbd>+<kbd>Q</kbd> does all three of that, it first has to move the cursor ot the top left, then clears the scrollback, then all the lines down (without moving the cursor), then performs the hard reset.

But we could indeed add a convenience action for these things to match KDE Konsole, I agree (wich would come in handy for #253).

EDIT: I just realized that while this works I had to add the second mapping line to force redraw of the command prompt. that is however not what konsole does, I think they send a SIGWINCH to the terminal to force redrawing? I should check, and yes, that isn't possible already, so definitely worth an Action. Many thanks :)

**Comment by data-man** [comment]
> I think they send a SIGWINCH to the terminal to force redrawing?

No, I didn't find it.

https://github.com/KDE/konsole/blob/8f4d613692ef27ec93b923f373f6557a00e5bebb/src/session/SessionController.cpp#L1608-L1613

**Comment by christianparpart** [comment]
> > I think they send a SIGWINCH to the terminal to force redrawing?
> 
> No, I didn't find it.
> 
> https://github.com/KDE/konsole/blob/8f4d613692ef27ec93b923f373f6557a00e5bebb/src/session/SessionController.cpp#L1608-L1613

I just checked, it's actually doing `SIGWINCH`.It can be also introspected via the following:
Open KDE Konsole, type `strace -f strace.log cat`; then press <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>K</kbd>, abort the `strace` and then check the contents.

After then I found it also in here:

https://github.com/KDE/konsole/blob/8f4d613692ef27ec93b923f373f6557a00e5bebb/src/session/Session.cpp#L765-L786

This function is invoked from `SessionController::clearAndReset()`. I think we can do a similar trick. :)

**Comment by data-man** [comment]
Huge thanks!

Added `{ mods: [Control],        key: A,             action: ClearHistoryAndReset }` to `contour.yml`.

`$ ls` press `Enter` `Ctrl-A` - ok.
Second pressing `Ctrl-A` closes `Contour`.

Tested Release build with CMake options:
```
-DLIBTERMINAL_LOG_RAW="ON" \
-DLIBTERMINAL_LOG_TRACE="ON" \
-DLIBTERMINAL_EXECUTION_PAR="OFF" \
-DCONTOUR_COVERAGE="OFF" \
-DCONTOUR_PERF_STATS="ON" \
-DCONTOUR_BLUR_PLATFORM_KWIN="ON" \
-DCONTOUR_TESTING="ON" \
-DCRISPY_TESTING="ON" \
-DLIBTERMINAL_TESTING="ON"
```

I'll be testing more!

**Comment by christianparpart** [comment]
> Second pressing `Ctrl-A` closes `Contour`.

I assume that wasn't supposed to happen. One thing that would be really helpful is:

* is that reproducible on your end?
* if so, can you try to run the exact same procedure through valgrind
* or amaybe have it build in debug mode (cmake -DCMAKE_CXX_FLAGS=Debug ...) and ran inside `gdb` or have it a core file created *`ulimit -c unlimited` before execution), then call `gdb /path/to/contour ./core` then type `bt` or `bt full`) and paste that here with that nice `<details>` feature of Github-Issues?

I'll try to see what I can do without that info. Maybe I can repro that too.

**Comment by data-man** [comment]
> I assume that wasn't supposed to happen.

Not reproducible in the debug build.

> I think I have one (it's an assert() that did trigger

:+1:

**Comment by data-man** [comment]
The latest commit fixed it, thank you!

Also sometimes the cursor (blink) disappears after `ClearHistoryAndReset`.

**Comment by christianparpart** [comment]
> Also sometimes the cursor (blink) disappears after `ClearHistoryAndReset`.

What do you mean with "disappears" here? like forever or is the phase shift just a little too long right short after the new reset?

**Comment by data-man** [comment]
https://user-images.githubusercontent.com/1754269/124396795-33f2a300-dd25-11eb-9a13-d0a926f3790c.mp4

**Comment by christianparpart** [comment]
Interesting. Thanks. So let's not closes this until it's fixed. :)

**Comment by data-man** [comment]
Note: I can't reproduce it with `blinking: false`.

**Comment by data-man** [comment]
> Also sometimes the cursor (blink) disappears after ClearHistoryAndReset.

I can' t reproduce it anymore with `blinking: true`. :rocket:
