### ISSUE TITLE
Qt 6 compatibility

### ISSUE THREAD

**Issue by data-man** [contour-terminal/contour#273]
If you don't mind, I can work on it. :)

**Comment by christianparpart** [comment]
Oh that would be awesome. The only sad story is, I should stay compatible with Ubuntu 18.04 LTS for a little longer. Do you see a possibility to retain this support? (We have a PPA where Ubuntu 18.04 users can apt-get instlal contour from).

@data-man many thanks for your interest, btw, I really appreciate that. :)

**Comment by data-man** [comment]
> I should stay compatible with Ubuntu 18.04 LTS for a little longer

Just build the release with Qt5 for this OS?

> many thanks for your interest, btw, I really appreciate that. :)

I like your project and someday Contour will be my only terminal. And I really want to get that day closer! :)

Thanks for the tips, I'll explore!

---------------

BTW Maybe create a GH organization (Contour, libunicode, etc.)? (ContourOrg is free, I checked :smile:)

**Comment by christianparpart** [comment]
> > I should stay compatible with Ubuntu 18.04 LTS for a little longer
> 
> Just build the release with Qt5 for this OS?

If the source stays compatible to Qt5, then this is a solution, yeah.

> > many thanks for your interest, btw, I really appreciate that. :)
> 
> I like your project and someday Contour will be my only terminal. And I really want to get that day closer! :)

 💜

> 
> Thanks for the tips, I'll explore!
> 
> BTW Maybe create a GH organization (Contour, libunicode, etc.)? (ContourOrg is free, I checked 😄)

Oh yeah i considered that already. It will come.

**Comment by data-man** [comment]
> If the source stays compatible to Qt5, then this is a solution, yeah.

I'll explore this later. My tasks now:
- [ ] migrate to CPM. It's really cool!
- [ ] CI refactoring. I think testing with MinGW would be useful.

> Oh yeah i considered that already. It will come.

 :100: :+1:

> Or we find a better org name

ContourProjects?

**Comment by data-man** [comment]
https://github.com/mitsuba-renderer/nanogui seems interesting, isn't it?

**Comment by christianparpart** [comment]
We're now live and running at: https://github.com/contour-terminal/contour/ (the old URL still happily exists and just redirects to the org)
