### ISSUE TITLE
The sixel scrolling mode is the wrong way around

### ISSUE THREAD

**Issue by j4james** [contour-terminal/contour#287]
## Description

When private mode 80 (`DECSDM`) is enabled, that is actually meant to *disable* sixel scrolling, rather than enable it. The way you've currently implemented it is the wrong way around.

## Environment

- Contour Version or Git commit hash: 0.1.1-prerelease-132
- Operating System (name / distribution / version): Ubuntu 20.04

## Steps to Reproduce

From a bash shell execute the following commands:
```
printf "\e[?80h"
cat snake.six
```
Where `snake.six` is any sixel image file. 

With mode 80 enabled, the image should be rendered at the top left of the screen, but it is instead rendered at the current cursor position.

I know this is confusing, because the VT340 manual describes it exactly as you've implemented it, and several other terminals have made the same mistake (including XTerm). The VT382 manuals describe it correctly, though.

The reason I'm bringing this up, is that the author of `lsix` has recently confirmed how this works on a real VT340 terminal, and as a result, XTerm is likely going to correct its implementation to match that behaviour (at least that's the impression I got). So if you want to be compatible with XTerm, you may want to fix this.

That said, it's probably a good idea to wait until the next XTerm release to see if it is actually fixed there. I just wanted to let you know what was going on in case you weren't aware.

**Comment by christianparpart** [comment]
I was not aware. Oh dear, that is a very interesting finding. And also many thanks for forwarding me this news :)

I guess apparently we ALL have done it wrong then? ;-)


I will wait for the xterm commit changing that behavior and will adapt then too of course. 

Many  thanks,
Christian.

**Comment by j4james** [comment]
> I guess apparently we ALL have done it wrong then? ;-)

Not all. From what I've seen, it's about evenly split between those that don't support it all (5 that I know of), those that got it wrong (again 5), and those that got it right (6 if I count my own Windows console fork). So one way of looking at it is at least two thirds got it "not wrong". ;-)

**Comment by christianparpart** [comment]
> > I guess apparently we ALL have done it wrong then? ;-)
> 
> Not all. From what I've seen, it's about evenly split between those that don't support it all (5 that I know of), those that got it wrong (again 5), and those that got it right (6 if I count my own Windows console fork). So one way of looking at it is at least two thirds got it "not wrong". ;-)

Speaking of which, any chance to get a glimpse look at your sixel branch? I am curious :)
Also, I was trying to search for the above mentioned discussions but couldn't really find any. Would you mind adding here some links to the related discussions?

Enjoy the weekend,
Christian.

**Comment by j4james** [comment]
> Speaking of which, any chance to get a glimpse look at your sixel branch? I am curious :)

I'm afraid it's still a private fork, and quite likely to remain that way indefinitely. I had hoped to be able to build something that was VT340 compatible, but with some simple extensions (like more colours) to support modern sixel apps, but I've essentially given up on that idea. The only way I could see it working was by having two almost completely different sixel implementations and some kind of mode to switch between them, and that just seemed like way too much effort.

> Would you mind adding here some links to the related discussions?

Sorry, I meant to link the lsix issue originally, but I clearly forgot. Most of the relevant discussion is taking place there. https://github.com/hackerb9/lsix/issues/41

**Comment by j4james** [comment]
FYI, version 369 of XTerm was released yesterday with the fix for `DECSDM` mode.

**Comment by christianparpart** [comment]
> FYI, version 369 of XTerm was released yesterday with the fix for `DECSDM` mode.

Many thanks for keeping me up to date @j4james  :)
