### ISSUE TITLE
How to build from source ? 

### ISSUE THREAD

**Issue by strogiyotec** [contour-terminal/contour#327]
Hey , I am considering using this emulator as an alternative to alacritty because of FireCode support, however I don't have an experience building c++ projects, README file contains a list of prerequisites but after I install them how to build contour from source ?

**Comment by christianparpart** [comment]
Hey. Many thanks for your interest! In case of support, we also have a discord. 

Can you tell me what OS and version you are running and maybe we can make sure we have a binary auto generated by the CI for everyone.

**Comment by strogiyotec** [comment]
I am using Ubuntu 20.04, the deb package in release works fine, but it's half a year old so I decided to build contour from source

**Comment by christianparpart** [comment]
> I am using Ubuntu 20.04, the deb package in release works fine, but it's half a year old so I decided to build contour from source

Github CI is auto-generating packages for Ubuntu 20.04, too. Have a look here for the latest `master` branch built (as of this writing): https://github.com/contour-terminal/contour/actions/runs/1042023071

I think the actual download link for Ubuntu 20.04 .deb file would then be [here](https://github.com/contour-terminal/contour/suites/3266403912/artifacts/76036933)

**Comment by christianparpart** [comment]
I forgot to mention, while the last release is half a year old, we are very close to a new release - basically only adding stability fixes and UX urgent improvements. :)

**Comment by strogiyotec** [comment]
@christianparpart  so I tried the latest update but having this error on startup , do you know how can I fix it ? 
```
========================================================================
  An internal error caused the terminal to crash ;-( 😭
-------------------------------------------------------

Please report this to https://github.com/contour-terminal/contour/isues/

Contour version: 0.2.0-unreleased-master-b4cfde8
/home/strogiyotec/Java/contour/contour/build/../src/contour/ContourGuiApp.cpp:186
/home/strogiyotec/Java/contour/contour/build/../src/contour/ContourGuiApp.cpp:198
/usr/include/c++/9/bits/invoke.h:74 (discriminator 4)
/usr/include/c++/9/bits/invoke.h:97
/usr/include/c++/9/functional:403
/usr/include/c++/9/functional:485
/usr/include/c++/9/bits/std_function.h:287
/usr/include/c++/9/bits/std_function.h:689
/home/strogiyotec/Java/contour/contour/build/../src/crispy/App.cpp:215
/home/strogiyotec/Java/contour/contour/build/../src/contour/ContourGuiApp.cpp:53
/home/strogiyotec/Java/contour/contour/build/../src/contour/main.cpp:24
0x7f12e5fb30b3

```

**Comment by christianparpart** [comment]
Most likely your command line arguments seem to have caused this. What did your cmdline look like?

Also, since the last release half a year agoy the config file has changed inherently. You can remove the existing one and contour will create a fresh one on next start.

**Comment by strogiyotec** [comment]
@christianparpart  so I deleted the config file and tried again , seems like it's working now , the previous config was generated by controur latest release , thanks

**Comment by christianparpart** [comment]
I still should fix that case fire people with a very old config. 

Be sure to try sixel images (`img2sixel`, `lsix`), emoji and ligature support :)

Keep in mind, compared to alacritty, contour is very young. If you find anything disturbing or odd, please keep on reporting.

Enjoy. ;-)
