### ISSUE TITLE
The font fallback requirement is too strict for CJK fonts

### ISSUE THREAD

**Issue by skyline75489** [contour-terminal/contour#343]
## Description

CJK characters are not correctly displayed in contour, because the font fallback mechanism actually *skip* the correct font to use.

## Environment

- Contour Version or Git commit hash: 76eeff1897bdec0823bd2084d4c59b6778f1122c
- Operating System (name / distribution / version): Linux X11
- Contour configuration: none
- TERM environment variable: xterm-256color
- Compiler version: GCC 10.3

## Steps to Reproduce

This is part my `ls` result in home directory

```text
下载      图片    桌面    视频
```

This can't be correctly displayed in contour, because the font chosen doesn't contain glyphs for these characters.

## Possible Solution

This is the change needed for contour to find the correct font (`Noto Sans Mono CJK`, which is part of the default CJK fonts (Noto Sans Family) for many Linux distros).

```diff
diff --git a/src/text_shaper/open_shaper.cpp b/src/text_shaper/open_shaper.cpp
index 54d7ef9..4176c4f 100644
--- a/src/text_shaper/open_shaper.cpp
+++ b/src/text_shaper/open_shaper.cpp
@@ -391,8 +391,7 @@ namespace // {{{ helper
             FcPatternGetInteger(font, FC_SPACING, 0, &spacing);
             if (_fd.force_spacing)
             {
-                if ((_fd.spacing == font_spacing::proportional && spacing < FC_PROPORTIONAL) ||
-                    (_fd.spacing == font_spacing::mono && spacing < FC_MONO))
+                if ((_fd.spacing == font_spacing::proportional && spacing < FC_PROPORTIONAL))
                 {
                     debuglog(FontFallbackTag).write("Skipping font: {} ({} < {}).",
                         (char const*)(file), fcSpacingStr(spacing), fcSpacingStr(FC_DUAL));
@@ -792,9 +791,6 @@ void open_shaper::shape(font_key _font,
             fontInfo.description.spacing != font_spacing::proportional)
         {
             FontInfo const& fallbackFontInfo = d->fonts_.at(fallbackKeyOpt.value());
-            bool const fontIsMonospace = fallbackFontInfo.ftFace->face_flags & FT_FACE_FLAG_FIXED_WIDTH;
-            if (!fontIsMonospace)
-                continue;
         }
 
         FontInfo& fallbackFontInfo = d->fonts_.at(fallbackKeyOpt.value());
```

As you can see in the diff, it actually does *NOT* report `FC_SPACING` and `FT_FACE_FLAG_FIXED_WIDTH`, for some reason.

Note that VTE-based terminals and Alacritty all pick up the font correctly.

**Comment by christianparpart** [comment]
Oh. That is awesome. Many many thanks for taking the time, also for looking into the text shaping code. :)

**Comment by skyline75489** [comment]
Gladly :)

I'm new to the font area, though. I didn't really know anything about fontconfig until I started to look at the code inside contour. So I'm not quite sure why `Noto Sans Mono CJK` does not report some monospace properties as expected. I didn't get to test other fonts, either.

I'd like to point out that `Noto` font family has been the dominating CJK font family in the Linux world for many years, because it's probably the first font that is both of very high quality and completely free of charge (and licensing issue). I can't honestly think of another font that can compete & replace Noto at this moment (without violating license requirements of commercial fonts). So maybe making `Noto` work is good enough for most CJK users. `Noto` actually contains fonts for other languages, too. I can't, however, make the same assumption for people who use other languages.

**Comment by christianparpart** [comment]
Just before I start working on this one, have a look at that screenshot.
![image](https://user-images.githubusercontent.com/56763/127023057-159781a9-7f06-460f-a12b-97065712b09e.png)

I think that one looks right, isn't it? Or is that wrong? :)

**Comment by christianparpart** [comment]
@skyline75489 Inside the font section you can set `only_monospace: false` in order to relax the monospace requirement. While this one works for me, I now start to wonder what the default should be.

Also, The reason why `NotoSansCJK-Regular.ttc` (in my case) is not being elected for font fallback is that the attempt to get its spacing property fails.

https://github.com/contour-terminal/contour/blob/97a3eba82bc78ab7b50eed2375366f60dc910511/src/text_shaper/open_shaper.cpp#L390-L397

I will try to look into what other TEs are doing (how they do fontfallback and how they filter out non-monospace fonts, if they filter out at all during fallback)

**Comment by christianparpart** [comment]
side node, just checked. alacritty doesn't do any spacing checks. you can also use Arial if one wants to. Not so sure about gnome-terminal or kitty just yet. But I think it's save to flip the default.

p.s.: the linked pr renames the flag to something more appropriate: `strict_spacing` which defaults to `false`now.

**Comment by skyline75489** [comment]
The screenshot you posted is correct. Thanks for the work!

Also I would like to point out that “Noto Sans CJK Regular” is not the same as “Noto Sans Mono CJK”. I am ok with the first one not having monospace properties but I am not sure about the second one.
