### ISSUE TITLE
munmap_chunk(): invalid pointer following unknown CSIs

### ISSUE THREAD

**Issue by dankamongmen** [contour-terminal/contour#365]
## Description

I updated my Contour build this evening, and ran the newest `notcurses-info` within it. I get the following output following parsing of the configuration:

```
[vt.parser:dankamongmen/contour/src/terminal/Sequencer.cpp:1297] Unsupported VT sequence: CSI = c
[vt.parser:dankamongmen/contour/src/terminal/Sequencer.cpp:1294] Invalid VT sequence: CSI ? 80;8452 h
[vt.parser:dankamongmen/contour/src/terminal/Sequencer.cpp:1294] Invalid VT sequence: CSI ? 8452 l
munmap_chunk(): invalid pointer
Aborted (core dumped)
```

## Environment

- Contour Terminal Emulator 0.2.0-unreleased-master-31f06c9
- Linux 5.13.6nlb
- default configuration
- xterm-256color
- gcc version 10.2.1 20210110 (Debian 10.2.1-6)

## Steps to Reproduce

The easiest way to reproduce right now is to run `notcurses-info`, either from Notcurses tip of master, or from the 2.3.12 release. You'll get the following output:

```
[vt.parser:dankamongmen/contour/src/terminal/Sequencer.cpp:1264] Unknown VT sequence: CSI 15;3 ~
[vt.parser:dankamongmen/contour/src/terminal/Sequencer.cpp:1264] Unknown VT sequence: CSI 17;3 ~
[vt.parser:dankamongmen/contour/src/terminal/Sequencer.cpp:1264] Unknown VT sequence: CSI 18;3 ~
[vt.parser:dankamongmen/contour/src/terminal/Sequencer.cpp:1264] Unknown VT sequence: CSI 19;3 ~
[vt.parser:dankamongmen/contour/src/terminal/Sequencer.cpp:1264] Unknown VT sequence: CSI 20;3 ~
[vt.parser:dankamongmen/contour/src/terminal/Sequencer.cpp:1264] Unknown VT sequence: CSI 21;3 ~
[vt.parser:dankamongmen/contour/src/terminal/Sequencer.cpp:1264] Unknown VT sequence: CSI 23;3 ~
[vt.parser:dankamongmen/contour/src/terminal/Sequencer.cpp:1294] Invalid VT sequence: CSI ? 80;8452 h
[vt.parser:dankamongmen/contour/src/terminal/Sequencer.cpp:1294] Invalid VT sequence: CSI ? 8452 l
munmap_chunk(): invalid pointer
Aborted (core dumped)
```

I'm looking into exactly what's blowing up contour, but this works to reproduce right now.

**Comment by dankamongmen** [comment]
note that this is probably a pretty recent issue, as I believe i ran `notcurses-info` without this issue prior to updating.

**Comment by christianparpart** [comment]
Guten Morgen Nachteule, @dankamongmen 

Thanks man. I will repro that ASAP in my next night. :)

**Comment by christianparpart** [comment]
> note that this is probably a pretty recent issue, as I believe i ran `notcurses-info` without this issue prior to updating.

I was kind touching the VT parser. But only for the Ground state (SSE optimizations). ;(

**Comment by dankamongmen** [comment]
> > note that this is probably a pretty recent issue, as I believe i ran `notcurses-info` without this issue prior to updating.
> 
> I was indeed touching the VT parser. But only for the Ground state (SSE optimizations). ;(

to be fair, i am not certain when i last updated my contour. i did notice that it seemed significantly faster than i remembered, so perhaps i was quite a bit behind.

**Comment by christianparpart** [comment]
Note to myself when executing this.

`notcurses-info` leaves this at stdin: `^[[2;1R^[[?2026;2$y^[[?1;0;256S^[[?2;0;800;600S^[[?1;0;256S^[[4;1325;1920t^[[?65;22;29;314;1;28;4;8c`

logging output:

![image](https://user-images.githubusercontent.com/56763/127928644-2650d355-51c7-4eaa-9c3e-07216f21cf85.png)

**Comment by dankamongmen** [comment]
isn't that the query string i send to you?

**Comment by christianparpart** [comment]
> isn't that the query string i send to you?

Exactly and it seems to break right after you send me `CSI 6 n` and I reply with `CSI y ; x  R`. Not sure yet why. It's late, i'm going into global GC run before making any qualified statements. :)
