### ISSUE TITLE
How to set custom WM_CLASS

### ISSUE THREAD

**Issue by uunnxx** [contour-terminal/contour#376]
Hi! Thank you for this awesome terminal emulator.
I've searched all closed and open issues for `WM_CLASS` and just for `class` but can't able to find it.
Let me know how can I set custom `WM_CLASS` for getting new instance?

Like `urxvt` :
```
urxvt -name float 
urxvt -name ranger
urxvt -name translator
```
or like `alacritty` : 
```
alacritty --class float
alacritty --class ranger
alacritty --class translator
```

Example `i3wm` config:
```
set $trans "alacritty --class translator -e trans :en jp: -I"
bindsym $mod+t exec --no-startup-id $trans


for_window [class="Alacritty" instance="translator"] floating enable resize set 880 400
for_window [class="Alacritty" instance="translator"] move position 1040 674
```

**Comment by christianparpart** [comment]
Hey @uunnxx 

Many thanks for your interest. I think am am.... sure that we do not support that yet.

So let's use this ticked to implement that. :-)
