### ISSUE TITLE
Configuration to disable titlebar on macos

### ISSUE THREAD

**Issue by mTvare6** [contour-terminal/contour#379]
## Abstract
In current versions there is a titlebar in the macos version being able to disable it will be better

## Motivation
Other terminals like alacritty, kitty and iTerm have the option to disable titlebar(and minimize maximize and close options) being able to remove either titlebar and even the window decorators would be nice

**Comment by christianparpart** [comment]
Hey  @mTvare6 ,

that is certainly a nice idea. Many thanks :)

**Comment by christianparpart** [comment]
Note to myself: I think what needs to be used is [bool QMainWindow::unifiedTitleAndToolBarOnMac](https://doc.qt.io/qt-5/qmainwindow.html#unifiedTitleAndToolBarOnMac-prop).
