### ISSUE TITLE
Use "login" executable by default on OSX (was: zprofile and zshrc isn't sourced)

### ISSUE THREAD

**Issue by mTvare6** [contour-terminal/contour#381]
## Description
~/.zprofile and $ZDOTDIR/.zshrc isn't sourced by default

## Environment

- Contour Version or Git commit hash: 0.1.1 132
- Operating System (name / distribution / version): macOS(11.3.1)
- Contour configuration: stock
- TERM environment variable: xterm-256color truecolor
- Compiler version: didn't compile from source

## Steps to Reproduce

Have .zshrc under $ZDOTDIR and not under home and set ZDOTDIR to the directory .zshrc is in .zprofile

**Comment by uspasojevic96** [comment]
Don't you need to set `$ZDOTDIR` through `.zshenv` first? Can you give us examples on which terminals it works and/or can you give us your dotfiles?

Resources:
https://github.com/romkatv/zsh4humans/issues/2
https://zsh.sourceforge.io/Intro/intro_3.html#SEC3

**Comment by mTvare6** [comment]
@uspasojevic96 I have set ZDOTDIR in .zprofile, it seems to work under alacritty and iTerm
I tried checking if ZDOTDIR is set via `echo $ZDOTDIR` but it is empty in contour. I have set zdotdir to ~/.config/zsh
```zsh
export ZDOTDIR="$HOME/.config/zsh"
```

**Comment by uspasojevic96** [comment]
> So does contour not start login shell by default?

That's a question for @christianparpart , while we wait for him, can you try setting the env in `.zshenv`?

**Comment by mTvare6** [comment]
I set $ZDOTDIR in .zshenv and it says tmux(or other stuff) not found (maybe because I set all $PATH stuff in .zprofile), but on sourcing ~/.zprofile in ~/.zshenv it worked, but this feels like unnecessary hack because other terminals work without it

**Comment by uspasojevic96** [comment]
Ok, then that confirms it that zsh isn't spawned as login interactive shell

**Comment by mTvare6** [comment]
Also is it a known issue that font rendering is bad on macos or do I make another issue for that

**Comment by uspasojevic96** [comment]
It's known, HiDPI isn't working properly yet

**Comment by christianparpart** [comment]
>     * Contour Version or Git commit hash: 0.1.1 132

(I really need to release 0.2.0 damn. there are worlds between those two releases) :-)

> Have .zshrc under $ZDOTDIR and not under home and set ZDOTDIR to the directory .zshrc is in .zprofile

Contour (I think like most (if not all) terminal emulators do by default start the executable that is configured as your default shell. So that's working apparently, great. This implies that it's not boot up as "login shell". This can be tweaked yourself by adding that to your profile:
```yaml
profiles:
    your_profile:
        shell: "/bin/zsh"
        arguments: ["--login"]
```

EDIT:

Ok, found it. OS/X plays the extra-chicken and wants you to run `login` executable instead of `bash --login` or `zsh --login` (etc). So another way around would be to set `shell: "login"` with `arguments: ["-fp", "YourUserName"]`. Seems like all the other terminal emulators have suffered the same extra-chicken-game and worked around that. https://github.com/alacritty/alacritty/issues/1071 & https://github.com/kovidgoyal/kitty/issues/247 at least (and iTerm2 mentioned via screenshots).

This can be easily fixed (btw: without any deeper knowledge of VTE's :) )

**Comment by uspasojevic96** [comment]
Wait, I didn't notice the version he was running, that means that he isn't talking about HiDPI but about actual font issues that I used to face

**Comment by mTvare6** [comment]
I tried to grab a build from CI and it works without any workaround

**Comment by christianparpart** [comment]
> I tried to grab a build from CI and it works without any workaround
> Edit: I get this error when I added `scientifica` in font section, with other fonts it works fine
> ![image](https://user-images.githubusercontent.com/57838468/128803804-36b5507d-6a2b-4f23-9f50-8b3bd11e7a8f.png)

Lovely. We are still in early stages. So we would love to get feedback and bug reports as much as your time permits. Do, enjoy and many thanks for your interest. :)

**Comment by mTvare6** [comment]
On using `open` it launches the terminal and everything other than tmux is sourced, but on double pressing the app via finder(and launchpad) it opens fine with tmux

https://user-images.githubusercontent.com/57838468/128821831-28e18b38-ab9c-46d0-8500-0e1a8ba46f90.mov

Everything other than tmux is sourced, very weird

**Comment by christianparpart** [comment]
Hey @mTvare6 

many thanks for that video demo. I will be booting into my MBP soon to test/fix and actually implement this. :)

**Comment by mTvare6** [comment]
@christianparpart did you check the edit, it happened because `open` passed the TMUX variable to contour so it thought tmux is running, also I had mentioned it worked without any workaround, but apparently I already edited the yaml file to have
```yaml
        shell: "login"
        arguments: ["-fp", "name"]
```
sorry if I had confused or wasted your time

**Comment by christianparpart** [comment]
> @christianparpart did you check the edit, it happened because `open` passed the TMUX variable to contour so it thought tmux is running, also I had mentioned it worked without any workaround, but apparently I already edited the yaml file to have
> 
> ```yaml
>         shell: "login"
>         arguments: ["-fp", "name"]
> ```
> 
> sorry if I had confused or wasted your time

Hey, I just read you *now*. 

This was certainly no waste of time. I did not even know of that behavior of OS/X (as I am mainly using Linux, and only rarely OS/X or Windows). I still try hard to make this terminal emulator working the same on all platforms.

The default startup shell is the one that I suggested you to do manually. It's still an improvement, so many thanks. :)
