### ISSUE TITLE
Add Kitty's graphic protocol support

### ISSUE THREAD

**Issue by WSLUser** [contour-terminal/contour#382]
## Motivation

Since [WezTerm](https://github.com/wez/wezterm/issues/986) is now picking this up and notcurses now detects it via query, I'd like Contour to also adopt this graphics protocol, especially as notcurses can now run on Windows, where I would be testing this out.

## Specification

See https://sw.kovidgoyal.net/kitty/graphics-protocol.html and https://github.com/kovidgoyal/kitty/issues/33 for discussion and implementation details.

**Comment by mTvare6** [comment]
I think they have plan to support a [new protocol](https://github.com/contour-terminal/terminal-good-image-protocol)

**Comment by christianparpart** [comment]
> I think they have plan to support a [new protocol](https://github.com/contour-terminal/terminal-good-image-protocol)

Exactly. There are many reasons for me to definitely not support that.
