### ISSUE TITLE
Missing contour-terminfo dependency in latest Ubuntu 20.04 package?

### ISSUE THREAD

**Issue by j4james** [contour-terminal/contour#400]
## Description

I'm trying to install the latest release on Ubuntu 20.04 and it's failing with the error:
```
contour depends on contour-terminfo: however:
  Package contour-terminfo is not installed.
```

## Environment

- Contour Version or Git commit hash: 0.2.0.173
- Operating System (name / distribution / version): Ubuntu 20.04

## Steps to Reproduce

1. Download contour_0.2.0.173-ubuntu_20_04_amd64.deb from the [releases](https://github.com/contour-terminal/contour/releases) page.
2. Run `dpkg -i ./contour_0.2.0.173-ubuntu_20_04_amd64.deb`

It does basically install, but it reports the error mentioned above. Then any time I do something with apt-get it complains about the broken installation, and "repairing" it just uninstalls Contour.

I'm a bit clueless when it comes to Linux, so it's possible I'm just not installing it correctly, but I had no problems with the previous release version (0.1.1).

**Comment by christianparpart** [comment]
Oh, many thanks. I will look into it. :) Did you try the PPA from https://launchpad.net/~christianparpart/+archive/ubuntu/contour-dev ? There the dependency should be present.

**Comment by j4james** [comment]
> Did you try the PPA from https://launchpad.net/~christianparpart/+archive/ubuntu/contour-dev ? There the dependency should be present.

That worked. Thank you!
