### ISSUE TITLE
Wobbly rendering in Vim when also used with emojis

### ISSUE THREAD

**Issue by whisperity** [contour-terminal/contour#401]
## Description

Using `coc.nvim` with the diagnostics engine set to use emojis as icons:

```json
  "diagnostic": {
    "errorSign": "⛔️",
    "warningSign": "⚠️",
    "infoSign": "ℹ️",
    "hintSign": "💡"
  },
```

will result in the emojis rendered in a way that the text in the line of the rendering breaks apart.

For example, sometimes the `colorcolumn` (80-char limit marker) gets shifted to the right:

![A code example with syntax errors and warnings rendered as diagnostics, but breaking the rendering](https://user-images.githubusercontent.com/1969470/131663339-ccb5f6a7-53c8-4448-af20-6f258305082a.png)

Setting `signcolumn=number` helps in hiding the number, but notice here that the line closing `;` is shadowed by the rendering error. (It's **not** missing from the code, if it was, the next line would be reported to have a compiler error too.)

Also note now the supposedly hidden number "leaks" from behind the emoji.

![Same issue with signcolumn=number where the rendering issue shows up with the number leaking from behind the emoji](https://user-images.githubusercontent.com/1969470/131663461-9093526b-f441-42df-b09c-f62cfbd922b1.png)

It seems to be somehow Vim specific and related to the dynamic change of contents (i.e. simply `cat`ing the file doesn't show this issue). For example, editing `coc-settings.json` which has multiple diagnostics will show the following wobbliness.
Notice how the opening `{` after `clangd` is also shown a whole line beforehand, like that part of the screen wasn't "wiped".

![Multiple wobblers in coc-settings.json on the right, and further rendering issues with lines not wiping correctly.](https://user-images.githubusercontent.com/1969470/131663739-58f8044c-75f2-4132-9dad-ea5964c050b5.png)

**This issue is not present if emojis are not used!**

[contour.log](https://github.com/contour-terminal/contour/files/7090682/contour-emoji.log)

## Environment

- Contour Version or Git commit hash: 0.2.0
- Operating System (name / distribution / version): Ubuntu 18.04
- Contour configuration:
   - `font.regular: "JetBrainsMono Nerd Font"`
   - `font.only_monospace: false`
   - `font.size`: 12
   - Otherwise unchanged (well, there are colour changes and custom keybinds, but that's it.)
- Vim configuration:
   - neovim/neovim@284199bc4b
   - neoclide/coc.nvim@595e60210
   - `coc-clangd`: 0.14.0 (clangd/coc-clangd@1ece8f324b537ae7aa03ed4b24e1371f10ec4174)
   - Tried all `set signcolumn=no`, `auto`, `number`
- TERM environment variable: `xterm-256color`

**Comment by christianparpart** [comment]
ah i know what the problem is.

I'll be reverting that change for 0.2.1.

the root cause is that i am treating double width (Wide) characters as double width, and the applications do not seem to respect that. And they don't respect that because historically all terminals where broken on getting emoji width right. I'd like to stick with the way it is right now, but I fear I'll but only one of a few that would like to have that more Unicode conformant. ;(

**Comment by christianparpart** [comment]
In the long run, I'd like to have that runtime configurable via VT sequence (DECSM/DECRM/DECRQM). But for now we've worked around that classic one.

**Comment by whisperity** [comment]
> DECSM/DECRM/DECRQM

@christianparpart I'm not sure what these are, but it sounds like the user application still needs to support emitting these control sequences in that case.

**Comment by whisperity** [comment]
(Nevertheless, can confirm the "fix". :slightly_frowning_face:)
