### ISSUE TITLE
Feature request: RPM packaging

### ISSUE THREAD

**Issue by NTBBloodbath** [contour-terminal/contour#420]
Hey, hope you're doing well!

As the title says I want to have a RPM package for contour. It would benefit users from Fedora/RHEL because there is people _like me_ who doesn't want to or can't manually build contour from source.

I know all the necessary build dependencies (including the extra ones) and I have a bit of experience packaging software using RPM. Did a tiny [spec file](https://gist.github.com/NTBBloodbath/4ffe36fe66efa79c93ce438407beb187) for compiling contour for testing purposes, here are the produced package files.

![RQ6zKP.png](https://iili.io/RQ6zKP.png)

And the package while installing it

![RQ6oiB.png](https://iili.io/RQ6oiB.png)

Note that there's still some work to be done, in Fedora we have a similar build system like PPAs in Ubuntu but we call them COPRs. I never uploaded a package to COPR so I don't know much about how it works so [here](https://docs.fedoraproject.org/en-US/quick-docs/publish-rpm-on-copr/) are the docs in case someone wants to maintain it before me haha.

I'll be glad to maintain the COPR repository for uploading the RPM packages later, but it's gonna take a bit because I need to learn how COPR tools works (e.g. [tito](https://github.com/rpm-software-management/tito)). However if someone wants to do it and already knows how to use COPR then feel free to upload it :)

Regards

**Comment by christianparpart** [comment]
Hey @NTBBloodbath 

Many thanks for your interest in our project at such an early stage. I always had RPM packages in my mind but never -  so far - did it, purely because I don't have a RPM based system lying around.

Let's have this for at least next bugfix release (I actually highly recommend building from master branch as it contains exclusively bug fixes from latest stable release 🐞).

From your writing I can assume you are using Fedora, right? What spin do you recommend me for testing?

Ideally I'd like to get the Github CI auto-creating these RPM packages, too.

**Comment by NTBBloodbath** [comment]
Hi, thank you for this amazing project!

> Let's have this for at least next bugfix release (I actually highly recommend building from master branch as it contains exclusively bug fixes from latest stable release :lady_beetle:).

Sure thing, it's a good idea imo

> From your writing I can assume you are using Fedora, right? What spin do you recommend me for testing?

Yes I do, if you're gonna use a VM for testing this maybe go with Xfce spin :p

> Ideally I'd like to get the Github CI auto-creating these RPM packages, too.

There are some actions for building RPM packages, I think they're using a docker image under the hood to build stuff but it seems to work. [This](https://github.com/AnjaloHettiarachchi/rpmbuild) is one that I saw a few days ago and should do the trick.

> p.s.: Can I reuse your spec file as basis for RPM packaging support?

Yes, you can. My spec file is completely functional and contains all the required _and extra_ build dependencies, you can take a look at [this](https://rpm-packaging-guide.github.io/) guide to see the required tools for building RPM packages and also a good explanation about how does spec files work.

Also for downloading the tarball for the source you can use `spectool` tool. This is how I do it
```sh
spectool -g -R /path/to/spec/file
```

where

- `-g` tells spectool to get all the sources/patches that are listed with a URL in `SourceN` fields
- `-R` tells spectool that we want to download into rpm's `%{_sourcedir}` (`~/rpmbuild/SOURCES`)

**Comment by WSLUser** [comment]
I'd suggest publishing to EPEL as that will allow the most rpm distros to consume the package and enable more users to use Contour. Of course, I'd verify Contour works fine on CentOS 7 first. But if it does, Fedora and new alternatives like RockyLinux and AlmaLinux ought to work just fine too.

**Comment by christianparpart** [comment]
> I'd suggest publishing to EPEL as that will allow the most rpm distros to consume the package and enable more users to use Contour. Of course, I'd verify Contour works fine on CentOS 7 first. But if it does, Fedora and new alternatives like RockyLinux and AlmaLinux ought to work just fine too.

Ah. Good to know. But first we need automated RPM creation in the CI :)

**Comment by WSLUser** [comment]
If interested, Clear Linux has an interesting RPM creation tool called [autospec](https://github.com/clearlinux/autospec). From there, you'd be able to easily add Contour as a bundle in addition to publishing for other rpm based distros. Clear Linux is a bit different than other rpm distros though CBL-Mariner probably is the closest one like it.

**Comment by jerch** [comment]
I suggest to have a look at https://build.opensuse.org/ for the rpm creation. Was quite convenient for me in the past and has blueprints for almost all rpm based distros.
