### ISSUE TITLE
Build a website for contour

### ISSUE THREAD

**Issue by christianparpart** [contour-terminal/contour#435]
Let's build a website for Contour.

The website should be static, e.g. so that it can also be put behind github.io.

Initially it should at least contain:

* what is this project
* whom is this for
* cool features list (maybe along with screenshots)
* how to install for: Windows, OS/X, Ubuntu, Arch, from source.
* what special VT extensions are supported
* what else?

**Comment by uspasojevic96** [comment]
jekyll can be used for this i think

**Comment by christianparpart** [comment]
> jekyll can be used for this i think

Yes, or the readthedocs.io rst files. The problem is my creativity of writing non-programming text and the lag of skill to sell ;-)

**Comment by qubisc** [comment]
I am interested:) Are the website in development or still free to do?:D

**Comment by uspasojevic96** [comment]
Hi, thanks for your interest! The development of website didn't start yet, you can do it whenever you want.

**Comment by christianparpart** [comment]
Maybe you want to join our Discord for some more real time communications one that matter, if you want, too. :)
