### ISSUE TITLE
Improve logging facility

### ISSUE THREAD

**Issue by christianparpart** [contour-terminal/contour#440]
currently we use the `<debuglog.h>` header-only logging API, which is good, but we also ab-use it for error logging and warnings.

We need some kind of logging facility that allows us to, **conveniently** log:

- errors
- warnings
- debug messages (filterable by tags/keywords)
- debug trace messages (filterable by tags/keywords - most likely it's sufficient to join that with debug messages)

for debug/trace messages maybe having a `int level` to determine how much to debug/trace? (not sure that's really good/needed).

- `fmtlib` should be used for formatting
- logging should be as simple as a single function call

**Comment by data-man** [comment]
> fmtlib should be used for formatting

My favourites are: :smile: 
https://github.com/gabime/spdlog
https://github.com/MengRao/fmtlog

**Comment by christianparpart** [comment]
This ticket I did create for keeping track of it. @uspasojevic96 is interested in maybe taking this over. 

I'll have a look at fmtlog (iff it's using fmtlib under the hood). I'd definitely prefer to stick with fmtlib for formatting, as most of the custom data types already provide fmtlib formatters that are useful to be printed for logging.
