### ISSUE TITLE
sixel painting to not destroy existing contents

### ISSUE THREAD

**Issue by christianparpart** [contour-terminal/contour#450]
>>   you'll then see that Contour draws the image on a black background, annihilating the glyphs underneath, unlike other sixel implementations which interpret unspecified pixels as transparent =]. fixing that would be the thing that earned you the most high marks in my book =].

> Challenge excepted. 💣 I see what I can do to get it into the next bugfix cycle (release 0.2.1), as that can be seen as a fix too, because that's how xterm is rendering it, right?

**Comment by j4james** [comment]
Copying my comment from the [notcurses discussion](https://github.com/contour-terminal/contour/discussions/444#discussioncomment-1451889), in case you don't see it there:
> Note that transparency is dependent on the _Background Select_ parameter (P2) of the sixel escape sequence. The background should only be transparent if P2 is set to 1. Xterm doesn't handle this correctly, so please don't copy their behaviour exactly.

**Comment by j4james** [comment]
Note that I was wrong about P2 not having any effect when raster attributes are set is wrong. It looks more like it's the other way around, i.e. the dimensions specified in the raster attributes have no effect when P2 is set to 1.

For example, consider an image like this over a background of Es:
```echo -e '\ePq"5;1;120;60#1!60T-!60T-!60T-!60T\e\\\n'```

![image](https://user-images.githubusercontent.com/4181424/137218349-4b9c0d2a-4a2f-418a-8f1f-2297984428d6.png)

The image is 120px high while the raster attribute height is given as 60px, so the half that extends below that point will have the underlying text showing through, despite the fact that P2 is not set to 1.

But if you _do_ set P2 to 1, I suspect the background will not be filled at all, so all the zero pixels in the image will be treated as transparent, and the dimensions specified by the raster attributes are irrelevant.
```echo -e '\eP;1q"5;1;120;60#1!60T-!60T-!60T-!60T\e\\\n'```

![image](https://user-images.githubusercontent.com/4181424/137218364-70ccd968-c4bc-4a80-9e9f-240837a01809.png)

**Comment by j4james** [comment]
> I have to sadly admit I am ignoring the aspect ratio

Not many TEs handle aspect ratio correctly, so if you don't intend to support legacy VT340 and VT240 applications, it's probably not a big deal. Occasionally you may come across old sixel images from the VT240 that depend on AR, because it only supported 2:1, but I don't think it's that common. I just find it useful for test cases, because it's so convenient when you just need to output simple block structures, so I use it all the time.

**Comment by dankamongmen** [comment]
> Note that I was wrong about P2 not having any effect when raster attributes are set. It looks more like it's the other way around, i.e. the dimensions specified in the raster attributes have no effect when P2 is set to 1

this matches my intuition (save that the terminal might use them to optimize something).

**Comment by dankamongmen** [comment]
> I have to sadly admit I am ignoring the aspect ratio (if provided) currently. I take the pixels as is. I am absolutely fine in fixing that. But until now it seemed (!) sufficient for modern apps as that's never set anyways.

fwiw, i never use them, since it doesn't make any sense to me how aspect ratio could be enforced on a pixel (and images don't always include information on their "pixel aspect ratio").

**Comment by j4james** [comment]
> it doesn't make any sense to me how aspect ratio could be enforced on a pixel

Think of it as similar to line doubling. If the AR is 2:1, every scanline in the image is output twice, if it's 3:1 they'll be output three times, etc. Aspect ratios are only ever integer values.

> images don't always include information on their "pixel aspect ratio"

If it's not specified, I believe the default is meant to be 2:1, for backwards compatibility with the VT240 (possibly also the VT125).

**Comment by dankamongmen** [comment]
> Think of it as similar to line doubling. If the AR is 2:1, every scanline in the image is output twice, if it's 3:1 they'll be output three times, etc. Aspect ratios are only ever integer values.

ahhh ok so the result isn't necessarily what you specify; this is strictly a blowup. got it. still kinda neat!

> If it's not specified, I believe the default is meant to be 2:1, for backwards compatibility with the VT240 (possibly also the VT125).

i meant the source material, i.e. pngs and such.
