### ISSUE TITLE
text buffer capture only works on second attempt

### ISSUE THREAD

**Issue by christianparpart** [contour-terminal/contour#493]
Message: `VTE did not respond to CAPTURE 'CSI > Ps; Ps t';`
Sometimes it is: `"did not start with expected prefix" thing.`

For some reason one has to press the keybind twice in order to capture the buffer. Let's fix that!

**Comment by whisperity** [comment]
#613 did not fix everything, there is something still wrong with more complex prompts such as Zsh with P9k/P10k, etc. Barebones Bash capture does indeed work.

**Comment by uspasojevic96** [comment]
barebones zsh also works, it's just with complex prompts

**Comment by christianparpart** [comment]
thx for re-opening. Okay, so what's "complex prompts" then. I'll keep digging this week. I wanted to address the "smal initial-winsize-on-ubuntu18" and "compile-me-on-clang-linux" problem, too. (all 3 this week). let's see how far I'll get. :)

**Comment by uspasojevic96** [comment]
Powerline or my prompt

**Comment by whisperity** [comment]
I think p9k/p10k should be enough.
The ZSH you're using on stream shall be sufficient too (I observed you use powerline and the "zsh syntax highlighting" plugin.)

**Comment by whisperity** [comment]
@christianparpart I think p9k/p10k should be enough.
The ZSH you're using on stream shall be sufficient too (I observed you use powerline and the "zsh syntax highlighting" plugin.)

I've attached a full debug log from my machine (and my zsh and prompt) on Discord for you :slightly_smiling_face: I think digging into that for the exact VT sequences could give some insight.

@uspasojevic96 Were you able to pin down whether it is the **prompt** causing the issue, or the Contour ZSH integration script?

**Comment by uspasojevic96** [comment]
its not integration, i have disabled it and still had issue

**Comment by christianparpart** [comment]
But now we can close it. (famous last words).

**Comment by whisperity** [comment]
So far can confirm it works properly. :grimacing: What an odd bug. :stuck_out_tongue:
