### ISSUE TITLE
Font choice looks weird when mixing CJK & ASCII characters.

### ISSUE THREAD

**Issue by skyline75489** [contour-terminal/contour#494]
## Environment

- Contour Version or Git commit hash: be0967df97b1c40ff8ad72ccd3f9fe38e0fc726a
- Operating System (name / distribution / version): Manjaro KDE
- Contour configuration: `strict_spacing = false`
- TERM environment variable:
- Compiler version:
-

## Steps to Reproduce

![image](https://user-images.githubusercontent.com/4710575/140290648-d0466a94-1e45-49d4-88bc-423c1ed9a7bb.png)

**Comment by christianparpart** [comment]
Thanks :)

**Comment by christianparpart** [comment]
@skyline75489 Hey, I hope you're doing well. Would you mind telling me what font you have been using that can trigger this? I would like to try to reproduce this and isolate it into a test case, so I can ideally improve the situation. Many thanks :-)
