### ISSUE TITLE
Show information about used libraries

### ISSUE THREAD

**Issue by data-man** [contour-terminal/contour#506]
Something like this:
`$ contour version` will output:
>Contour Terminal Emulator 0.3.0-unreleased-master-122cc23
Compiled with:
Qt:
FreeType:
HarfBuzz:
libfmt:
etc.

**Comment by christianparpart** [comment]
nice idea!

This should be a list/table containing something like:

[project name] | [version] | [license] | [url]

**Comment by data-man** [comment]
> This should be a list/table

E.g. using https://github.com/p-ranav/tabulate? ;)

**Comment by christianparpart** [comment]
> > This should be a list/table
> 
> E.g. using https://github.com/p-ranav/tabulate? ;)

Nö. That's too much and no need for such things fior a simple about-output.
