### ISSUE TITLE
Integrate notcurses-demo into CI

### ISSUE THREAD

**Issue by christianparpart** [contour-terminal/contour#511]
In order to prevent things like #510 without noticing before @dankamongmen, I'd love to have it tested by CI against latest stable notcurses and then set to "required".

Maybe `xvfb` (framebuffer X display server) could be used.

### Basic idea

```
Xvfb :99 &
export DISPLAY=:99
$build_dir/src/contour/contour /path/to/notcurses-demo
```

This should be using either Debug or RelWithDebInfo build mode.
Ideally it could be run in to run-modes, once bare, and in another test via ASAN or valgrind. The latter would severaly  increase test times however.

### How to take screenshots

```
xwd -display :99 -root -silent | convert xwd:- png:/tmp/screenshot.png
```

**Comment by christianparpart** [comment]
![image](https://user-images.githubusercontent.com/56763/142721010-4c6035b3-7a9e-43a2-ad7b-2eb84647878d.png)

@dankamongmen damn, man. why the heck can't I get contour to crash on CI :-D

I'll continue investigating. (I could repro it locally, so i'll work on it)

**Comment by dankamongmen** [comment]
when i have problems that do/don't show up in CI vs interactive use, the problem almost always comes down to:

* `TERM`/`LANG` settings within ci, or
* the fact that ci has input/output redirected

**Comment by christianparpart** [comment]
> when i have problems that do/don't show up in CI vs interactive use, the problem almost always comes down to:
> 
>     * `TERM`/`LANG` settings within ci, or

🙇‍♂️

**Comment by christianparpart** [comment]
We have notcurses-demo CI job for each little demo to be run in valgrind even. Nice. Now I just need to fix the findings (lol).
