### ISSUE TITLE
Crash when PM (privacy message) sequence is output

### ISSUE THREAD

**Issue by j4james** [contour-terminal/contour#513]
## Description

If I output a simple PM sequence, Contour crashes with a `std::out_of_range` error.

## Environment

- Contour Version or Git commit hash: 0.3.0-unreleased
- Operating System (name / distribution / version): Ubuntu 21.04
- Contour configuration: 
- TERM environment variable: xterm-256color
- Compiler version:

## Steps to Reproduce

From a bash shell execute the following:
```
printf "\e^X"
```

Contour crashes with the following error message:
```
terminate called after throwing an instance of 'std::out_of_range'
  what():  array::at: __n (which is 15) >= _Nm (which is 15)
Aborted (core dumped)
```

**Comment by j4james** [comment]
It looks like an SOS (start of string) sequence will trigger it too:
```
printf "\eXY"
```

**Comment by christianparpart** [comment]
Oh nice catch. I know I was simply mapping the [DEC VT parser FSM](https://vt100.net/emu/dec_ansi_parser) and later on improved on it a bit.

I never touched PM, so I tried to google a bit about it but severely failed. What did you use/test it for? How can I find out more about PM? (just read your SOS comment, will investigate).

**Comment by j4james** [comment]
This wasn't an app or anything like that. I was just running some random string sequence tests on the terminals I have installed to see how different implementations handle them. I doubt anyone is likely to be using these sequences for real, so there's no urgency to fix this.

**Comment by j4james** [comment]
> How can I find out more about PM?

If you look at that state diagram, you can see that PM and SOS should be handled exactly the same way as APC (which doesn't seem to have this problem).

**Comment by christianparpart** [comment]
yes, I was splitting something apart I can remember. Before I'm getting the "it's not working"-label, I better fix that (over the weekend).

Many thanks for the report @j4james :)
