### ISSUE TITLE
[Windows] Contour silently closes if the configured shell cannot be started

### ISSUE THREAD

**Issue by whisperity** [contour-terminal/contour#519]
## Description

If the `shell` configuration variable in the profile refer to a shell that cannot be started, Contour just closes immediately without opening a window.

## Environment

- Contour Version or Git commit hash: https://github.com/contour-terminal/contour/releases/tag/v0.2.2.175
- Operating System (name / distribution / version): Windows 10 20.04

## Steps to Reproduce

 1. Use your Linux-y Contour profile on Windows which says `/bin/zsh` is your default shell.
 2. Double-click `contour.exe`
 3. The cursor changes to the "semi-busy" icon, but then goes back to normal immediately. The spawned process exits. No error message is generated.

**Comment by Yaraslaut** [comment]
I suppose this is fixed now, this is what i see when run contour with wrong shell
![image](https://user-images.githubusercontent.com/44506630/235080582-cc2efa62-5124-48ac-9251-be6bd6bb55ea.png)

**Comment by whisperity** [comment]
Is that on Windows?

And hey, it's still saying `Success`. :joy:

**Comment by Yaraslaut** [comment]
> Is that on Windows?
> 
> And hey, it's still saying `Success`. 😂

I checked on linux first, on windows issue is still present. Here is stderr of contour while shell does not exist 
```
Unhandled exception for event 14: Resize
?event@TerminalWidget@display@contour@@UEAA_NPEAVQEvent@@@Z: Unhandled exception caught (class std::runtime_error). Could not create process. The system
cannot find the file specified.
```
and contour itself just opens in zombie state
