### ISSUE TITLE
Builtin support for progress bar box drawing (inspired by Fira Code)

### ISSUE THREAD

**Issue by christianparpart** [contour-terminal/contour#521]
For reference: https://github.com/tonsky/FiraCode/issues/1182

Fira Code actually had an amazing idea of making progress bars pretty. We could get users to make use of these code points even though their fonts do not support it.

**Comment by WSLUser** [comment]
If you were using XAML, I'd say you could easily set up progress bars as that's what WT did, though that also makes them accept all the bugs with it too and there are a couple still out there on the WinUI repo. But since you're using QT, I'd wonder how another QT based terminal does it, if it's supported by the terminal. 

Or are you looking to do it in the client drawing area, not the UI? That would explain wishing to do similar to FiraCode.

**Comment by uspasojevic96** [comment]
> If you were using XAML, I'd say you could easily set up progress bars as that's what WT did, though that also makes them accept all the bugs with it too and there are a couple still out there on the WinUI repo. But since you're using QT, I'd wonder how another QT based terminal does it, if it's supported by the terminal.
> 
> Or are you looking to do it in the client drawing area, not the UI? That would explain wishing to do similar to FiraCode.

what does a markup language have to do with framework?

**Comment by christianparpart** [comment]
Oh I think you are misunderstanding something, accidentally. This is about rendering progress bars as part of the grid system, by making codepoints to manually created bitmaps, just like pixel perfect box drawing.

**Comment by WSLUser** [comment]
So not something you'd show in a tab or pane when you eventually have those too then.

**Comment by christianparpart** [comment]
> So not something you'd show in a tab or pane when you eventually have those too then.

<img width="858" alt="image" src="https://user-images.githubusercontent.com/56763/145641573-46ee3e5b-5eed-4907-9138-9fd51fcda37f.png">

These are regular codepoints, just like letters and digets, or box-drawing characters. See the link above :)

**Comment by christianparpart** [comment]
Note to myself: https://github.com/tonsky/FiraCode/issues/1324#issuecomment-985965631

**Comment by christianparpart** [comment]
EE00..EE05 implemented
