### ISSUE TITLE
Colour inversion for terminal cursor

### ISSUE THREAD

**Issue by Utkarsh-khambra** [contour-terminal/contour#526]
## Abstract

When cursor shape is block and cursor is moved over to some character then cursor completely hides the character making it unreadable. 
Currently this happens in contour
![Screenshot from 2021-12-04 13-09-29](https://user-images.githubusercontent.com/29328319/144701843-fed3504e-69fa-4b0a-9baa-0c0e5302743c.png)
and this is in alacritty
![Screenshot_2021-12-04_13-13](https://user-images.githubusercontent.com/29328319/144701929-3e6e024f-f0ef-4edb-9867-c9d69c37bcac.png)

 
## Motivation

Whenever cursor is moved to some character, the background cell color and text color can be inverted. Alacritty also does this by allowing to set 
```yaml
  cursor:
    text: CellBackground
    cursor: CellForeground
```
in config file

**Comment by christianparpart** [comment]
Oh yes, let me fix that ASAP. thanks for pushing me. :-)

**Comment by Utkarsh-khambra** [comment]
Thanks :-)

**Comment by christianparpart** [comment]
> ```yaml
>   cursor:
>     text: CellBackground
>     cursor: CellForeground
> ```

I really struggled in accepting the naming scheme of Alacritty, as much as I tried to be in line with their naming scheme to not confuse users, but `cursor.cursor` doesn't sound quite right. I'm not saying I found the best solution though, but here we go. (PR should be merged soon).

**Comment by christianparpart** [comment]
@Utkarsh-khambra this is how you can configure it:

https://github.com/contour-terminal/contour/blob/a008f1383e1c32dffbce7c8e3f504136bf682286/src/contour/contour.yml#L277-L291


While now being merged to master, CI should have created binary packages already also. Otherwise, I think it's time to make another point release. Enjoy.

**Comment by Utkarsh-khambra** [comment]
Thanks it works great now :)
