### ISSUE TITLE
FreeBSD : SIGFPE on changing fonts

### ISSUE THREAD

**Issue by herrhotzenplotz** [contour-terminal/contour#536]
## Description
SIGFPE on startup related to fonts:

## Environment

- Contour Version or Git commit hash: 8e6591605764acee4282b9761bc822fad76b845e
- Operating System (name / distribution / version): `FreeBSD triton.herrhotzenplotz.geek 13.0-RELEASE-p4 FreeBSD 13.0-RELEASE-p4 #6 releng/13.0-n244760-940681634ee: Wed Oct 20 16:21:16 CEST 2021     nico@triton.herrhotzenplotz.geek:/usr/obj/usr/src/amd64.amd64/sys/TRITON13  amd64`
- Contour configuration: change font to 'JetBrains Mono' or 'Termingus'
- TERM environment variable: `xterm-256color`
- Compiler version: 
```console
nico@triton:~/src/contour $ cc --version
FreeBSD clang version 11.0.1 (git@github.com:llvm/llvm-project.git llvmorg-11.0.1-0-g43ff75f2c3fe)
Target: x86_64-unknown-freebsd13.0
Thread model: posix
InstalledDir: /usr/bin
nico@triton:~/src/contour $ 
```

## Steps to Reproduce

Change the font to anything other than the default 'monospace'.
You get a deep stacktrace which isn't helpful at all.

Issue seems to be in `open_shaper.cpp:402 (int computeAverageAdvance(FT_Face _face) noexcept)`:
`FT_Get_Char_Index(_face, i)` never returns an ok code leaving the maxAdvance at 0 causing divisions by zero later.
No idea what's going here, but seems to be related to Freetype2.

**Comment by herrhotzenplotz** [comment]
Just as a side note, the error code from freetype is very creative : `0xdb`. Upon which FT_Error_String returns a null pointer.

**Comment by uspasojevic96** [comment]
Looking at this (https://github.com/golang/freetype/blob/e2365dfdc4a05e4b8299a783240d4a7d5a65d4e4/truetype/opcodes.go#L231) it makes sense why it's null pointer
