### ISSUE TITLE
Can't input '{' or '}'

### ISSUE THREAD

**Issue by rhcher** [contour-terminal/contour#552]
### Contour Terminal version

0.2.3.182

### Installer source

I download contour-0.2.3.182-win64.msi and install in my windows.
GitHub: release page

### Operating System

Windows 11

### Architecture

x86-64

### Steps to reproduce

Just open contour and input '{' or '}' and nothing happened.

### Expected Behavior

'{' or '}' appears on the screen.

### Actual Behavior

Nothing appears on the srceen.

### Additional notes

Only '{' and '}' has this issue, The rest of the characters work fine (At least in my limited testing). This bug has nothing to do with wsl2, as it also appears in powershell.

**Comment by uspasojevic96** [comment]
Hi, can you check the `contour.yml` file and change the bindings for these 2 options:

```yml
    - { mods: [Shift],          key: '{',           action: ScrollMarkUp,   mode: "~Alt"}
    - { mods: [Shift],          key: '}',           action: ScrollMarkDown, mode: "~Alt"}
```

**Comment by rhcher** [comment]
It's works when I comment that two lines.
