### ISSUE TITLE
Ubuntu 20.04 missing dependency

### ISSUE THREAD

**Issue by trappedinspacetime** [contour-terminal/contour#563]
First of all, I congratulate you on your project.
I am on Ubuntu 20.04 platform. I cloned this repo and tried to build it via 

        dpkg-buildpackage -rfakeroot -b -uc -us

but I got the following dependency error:        
        
        CMake Error at cmake/ThirdParties.cmake:82 (find_package):
          By not providing "Findtermbench-pro.cmake" in CMAKE_MODULE_PATH this
          project has asked CMake to find a package configuration file provided by
          "termbench-pro", but CMake did not find one.
        
          Could not find a package configuration file provided by "termbench-pro"
          with any of the following names:
        
            termbench-proConfig.cmake
            termbench-pro-config.cmake
        
          Add the installation prefix of "termbench-pro" to CMAKE_PREFIX_PATH or set
          "termbench-pro_DIR" to a directory containing one of the above files.  If
          "termbench-pro" provides a separate development package or SDK, be sure it
          has been installed.
        Call Stack (most recent call first):
          CMakeLists.txt:81 (include)
        
        
I attempted to build and install   https://github.com/contour-terminal/termbench-pro but I hit a `fmt` bug https://github.com/contour-terminal/contour/issues/189
I tried to work around that bug by replacing  `fmt::fmt-header-only` with `fmt::fmt`. It's built finally but `Makefile` won't install the library.

How can I build it from sorce on Ubunto 20.04?

**Comment by herrhotzenplotz** [comment]
Did you install the embedded libraries? See `scripts/install-deps.sh`

**Comment by christianparpart** [comment]
There are also two ways to create a .deb package file. The one you are using is what I use for creating PPA builds. This requires pre-fetching the embedded dependencies, so yes, best choice is to invoke `scripts/install-deps.sh`.

The second way to create a .deb package file is to use CMake's provided `cpack` tool for it. Both ways are used by CI.

So depending on your usecase, you might also want to simply grab the latest stable(?) release from the github release page that contains as many prebuilt packages as possible (so far).

We could however improve the documentation to reflect the today's state of the building & packaging procedures.

Happy Xmas-days ;)

**Comment by trappedinspacetime** [comment]
@herrhotzenplotz After running `scripts/install-deps.sh` it finished building successfully. But when I launch it, it crashes with the following error:

          [error] Compiling vertex shader builtin.text.vert failed. 0:1(10): error: GLSL 3.30 is not supported. Supported versions are: 1.10, 1.20, and 1.00 ES
          
GL version in my laptop:

                   OpenGL version string: 2.1 Mesa 21.0.3
                   
@christianparpart     Happy Xmas!

**Comment by herrhotzenplotz** [comment]
> OpenGL version string: 2.1 Mesa 21.0.3

This looks like, despite you having installed a relatively recent version of Mesa, it doesn't have support for more recent OpenGL versions. You may wanna check that your version of Qt is linking against the correct mesa libraries and that Qt is picking up the correct versions of mesa.

what I've got here:

```console
$ build/src/contour/contour debug gui.display
<snip>
[gui.display:TerminalWidget.cpp:350] [FYI] OpenGL type     : OpenGL
[gui.display:TerminalWidget.cpp:353] [FYI] OpenGL renderer : Radeon RX 580 Series (POLARIS10, DRM 3.35.0, 13.0-RELEASE-p4, LLVM 12.0.1)
[gui.display:TerminalWidget.cpp:354] [FYI] Qt platform     : xcb
[gui.display:TerminalWidget.cpp:360] [FYI] OpenGL version  : 4.6
[gui.display:TerminalWidget.cpp:385] [FYI] GLSL version    : 4.60 (460, 450, 440, 430, 420, 410, 400, 330, 150, 140, 130, 120, 320 es, 310 es, 300 es, 100)
<snip>
```
Important here is the the versions of opengl and glsl.

```console
$ ldd build/src/contour/contour
build/src/contour/contour:
	libyaml-cpp.so.0 => /usr/local/lib/libyaml-cpp.so.0 (0x80044e000)
	libQt5Network.so.5 => /usr/local/lib/qt5/libQt5Network.so.5 (0x8004a5000)
	libQt5Widgets.so.5 => /usr/local/lib/qt5/libQt5Widgets.so.5 (0x800800000)
	libdl.so.1 => /usr/lib/libdl.so.1 (0x800690000)
	libfreetype.so.6 => /usr/local/lib/libfreetype.so.6 (0x800694000)
	libharfbuzz.so.0 => /usr/local/lib/libharfbuzz.so.0 (0x800ea8000)
	libfontconfig.so.1 => /usr/local/lib/libfontconfig.so.1 (0x80075b000)
	libQt5Gui.so.5 => /usr/local/lib/qt5/libQt5Gui.so.5 (0x800f9a000)
	libQt5Core.so.5 => /usr/local/lib/qt5/libQt5Core.so.5 (0x801600000)
	libc++.so.1 => /usr/lib/libc++.so.1 (0x801b48000)
	libcxxrt.so.1 => /lib/libcxxrt.so.1 (0x8007a9000)
	libm.so.5 => /lib/libm.so.5 (0x8007cc000)
	libc.so.7 => /lib/libc.so.7 (0x801c33000)
	libz.so.6 => /lib/libz.so.6 (0x802044000)
	libGL.so.1 => /usr/local/lib/libGL.so.1 (0x80224d000)
	libGLdispatch.so.0 => /usr/local/lib/libGLdispatch.so.0 (0x802c0d000)
	libGLX.so.0 => /usr/local/lib/libGLX.so.0 (0x802cc5000)
...
$ pkg info qt5-gui
qt5-gui-5.15.2_7
Name           : qt5-gui
Version        : 5.15.2_7
Installed on   : Wed Oct 20 16:34:12 2021 CEST
Origin         : x11-toolkits/qt5-gui
Architecture   : FreeBSD:13:amd64
Prefix         : /usr/local
Categories     : x11-toolkits graphics
Licenses       : LGPL21
Maintainer     : kde@FreeBSD.org
WWW            : https://www.qt.io/
Comment        : Qt graphical user interface module
Options        :
	X11            : on

```

I have the slight suspicion that the versions on Ubuntu are a little outdated and/or picking up old stuff by accident.

**Comment by trappedinspacetime** [comment]
@herrhotzenplotz 

`apt-cache show qt5-default`
        Package: qt5-default
        Architecture: amd64
        Version: 5.12.8+dfsg-0ubuntu1
        Multi-Arch: same
        Priority: optional
        Section: universe/libs
        Source: qtbase-opensource-src
        Origin: Ubuntu
My laptop is pretty old and doesn't have a decent GPU. Could it be the cause of the crash?

**Comment by christianparpart** [comment]
It seems you are having a very old graphics card... which one? Did you try to enforce Mesa software rendering using:

```sh
export LIBGL_ALWAYS_SOFTWARE=true
contour ...
```

If that works, I think we should consider adding that as a configuration option.

**Comment by trappedinspacetime** [comment]
@christianparpart `export LIBGL_ALWAYS_SOFTWARE=true` works. I should have thought of it. I used to add that environment variable to run `google-earth` program. 
Thank you for your help.
Regards.

**Comment by christianparpart** [comment]
@trappedinspacetime I'll still make that a configuration option as linked in the PR above, so that users don't have to always prefix/export that environment variable when wanting to use Contour.

But you are certainly not the only one having an ancient GPU (pre OpenGL 3), so we should make sure that's auto-detected and working out-of-the-box in these cases without additional work, too.

**Comment by uspasojevic96** [comment]
Can we close this issue and create new one for `LIBGL_ALWAYS_SOFTWARE`?

**Comment by christianparpart** [comment]
Oh yes we can close this. We don't need to create a new one as I already implemented a config option for that in `contour.yml`.
