### ISSUE TITLE
contour replies to all XTGETTCAP with FFFFFF

### ISSUE THREAD

**Issue by dankamongmen** [contour-terminal/contour#582]
### Contour Terminal version

0.3.0-unreleased-master-f764fb6f

### Installer source

Github: source code cloned

### Operating System

Debian Linux Unstable

### Architecture

x86-64

### Other Software

notcurses 3.0.5-prerelease

### Steps to reproduce

echo -e '\eP+q687061\e\\'

### Expected Behavior

` :0+r^[\` if `hpa` is unsupported
`:1+r687061=5c455b2569257031256447^[\` (or something similar) if it is

### Actual Behavior

`:1+r687061=FFFFFFFF^[\`

### Additional notes

this seems to be returned for all XTGETTCAP requests.

this now causes a problem, because notcurses 3.0.5 will be pulling `hpa`'s definition from XTGETTCAP if it's defined there. technically, FF would be an invalid byte, since there should not be any bigger than 7F, so i can ignore this and throw it out. you probably want to fix it, though.

**Comment by christianparpart** [comment]
Oh sorry @dankamongmen . I will have that fixed by tonight.

**Comment by christianparpart** [comment]
I had tcap generally unit tested. but apparently not enough. I'll merge the fix ASAP.

**Comment by christianparpart** [comment]
"commented yesterday" ... WHAT? And I just noticed this afternoon? Sorry....
