### ISSUE TITLE
0.3.0: Crash on SU with horizontal margins

### ISSUE THREAD

**Issue by ninjalj** [contour-terminal/contour#593]
### Contour Terminal version

0.3.0-unreleased-v0.2.3.182-160-g21c4dab7-21c4dab7

### Installer source

Github: source code cloned

### Operating System

Linux

### Architecture

x86-64

### Steps to reproduce

echo -e "\e[?69h\e[4;74s\e[20S"

### Actual Behavior

[/home/lj/src/term/contour/src/terminal/Grid.cpp:192] Precondition failed. *_line < *pageSize_.lines

An internal error caused the terminal to crash ;-( 😭
-------------------------------------------------------

Please report this to https://github.com/contour-terminal/contour/issues/

Contour version: 0.3.0-unreleased-v0.2.3.182-160-g21c4dab7-21c4dab7

Stack Trace:
------------
/home/lj/src/term/contour/src/crispy/StackTrace.cpp:90
/home/lj/src/term/contour/src/crispy/StackTrace.cpp:218
/home/lj/src/term/contour/src/contour/ContourApp.cpp:105
/home/lj/src/term/contour/src/contour/ContourApp.cpp:119
0x7fb047dbcbd0
0x7fb047dbcb24
0x7fb047da6557
/home/lj/src/term/contour/src/crispy/assert.h:54
/home/lj/src/term/contour/src/crispy/assert.h:61
/home/lj/src/term/contour/src/terminal/Grid.cpp:192
/home/lj/src/term/contour/src/terminal/Grid.cpp:211
/home/lj/src/term/contour/src/terminal/Grid.cpp:206
/home/lj/src/term/contour/src/terminal/Grid.cpp:449 (discriminator 3)
/home/lj/src/term/contour/src/terminal/Screen.cpp:1109
/home/lj/src/term/contour/src/terminal/Screen.cpp:1117
/home/lj/src/term/contour/src/terminal/Screen.h:531
/home/lj/src/term/contour/src/terminal/Sequencer.cpp:1523
/home/lj/src/term/contour/src/terminal/Sequencer.cpp:1308
/home/lj/src/term/contour/src/terminal/Sequencer.cpp:1299
/home/lj/src/term/contour/src/terminal/Sequencer.cpp:1063
/home/lj/src/term/contour/src/terminal/Parser-impl.h:355
/home/lj/src/term/contour/src/terminal/Parser-impl.h:321
/home/lj/src/term/contour/src/terminal/Screen.cpp:563
/home/lj/src/term/contour/src/terminal/Terminal.cpp:749
/home/lj/src/term/contour/src/terminal/Terminal.cpp:231
/home/lj/src/term/contour/src/terminal/Terminal.cpp:191
/usr/lib/gcc/x86_64-pc-linux-gnu/11.2.0/include/g++-v11/bits/invoke.h:74 (discriminator 4)
/usr/lib/gcc/x86_64-pc-linux-gnu/11.2.0/include/g++-v11/bits/invoke.h:97
/usr/lib/gcc/x86_64-pc-linux-gnu/11.2.0/include/g++-v11/functional:422
/usr/lib/gcc/x86_64-pc-linux-gnu/11.2.0/include/g++-v11/functional:505
/usr/lib/gcc/x86_64-pc-linux-gnu/11.2.0/include/g++-v11/bits/invoke.h:61
/usr/lib/gcc/x86_64-pc-linux-gnu/11.2.0/include/g++-v11/bits/invoke.h:97
/usr/lib/gcc/x86_64-pc-linux-gnu/11.2.0/include/g++-v11/bits/std_thread.h:253
/usr/lib/gcc/x86_64-pc-linux-gnu/11.2.0/include/g++-v11/bits/std_thread.h:260
/usr/lib/gcc/x86_64-pc-linux-gnu/11.2.0/include/g++-v11/bits/std_thread.h:211
0x7fb04817cf54
0x7fb049062e9e
0x7fb047e7f86f

**Comment by christianparpart** [comment]
Hey. Oh yes. Many thanks. I will try to fix that ASAP.
