### ISSUE TITLE
default config's color scheme should respect dark/light mode OS settings

### ISSUE THREAD

**Issue by christianparpart** [contour-terminal/contour#604]
Windows and OSX have it. And at least KDE version 5.24 has it too .

The default color scheme from there default config should respect that setting and pick some appropriate colors.

**Comment by christianparpart** [comment]
I actually wonder. How can we find out if KDE is currently in dark color mode or in light color mode?

Also, we currently only support specifying _one_ color scheme, regardless of the OS dark/light mode settings.
We should probably tag colorschemes as dark or light (could be inferred by default background color maybe?) and allow the user either explicitly set one color scheme or explicitly one for each mode (dark/light OS color mode).

-> We could then adjust the color theme live as soon as the OS decided to go dark/light mode.

**Comment by uspasojevic96** [comment]
https://doc.qt.io/qt-5.15/qtquickcontrols2-universal.html

**Comment by christianparpart** [comment]
I also googled around a bit and found this:

```sh
dbus-send \
    --session --print-reply=literal --reply-timeout=1000 \
    --dest=org.freedesktop.portal.Desktop \
    /org/freedesktop/portal/desktop \
    org.freedesktop.portal.Settings.Read \
    string:'org.freedesktop.appearance' \
    string:'color-scheme'
```

We could initially read and then watch on change events on that setting and act accordingly (Not sure how to do that in C++, but most likely QtDbus would probably do the most work for us on that one already.

**Comment by christianparpart** [comment]
> https://doc.qt.io/qt-5.15/qtquickcontrols2-universal.html

I really like that one, the accent color could be used for selection.

So we could extend color schemes to make use of accent colors by specifying the string "accent" rather than a hex code. That could be used for things like selection colors etc. We'd need a way to say something like `mix(accent, ...)` to allow variations. But making use of accent colors should be its own ticket I think :)
