### ISSUE TITLE
Support visual bell

### ISSUE THREAD

**Issue by christianparpart** [contour-terminal/contour#61]
### Checklist:

* [ ] Screen: adjusted relevant code parts (enable/disable bell? adjust bell audio volume?)
* [ ] aeroterm: visualizes bell (at least one mode: hard start, smooth fading out)
* [ ] aeroterm: also consider:[ `glfwRequestWindowAttention(window);`](https://www.glfw.org/docs/latest/window_guide.html#window_attention)

**Comment by Yaraslaut** [comment]
Bell is implemented and configurable, i am closing this one
