### ISSUE TITLE
resize on alt screen sometimes causes assertion failure

### ISSUE THREAD

**Issue by christianparpart** [contour-terminal/contour#610]
Repro: go into tmux (or any alt-buffer app?) and have the tmux pane non-empty (e.g. `dmesg -w`), then toggle maximize window a few times until assertion failure happens

File Grid.cpp line 153: `(totalLineCount() >= linesUsed_)`

**Comment by Yaraslaut** [comment]
Also, crash file is empty after this error, don't know about another errors, but would expect it to contain some info

**Comment by christianparpart** [comment]
This might be fixed by PR #628.

**Comment by Yaraslaut** [comment]
> This might be fixed by PR #628.

Fixed for me
