### ISSUE TITLE
White one-pixel border on right and bottom

### ISSUE THREAD

**Issue by herrhotzenplotz** [contour-terminal/contour#620]
I remember that I have seen some discussion related to this, but haven't found the issue/PR. So maybe this is a regression or a duplicate.

Anyways:

```
nico@triton:~/src/contour $ uname -onr; freebsd-version; git log --oneline | sed 1q;
FreeBSD triton.herrhotzenplotz.de 13.0-RELEASE-p6
13.0-RELEASE-p6
f6d6375a [contour] contour.yml: Fixes default for on_mouse_select.
nico@triton:~/src/contour $
```

I think the screenshot shows the white border pretty well:

![2022-03-10-104012_1454x906_scrot](https://user-images.githubusercontent.com/34663024/157637335-97489f38-5824-4e7c-a7c6-24ab56ea186a.png)

This is with i3 (thus X11).

Also, I looked into the problem with gammaray and see the issue being that the `contour::opengl::TerminalWidget` has a width that is off by one pixel compared to its parent `contour::ScrollableDisplay`.

**Comment by herrhotzenplotz** [comment]
Looking into this after some gdb work and then turning on some logging I can see the following weirdness:

```console
[2022-03-11 18:08:57.431594] [gui.display] called with 654x450 in main
[2022-03-11 18:08:57.431606] [gui.display] Scrollbar Pos: Hidden
[2022-03-11 18:08:57.431824] [gui.display] contentScale: 1
[2022-03-11 18:08:57.431841] [gui.display] resizeGL: 653x449 (653x449)
[2022-03-11 18:08:57.431850] [gui.display] setRenderSize: 653x449
[2022-03-11 18:08:57.435884] [gui.display] execute: 653x449
[2022-03-11 18:08:57.435930] [gui.display] TW 0x0+653x449, SB invisible, 0x0+14x450, value: 0/0
[2022-03-11 18:08:57.435963] [gui.display] TerminalWindow.resizeEvent: size 654x450 (654x450)
[2022-03-11 18:08:57.438414] [gui.display] contentScale: 1
[2022-03-11 18:08:57.438432] [gui.display] sizeHint: 640x450 (640x450)
```

In `contour::ScrollableDisplay::resizeEvent` with a hidden scrollbar, the Widget's `height()` and `width()` return e.g. `654x450`. However, the call to `contentsRect();` (ScrollableDisplay.cpp:126) returns a rectangle that is exactly one pixel off. I have no clue why.

To confirm that this is indeed the issue, I made the following changes:

```diff
diff --git a/src/contour/ScrollableDisplay.cpp b/src/contour/ScrollableDisplay.cpp
index b0445774..5a810f3f 100644
--- a/src/contour/ScrollableDisplay.cpp
+++ b/src/contour/ScrollableDisplay.cpp
@@ -123,8 +123,7 @@ void ScrollableDisplay::updatePosition()
             break;
         case config::ScrollBarPosition::Hidden: {
             scrollBar_->hide();
-            auto const cr = contentsRect();
-            mainWidget_->resize(cr.right(), cr.bottom());
+            mainWidget_->resize(width(), height());
             mainWidget_->move(0, 0);
             break;
         }
```

And it fixes the issue. I don't know whether this is a hack or it is wrong or if it breaks hidpi things. Feedback would be appreciated :-)

**Comment by christianparpart** [comment]
Hey @herrhotzenplotz. Sorry for the huge delay. I didn't mean to. I'll ... oh, wow. you even provided a fix already. You've been quicker. Many thanks. :-)
