### ISSUE TITLE
Unexpected behavior of selections

### ISSUE THREAD

**Issue by herrhotzenplotz** [contour-terminal/contour#641]
A little bit of a long one, however I tend to use these quite
often. Most likely this only concerns X11.

Comparing to both rxvt-unicode and xterm I see the following three
inconsistencies when making selections with your mouse:

### Steps to reproduce

1. Type a random command (e.g. ls -lap)
2. Select something from the beginning of a line
3. Hit the middle mouse button to paste it back

### Observed

A new-line character and then the selected text is printed.

### Expected

Only the selected text without the new-line character is printed.

### Steps to reproduce

1. Double click and hold on a word to make a selection, then move the
   mouse cursor beyond the last word of the same line such that the
   selection snaps to the end of the line.
2. Hit the middle mouse button to paste back.

### Observed

Only the selected text is printed.

### Expected

The selected text and a new-line character is printed such that the
pasted command gets run by the shell.

### Steps to reproduce

1. Hold and select a command and move the mouse cursor beyond the last
   word of a line until its end.
2. Paste back using the middle-mouse button.

### Observed

The selection continues cell-by-cell after the last word. A new-line
is not printed.

### Expected

The selection snaps to the end of the line once the last word has been
passed. It should also print the new-line character such that the
selected command is run by the shell.

**Comment by christianparpart** [comment]
This is indeed not nice. We noticed that one too recently and I will check that and have that fixed before the next release (ASAP so I hope)

**Comment by christianparpart** [comment]
Update: leading LF when copying out a selection is just fixed on master.

**Comment by mirsemen** [comment]
./contour --version
Contour Terminal Emulator 0.3.1-unreleased-master-503f917b

When the command line is at the very bottom of the terminal - selection occurs without problems.
![Screenshot-OK](https://user-images.githubusercontent.com/51527012/164958939-3822eda5-08d1-4af4-81fe-fd84ebee0a10.png)


When it is necessary to scroll the terminal up a little, the selection is shifted down relative to the position of the mouse pointer. And the higher you scroll, the greater the distance from the mouse cursor to the selection.
![Screenshot-ERROR](https://user-images.githubusercontent.com/51527012/164958859-b400c656-9a09-47dc-9ac7-d9d170774fd9.png)

**Comment by christianparpart** [comment]
Tiny checklist for myself of things that are left (IMHO)

- [ ] line-based selection should include trailing linefeed (to match behaviour of Xterm and others)
- [ ] selecting past the last filled character in a line should snap to the end of that line
- [ ] selection rendered wrong when viewport is scrolled.

**Comment by christianparpart** [comment]
@herrhotzenplotz how urgent is the mittle item in my list of the comment above? ("selecting past the last filled character in a line should snap to the end of that line")?

Everything else is now addressed, or am I missing anything?

**Comment by herrhotzenplotz** [comment]
> @herrhotzenplotz how urgent is the mittle item in my list of the comment above? ("selecting past the last filled character in a line should snap to the end of that line")?

Tbh, when I am doing admin and config work, this is one of the things I use very often to copy commands etc.
For me personally it is quite urgent, for others it may not be.

> Everything else is now addressed, or am I missing anything?

Looks good to me :+1:

**Comment by data-man** [comment]
The addition: tripple clicking adds `\n`.

**Comment by Yaraslaut** [comment]
I checked and bugs are fixed now, 
one thing though that can be implemented in the future is execution of the pasted text. I will create a new issue for this and close this one
