### ISSUE TITLE
Unexpected internal error if specifying invalid command line option

### ISSUE THREAD

**Issue by kumattau** [contour-terminal/contour#647]
### Contour Terminal version

0.3.0.198

### Installer source

GitHub: release page

### Operating System

Ubuntu Linux 20.04

### Architecture

x86-64

### Steps to reproduce

Invalid option is specified. For example,

```
contour -V
```

### Expected Behavior

Error message is shown without internal error.
At the same time, it is better to output how to display help or the help itself.

### Actual Behavior

Error message is shown with internal error.

![image](https://user-images.githubusercontent.com/171798/164017401-f1cca23d-70c3-48d7-8bdd-a61a9b2aa3a1.png)

### Additional notes

I noticed this when I tried to display the version with -V.
I think application should validate user's specified options and shows only appropriate message without internal error if the options are invalid.

This problem occurs in the current latest commit 0cf97cb9d98854343ed113058c0e9c841481bd00

**Comment by christianparpart** [comment]
@kumattau I just wanted to mention, the version can be taken via `contour version` and help via `contour help`. We do support longopt-style syntax, so one might want to write `contour --version` and `contour --help`, too. Short-opts are currently not supported. On purpose actually. But that may change. I'm not hard'ly opinionated here. :)

**Comment by kumattau** [comment]
@christianparpart 
Thank you for the usage.
My point was not about usage, but that internal errors should not be reported when options are incorrectly specified.
I tried https://github.com/contour-terminal/contour/commit/720303ec73c1b85d814887e6796bc0b618622931 but there does not appear to be a fix for this yet.
Of course, it depends on the application's error handling policy, so I respects the answer if current error handing is in accordance with the specification of this software.

![image](https://user-images.githubusercontent.com/171798/164942804-072056c3-19e6-460b-9b61-4b0a1cd995be.png)

**Comment by christianparpart** [comment]
The error is to appear in the window. That part is right. But it should be a user targeted error message, and not an internal error. I was sure I fixed that and checked it locally. I will revisit (As soon as I am awake enough) :)
