### ISSUE TITLE
selecting past the last filled character in a line should snap to the end of that line

### ISSUE THREAD

**Issue by christianparpart** [contour-terminal/contour#665]
Selecting past the last filled character in a line should snap to the end of that line

Emerging out of #641 to explicitly address this one item. /cc @herrhotzenplotz 

I initially planned to address this one for 0.3.1, but I'd prefer to release 0.3.1 as early as possible, so it might be 0.3.2 instead, FYI.

**Comment by Utkarsh-khambra** [comment]
I was thinking of working on this. Did mean cursor snapping like this?

https://user-images.githubusercontent.com/29328319/170099037-a4aba322-6cb8-4006-8629-0fa0304cc095.mp4

**Comment by christianparpart** [comment]
Hey. Exactly like that. I think that is also how other TEs (most?) are doing it. Wasn't it something you initially requested on Discord, or am I mixing something up here? Also, sorry for my late absence, I'm mentally occupied with real-life. That'll be sorted out ASAP I hope. :)

**Comment by Utkarsh-khambra** [comment]
No I didn't. I'll do now.
