### ISSUE TITLE
Can't find explorer.exe in WSL2 in contour

### ISSUE THREAD

**Issue by rhcher** [contour-terminal/contour#671]
### Contour Terminal version

master

### Installer source

Github: source code cloned

### Operating System

wsl2 Arch

### Architecture

x86-64

### Steps to reproduce

1. open contour
2. input `explorer.exe .`

### Expected Behavior

open Windows Explorer.exe

### Actual Behavior

zsh: command not found: explorer.exe

### Additional notes

The Windows Terminal work well, and I guess it's because 1c68d6e0e3bf11aa53af6447b16344fc7dace66c

**Comment by uspasojevic96** [comment]
Hello, thanks for reporting this, can you tell me what is the output of `echo $PATH`?

**Comment by rhcher** [comment]
> Hello, thanks for reporting this, can you tell me what is the output of `echo $PATH`?

/home/rhcher/.opam/cs3110-2021fa/bin:/home/rhcher/.local/share/zinit/polaris/bin:/home/rhcher/.nix-profile/bin:/home/rhcher/.emacs.d/.local/e
tc/lsp/mspyls:/home/rhcher/.cargo/bin:/home/rhcher/.emacs.d/bin:/home/rhcher/.cargo/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sb
in:/bin:/usr/games:/usr/local/games:/usr/lib/wsl/lib:/mnt/f/software/contour/build/src/contour/Release:/home/rhcher/.dotnet/tools:/usr/lib/jv
m/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl

**Comment by uspasojevic96** [comment]
You are missing `/mnt/c/WINDOWS` in your `PATH` that is why, please check your `.profile` or `.zprofile` or `.zshrc` in case you override whole `PATH` since WSL by default presets that for you

**Comment by rhcher** [comment]
> You are missing `/mnt/c/WINDOWS` in your `PATH` that is why, please check your `.profile` or `.zprofile` or `.zshrc` in case you override whole `PATH` since WSL by default presets that for you

Yeah you are right and it works as expected after I add that path by hand. Thank you for your help.
