### ISSUE TITLE
in midnight commander, F[0..9] keys, PgDn and PgUp etc are not working

### ISSUE THREAD

**Issue by al-zatv** [contour-terminal/contour#675]
### Contour Terminal version

Contour Terminal Emulator 0.3.1-unreleased-master-9dbc4d23

### Installer source

Github: source code cloned

### Operating System

ubuntu 20.04 (Linux al-UX310UQ 5.13.0-40-generic #45~20.04.1-Ubuntu SMP Mon Apr 4 09:38:31 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux)

### Architecture

x86-64

### Other Software

midnight commander from ubuntu 20.04:

$ mc --version
GNU Midnight Commander 4.8.24
Built with GLib 2.63.3
Using the S-Lang library with terminfo database
With builtin Editor and Aspell support
With subshell support as default
With support for background operations
With mouse support on xterm and Linux console
With support for X11 events
With internationalization support
With multiple codepages support
Virtual File Systems: cpiofs, tarfs, sfs, extfs, ext2undelfs, ftpfs, sftpfs, fish
Data types: char: 8; int: 32; long: 64; void *: 64; size_t: 64; off_t: 64;

### Steps to reproduce

1)run contour
2)run mc
3)press PgDn 

### Expected Behavior

selection goes one page down:)

### Actual Behavior

... nothing:)

**Comment by uspasojevic96** [comment]
What is the value of your `TERM`? I can't seem to reproduce it

**Comment by christianparpart** [comment]
What is your TERM environment charitable?

**Comment by al-zatv** [comment]
vt100
I don't set it -- it was set by default.

**Comment by al-zatv** [comment]
Thank you, I set contour term somehow, now F1-F10, PgUp,PgDn are working. But Ctrl+O is not working (ctrl+x s is working,though). What can it be?

**Comment by uspasojevic96** [comment]
Open up your config `$HOME/.config/contour/contour.yml` and change `OpenFileManager` keybind

**Comment by al-zatv** [comment]
btw, when I press Ctrl+O in contour, in parent terminal for contour I see a message:

[error] Could not open file "".

(probably, it's content of contour's stderr file).
I use Ctrl+O to switch to console view in mc, not to open something.

**Comment by christianparpart** [comment]
> btw, when I press Ctrl+O in contour, in parent terminal for contour I see a message:
> 
> [error] Could not open file "".
> 
> (probably, it's content of contour's stderr file). I use Ctrl+O to switch to console view in mc, not to open something.

looks like a cosmetic error. you did not specify a config file explicitly, so hence the empty string (""), defaulting to the standard location at ~/.config/contour/contour.yml. I'll fix that. thanks for the notice. :)

**Comment by al-zatv** [comment]
Thank you! Now it is working!
