### ISSUE TITLE
Cannot start with "Unhandled error caught. Unexpected index"

### ISSUE THREAD

**Issue by kumattau** [contour-terminal/contour#678]
### Contour Terminal version

0.3.2-unreleased-master-db284983

### Installer source

Github: source code cloned

### Operating System

Ubuntu Linux 20.04

### Architecture

x86-64

### Steps to reproduce

```
$ rm -fr build && cmake -s . -B build && cmake --build build
$ ./build/src/contour/contour
```

### Expected Behavior

Contour Terminal Emulator 0.3.1.200 (from github release page deb package) can start.

Note: In my environment, the following message reported but it seems not to relate to this problem.

```
[error] Superfluous config key found: profiles.main.bold_is_bright
[error] Superfluous config key found: profiles.main.cursor
[error] Superfluous config key found: profiles.main.normal_mode.cursor
[error] Superfluous config key found: profiles.main.normal_mode
[error] Superfluous config key found: profiles.main.visual_mode.cursor
[error] Superfluous config key found: profiles.main.visual_mode
```

### Actual Behavior

Contour Terminal Emulator 0.3.2-unreleased-master-db284983 cannot start.

```
[error] Superfluous config key found: profiles.main.bold_is_bright
[error] Superfluous config key found: profiles.main.cursor
Unhandled error caught. Unexpected index% 
```

**Comment by christianparpart** [comment]
i broke it last night. I'm sorry. i'm about to fix that :-)
