### ISSUE TITLE
Weird Light Color On The Line After Cursor

### ISSUE THREAD

**Issue by pegvin** [contour-terminal/contour#696]
### Contour Terminal version

0.3.2-unreleased-master-88e6456f

### Installer source

Yay

### Operating System

Manjaro Linux

### Architecture

x86-64

### Other Software

None

### Steps to reproduce

1. Install Yay or any AUR Package Manager
2. Install [`contour-git`](https://aur.archlinux.org/packages/contour-git) Package (`yay contour-git`)
3. Run The Terminal

### Expected Behavior

This is how the terminal should look like:
![image](https://user-images.githubusercontent.com/75035219/169547528-a94c05a1-469a-48ed-8e64-f9683c17d290.png)

### Actual Behavior

This is how it actually looks:
![image](https://user-images.githubusercontent.com/75035219/169547653-bb56a2b2-c426-44a1-a192-f72c10accd96.png)

### Additional notes

I am using the Bleeding Edge Version of Contour, using the package available on [Arch Linux AUR](https://aur.archlinux.org/packages/contour-git).

I know i am using the Bleeding Edge Version and it may contain bugs, i am raising this issue just to let the developers know.

The problem might be of the prompt i am using: [Powerline Shell](https://github.com/b-ryan/powerline-shell)
But it doesn't occur on other terminals like the xfce4-terminal

### Important
Seems like the problem is with the prompt i am using which is [Powerline shell](https://github.com/b-ryan/powerline-shell) because the default prompt with colors works fine, but powerline-shell prompt works fine on xfce terminal and others too

**Comment by christianparpart** [comment]
Do we actually have some VT sequence to explicitly reproduce this? @pegvin - if that's not too much of a burden, maybe you could run contour passing some logging flags, such as `contour debug pty,pty.input,vt.trace > contour.log`, which will spawn contour as usual, but also log some VT processing. Simply <kbd>Ctrl</kbd>+<kbd>D</kbd> to quit the terminal, then send the contents of the just created `contour.log`-file here as a comment. That would be super-useful.

Many thanks,
Christian.

**Comment by Utkarsh-khambra** [comment]
`printf '^[[22;38;5;250;48;5;240m utkarsh ^[[22;38;5;240;48;5;238m^[[22;38;5;250;48;5;238m fedora ^[[22;38;5;238;48;5;31m^[[22;38;5;15;48;5;31m ~ ^[[22;38;5;31;48;5;236m^[[
22;38;5;15;48;5;236m $ ^[[22;38;5;236m\033[39;49m\n'`

**Comment by christianparpart** [comment]
> ` printf '\033[22;38;5;250;48;5;240m utkarsh \033[22;38;5;240;48;5;238m\033[22;38;5;250;48;5;238m fedora \033[22;38;5;238;48;5;31m\033[22;38;5;15;48;5;31m ~ \033[22;38;5; 31;48;5;236m\033[22;38;5;15;48;5;236m $ \033[22;38;5;236;49m\033[22;39;49m'`

nice, thanks. I can repro that on my installed binary (release build, 0.3.1.200) but not on master 3a79d3f1d8f339a0228d56724656734f407dba96. What's the output of `contour version`?

**Comment by christianparpart** [comment]
Re-closing. Sorry for the unnecessary noise. :)

**Comment by pegvin** [comment]
@christianparpart Firstly Thanks To The Devs The Issue Is Fixed Now, And The Output is:
```bash
[2022-05-27 16:08:35.157673] [pty] PTY opened. master=7, slave=8
[2022-05-27 16:08:35.157863] [pty] stdout fastpipe: reader 9, writer 10
[2022-05-27 16:08:36.765730] [pty.input] master received: "\e[?2004h\e[38;5;15m\e[48;5;8m ~ \e[0m\e[38;5;8m\xee\x82\xb0\e[0m "
[2022-05-27 16:08:40.035097] [pty.input] master received: "\e[?2004l\r\r\n"
[2022-05-27 16:08:40.035588] [pty.input] master received: "exit\r\n"
[2022-05-27 16:08:40.037051] [pty] PTY closing master (file descriptor 7).
```
(I actually updated contour yesterday, to get the patch for the issue, so this might not help)
