### ISSUE TITLE
Keybind / option for read-only / protected mode

### ISSUE THREAD

**Issue by whisperity** [contour-terminal/contour#697]
## Abstract

A new keybind action, perhaps not bound to anything by default, should be added that, when pressed, disable passing input to the underlying programs.

## Motivation

Sometimes I have long-running applications, output I would like to monitor, but I'm scared that pressing ^C will kill potentially hours' worth of computation. Idea taken from KiTTY that has a "Protected" mode: if enabled, you can't interact with the shell (no mouse events or keys are forwarded), and you can't even close the window -- but output is still being refreshed on your side.

**Comment by christianparpart** [comment]
That's a very interesting idea and should be trivial to implement. It should be shown to the user in some way or the other, such that the user won't be disappointed why nothing is happening.

**Comment by whisperity** [comment]
> That's a very interesting idea and should be trivial to implement. It should be shown to the user in some way or the other, such that the user won't be disappointed why nothing is happening.

All KiTTY does is put a `(PROTECTED)` into the title of the window, which is not *quite* enough. My first idea would be to change the running window's icon (I guess that is possible?) to a contour logo with a lock on it? (Get one of the nice coloured lock icons from Wikipedia! :wink: )

But I guess a lock could also be drawn somewhere in the viewport of the window, where it is expected to be unobtrusive. Top right corner?

**Comment by uspasojevic96** [comment]
While I agree that changing some sort of window decoration is nice, but keep in mind that some of us have decorations disabled

**Comment by christianparpart** [comment]
What about changing color scheme when in readonly-mode?

**Comment by christianparpart** [comment]
While the logic itself is trivial to implement, it's probably best to simply wait for #687 to be implemented, such that the visual feedback is easy, too. :)
