### ISSUE TITLE
Resizing window messes up neovim background color

### ISSUE THREAD

**Issue by Utkarsh-khambra** [contour-terminal/contour#706]
### Contour Terminal version

0.3.2-unreleased-master-091f56a3

### Installer source

Github: source code cloned

### Operating System

Fedora Linux 35

### Architecture

x86-64

### Other Software

NeoVim 0.7

### Steps to reproduce

1. Start contour in smaller window.
2. Open some file in nvim.
3. Maximize the contour window.

### Expected Behavior

![Screenshot from 2022-05-29 12-06-39](https://user-images.githubusercontent.com/29328319/170855544-5ac0f310-530c-4c81-820b-41263220d117.png)

### Actual Behavior

![Screenshot from 2022-05-29 12-07-20](https://user-images.githubusercontent.com/29328319/170855565-2bbbd2e9-76ac-4bad-8c17-224b4fb50c20.png)

**Comment by christianparpart** [comment]
yes, can confirm. I wonder if we recently introduced that. thanks :)

**Comment by Utkarsh-khambra** [comment]
Yup in #698

**Comment by christianparpart** [comment]
Okay that's embarrassing. I thought it's not fixed yet, seems so we fixed that in #703 already. :)

**Comment by Utkarsh-khambra** [comment]
I still have this issue. I am also on latest master.

**Comment by christianparpart** [comment]
Hm, okay. Then we need to try to repro that in some kind of minimal-setup, so that I can reproduce this for me, too. :)

**Comment by Utkarsh-khambra** [comment]
Can you reproduce this by opening file in nvim  in this way `nvim -u NONE -c "colorscheme blue" -c "syntax on" <some file>` and then resizing your window.
