### ISSUE TITLE
Nerd font character e0b2 shows as a block

### ISSUE THREAD

**Issue by GoldsteinE** [contour-terminal/contour#707]
### Contour Terminal version

Contour Terminal Emulator 0.3.2-unreleased

### Installer source

Github: source code cloned

### Operating System

NixOS

### Architecture

x86-64

### Steps to reproduce

1. Use a nerd font (I used Iosevka Nerd Font Mono)
2. `printf '\ue0b2\n'`

### Expected Behavior

Triangle is printed

### Actual Behavior

Block symbol is printed

### Additional notes

The same symbol with the same font renders correctly on QTerminal

**Comment by christianparpart** [comment]
Fixed on master branch. :-)
