### ISSUE TITLE
Tentatives for COPR packaging for Fedora

### ISSUE THREAD

**Issue by gagbo** [contour-terminal/contour#729]
Hello,

I'll just try to summarize here my efforts to package `contour` properly in a COPR repo so it is easily installable. Here be dragons!

## Status

Currently, nothing works, but you can check progress in 2 places:
- My WIP [copr repo](https://github.com/gagbo/coprs). I _will_ definitely force push it a few times while trying to figure out the errors (my desktop machine is running Arch for gaming purposes, so sometimes I need to test a few builds on COPR infra until I can figure out a proper solution)
- The [COPR itself](https://copr.fedorainfracloud.org/coprs/gagbo/contour/) where, of course, all builds are failing.

## Remarks/help required

Here are a few remarks and questions I got from that first (unsuccesful) hacking session.

### Proper install targets for libunicode and termbench-pro

As I'd like to have proper packaging for everything including dependencies, it would be nice if libtermbench had a proper install target for the library and the binary, as it seems the builders can't find them in common location ([logs](https://download.copr.fedorainfracloud.org/results/gagbo/contour/fedora-36-x86_64/04509936-termbench-pro/builder-live.log.gz)).

I still couldn't test it properly for libunicode, but it seems that it's also a minimal project that might have issues with proper installation to make a package out of it.

### Fedora actually has the GSL you mean

I thought Fedora missed GSL-3 since I thought it meant GNU Scientific Library. Actually GSL here means Guildelines Support Library, and it turns out the confusion was lifted by making a separate [guidelines-support-library](https://src.fedoraproject.org/rpms/guidelines-support-library) package, with a `-devel` version as well (thanks a lot @xvitaly for catching this). Currently version 4 is packaged though. Is version 4 really incompatible with version 3 ? If so I can try to extract this package definition to make a version 3 one, shouldn't be too hard.

### `install-deps.sh` forcefully modifying for embeds

As I will be able to properly install libunicode and termbench in the chroot builders, would it be possible to add some logic in the ThirdParties Cmake module so that it doesn't always try to call the non-existing [ContourThirdParties_Embed_libunicode](https://github.com/contour-terminal/contour/blob/d7d39d6be01d048c8b9500c7acc7ea50c3a68be6/cmake/ContourThirdParties.cmake#L103) since I plan on not running `install-deps.sh` at all ? Another solution would be for me to sed those lines out, but I'm not sure what I should replace them with if the libraries are installed on the system.

### Is contour statically linked ?

I don't understand how there's a single rpm in the release downloads if we require libunicode and other network dependencies like fmt-lib to build it. Is everything statically linked to not need any of those shared objects ?

Have a nice week-end,
Gerry

**Comment by christianparpart** [comment]
I'm gonna respond as soon as possible. Thanks for your efforts.

**Comment by Yaraslaut** [comment]
Hi, linking related [issue](https://github.com/contour-terminal/contour/issues/1054).  
And a link to fedora package https://packages.fedoraproject.org/pkgs/contour-terminal/contour-terminal/
