### ISSUE TITLE
Raspberry Pi 4 support

### ISSUE THREAD

**Issue by christianparpart** [contour-terminal/contour#741]
Support Raspberry Pi 4 (ARMv8).

### Checklist

- [x] OpenGL ES (3.1) (#740)
- [x] SIMD adaption via sse2neon
- [x] Alternative AES-NI `StrongHash` implementation, as it's not supported on Raspberry Pi's ARM CPU's (#1028)

**Comment by whisperity** [comment]
@christianparpart Just for verification, do we have a confirmation that this indeed works, by someone who actually tried on an RPi? I don't have such a hardware but I could try asking a colleague to do so, if needed.

**Comment by thaihugo** [comment]
I can also confirm it compiles on a non developer Rpi 4

**Comment by thaihugo** [comment]
There are not many opengl terminal options on the RPI 4 where the latest branch is working without modifications. Thanks for your work on this.
