### ISSUE TITLE
Crash during redraw

### ISSUE THREAD

**Issue by uspasojevic96** [contour-terminal/contour#743]
### Contour Terminal version

Contour Terminal Emulator 0.3.2-unreleased-master-3fe8121a

### Installer source

Github: source code cloned

### Operating System

Gentoo

### Architecture

x86-64

### Other Software

NodeJS 14

### Steps to reproduce

1. `git clone git@github.com:kamilmysliwiec/nest-cqrs-example.git`
2. `cd nest-cqrs-example`
3. `npm install`
4. `npm run start`
5. profit???

### Expected Behavior

Should clear screen and draw the framework output

### Actual Behavior

Crashes

### Additional notes

[yolo.log](https://github.com/contour-terminal/contour/files/8943218/yolo.log)

**Comment by christianparpart** [comment]
`ESC c` (hard reset) is broken. Should not be too hard to fix. :)
