### ISSUE TITLE
Flatpak support

### ISSUE THREAD

**Issue by christianparpart** [contour-terminal/contour#764]
It's already half implemented (C++-wise), it must be finished (I had issues with privilege escalation to escape the sandbox) and then be submitted to the flatpak store.

### Checklist

- [x] ensure C++ code is done
- [x] Control codes (e.g. <kbd>Ctrl</kbd>+<kbd>C</kbd>) do not seem to be passed correctly. It's definitely handled by Contour, but maybe flatpak-spawn does not properly forward it? Not proven nor sure yet what the actual root cause is.
- [x] Probably same root cause, window resizes are not forwarded correctly. This is probably some missing signal handling in flatpak-spawn.
- [x] pre-populate a `contour` terminfo file in a location somewhere in `~/.var/app/org.contourterminal.Contour/terminfo/` if it doesn't exist yet. -- Can we make the sandbox have access to this before-hand to make the file-creation cheap? Yes!.
- [ ] adapt CI to test against flatpak builds
- [ ] adapt CI release cycle to ideally(!) also auto-release on flatpak store.

**Comment by christianparpart** [comment]
Initial PR: https://github.com/flathub/flathub/pull/3349

**Comment by sitompul** [comment]
@christianparpart since [contour flathub](https://flathub.org/apps/details/org.contourterminal.Contour) has been released will you add flatpak installation guide on the readme?

**Comment by christianparpart** [comment]
> @christianparpart since [contour flathub](https://flathub.org/apps/details/org.contourterminal.Contour) has been released will you add flatpak installation guide on the readme?

This is a very good idea. But I consider it experimental for now. I am not yet sure if really everything works in this sandbox. Are you using the flatpak installation?

**Comment by sitompul** [comment]
@christianparpart I'm currently using it with tmux + vim and so far the only issue is when I'm using tmux it won't resize properly 
! [pic](https://user-images.githubusercontent.com/14266055/182361391-d92ca6c1-c090-41f4-8fb7-4a37c561168c.png)

I'm using fedora 36 + gnome 42 btw

**Comment by uspasojevic96** [comment]
Can you please check your `TERM` var and change it to `contour` if not already?

**Comment by christianparpart** [comment]
While now being published on flathub, it is apparent that a few things are definitely still missing before we can advertise for flatpak support in the project's README and the release page:

### Checklist

- [ ] Control codes do not seem to be passed correctly. It's definitely handled by Contour, but maybe flatpak-spawn does not properly forward it? Not proven nor sure yet what the actual root cause is.
- [ ] Probably same root cause, window resizes are not forwarded correctly. This is probably some missing signal handling in flatpak-spawn.
- [ ] anything else? (I'll keep this list updated) ...

**Comment by christianparpart** [comment]
@sitompul a little update. I've updated the flathub package that contains a fix to properly handle ctrl+c as well as window resize propagation.

Fix isn't the right term, because the problem is on flatpak's sandboxing side (flatpak-spawn process not properly handling PTY handles. Especially not when the child process (happens to become flatpak-spawn) is set to be the controlling terminal. 
The "workaround" is to not set this bit. But that leads to other issues but it's more important to be able to handle SIGWINCH as well as Ctrl+C.

**Comment by Yaraslaut** [comment]
Support for flatpack is added, link to the package: https://flathub.org/apps/org.contourterminal.Contour

**Comment by christianparpart** [comment]
Yeah, but sadly we have fallen behind, sure to flathub build server complications
