### ISSUE TITLE
install-deps script fails on Manjaro

### ISSUE THREAD

**Issue by Yaraslaut** [contour-terminal/contour#768]
### Contour Terminal version

Contour Terminal Emulator 0.3.3-unreleased-master-24920acd

### Installer source

Github: source code cloned

### Operating System

Linux Manjaro 5.15.55-1-MANJARO

### Architecture

x86-64

### Steps to reproduce

When running script to download and install dependencies I am getting error with harfbuzz, error tells that  current harfbuzz from repo can not be installed. This is caused by the fact that following packages are installed by default: 
 ``` 
harfbuzz 4.2.0-1
harfbuzz-icu 4.2.0-1
```
So, harfbuzz alone can not be upgraded and requires harfbuzz-icu update as well.

### Actual Behavior

Error during package installation

**Comment by christianparpart** [comment]
We can add support for Manjaro in this install-depa script.

I. Not sure the reason for the failure is correct though. We can surely easily find out and I keep you posted.

Many thanks for reporting this :-)

**Comment by christianparpart** [comment]
I have been just installing a Manjaro (Plasma spin) in a VM and I must appreciate the really good look of that Distribution. Also the installer looks nice. :+1:

**Comment by Yaraslaut** [comment]
> I have been just installing a Manjaro (Plasma spin) in a VM and I must appreciate the really good look of that Distribution. Also the installer looks nice. 👍

A was using gnome version

**Comment by christianparpart** [comment]
@Yaraslaut can you please tell me if #769 is fixing it for you? I had a fresh install of Manjarao and the changes in that PR (just checkout that branch to test) actually made it install the dependencies and build the binary right out of the box.

**Comment by Yaraslaut** [comment]
> @Yaraslaut can you please tell me if #769 is fixing it for you? I had a fresh install of Manjarao and the changes in that PR (just checkout that branch to test) actually made it install the dependencies and build the binary right out of the box.

Now script detects distribution, thanks. 
I realised how to reproduce bug, if you would install manjaro from older iso where harfbuzz version by default is not current version, then you will get this error when trying to install harfbuzz only

**Comment by christianparpart** [comment]
Any harfbuzz should be sufficient for contour as long as it isn't way too old.

**Comment by Yaraslaut** [comment]
> 

At least this error is not reproducible when someone is using current version of manjaro.

**Comment by christianparpart** [comment]
> At least this error is not reproducible when someone is using current version of manjaro.

I assume that "current" also implies "up-to-date", right? In this case I think we can safely close this ticket, iff it is working for you now.

**Comment by Yaraslaut** [comment]
> > At least this error is not reproducible when someone is using current version of manjaro.
> 
> I assume that "current" also implies "up-to-date", right? In this case I think we can safely close this ticket, iff it is working for you now.

Yes, you are right, it implies up-to-date version.
