### ISSUE TITLE
`Bold` and `Faint` CSI changes a background color

### ISSUE THREAD

**Issue by data-man** [contour-terminal/contour#786]
### Contour Terminal version

0.3.3-unreleased-master-a8ad3ed2

### Installer source

Github: source code cloned

### Operating System

Devuan

### Architecture

x86-64

### Steps to reproduce

* comment all colors in `dim` and `bright` sections in contour.yml
* uncomment:
```
# decoration "0" "Reset or normal"
# decoration "1" "Bold or increased intensity"
# decoration "2" "Faint, decreased intensity, or dim"
...
```
* run `$ test/decoration.sh`

### Expected Behavior

Background color is unchanged.

### Actual Behavior

![ksnip_20220811-164655](https://user-images.githubusercontent.com/1754269/184126648-3f43f6a3-8ee9-4602-a845-9aeeb75e52aa.png)

**Comment by christianparpart** [comment]
good catch, thx.

**Comment by christianparpart** [comment]
So bold colors are meant to be altered when `bold_is_bright` is set to `true.

Faint (dim) coloring indeed has a bug, especially with respect to default text and to background coloring.

**Comment by data-man** [comment]
Thank you! But...
With `draw_bold_text_with_bright_colors: true`:
![ksnip_20220913-114305](https://user-images.githubusercontent.com/1754269/189829254-67ea4a9d-6636-46e6-8540-5de4329786c8.png)

**Comment by christianparpart** [comment]
`draw_bold_text_with_bright_colors` alters the colors to be bright colors. that's the meaning of this option. The question is whether or not it should deal only with foreground color or also with background color.

**Comment by data-man** [comment]
I think a background color should not be changed.

**Comment by christianparpart** [comment]
done
