### ISSUE TITLE
micro does not work with contour

### ISSUE THREAD

**Issue by ptr1337** [contour-terminal/contour#796]
### Contour Terminal version

0.3.3.204

### Installer source

something else (please specify below)

### Operating System

Arch Linux

### Architecture

x86-64

### Other Software

micro 2.0.11-4

### Steps to reproduce

Install contour, open micro

### Expected Behavior

Micro does open

### Actual Behavior

contour just clears the terminal

**Comment by christianparpart** [comment]
Thanks @ptr1337 for reporting this. I actually wanted to ask you about what `micro` is, but now I did find the project page, I think. It seems to be a text editor: https://github.com/zyedidia/micro

I will investigate in this tonight and report back with a fix ASAP. Many thanks.

**Comment by christianparpart** [comment]
Just a quick update, I think that's on micro's side. Just blindingly type in `reset` and hit Enter to get back on track. `micro` puts the terminal into alternate-screen, wiping it, hiding the cursor, then quitting itself. This very much looks like a problem on `micro`'s side running into some interesting condition. I will try to debug that on `micro`'s side, but not now, more like tonight or so, unless someone Go-ledgeable helps me out here (@uspasojevic96? :-) )

**Comment by uspasojevic96** [comment]
@Utkarsh-khambra If you follow our discussion on discord:

1. `micro` seems to be using some work for terminal emulation
2. that fork has hardcoded terminfo
3. the bug is on `micro` side as it hardcodes the terminfo termcaps instead of looking up the env var for terminfo location and to query capabilities like that

**Comment by ptr1337** [comment]
Should I create at micro a issue cause this? 

@uspasojevic96 

Can confirm this, `TERM=kitty micro` works well for example.

**Comment by uspasojevic96** [comment]
Yes, best bet would be for this to be fixed on `micro` side
