### ISSUE TITLE
Selection in Vi mode disapears

### ISSUE THREAD

**Issue by Utkarsh-khambra** [contour-terminal/contour#798]
### Contour Terminal version

master

### Installer source

Github: source code cloned

### Operating System

Fedora 36

### Architecture

x86-64

### Steps to reproduce

1. Run `tree` in home
2. Switch to Vi mode
3. Start selecting text with `V`
4. keep selecting text upwards until selection doesn't disappear.

### Expected Behavior

Selection should be visible at all times

### Actual Behavior

Selection disapears

### Additional notes

If I try to yank the selection after it disappears, I get a segfault and this assertion failure 
`contour: contour/src/terminal/ViCommands.cpp:185: void terminal::ViCommands::executeYank(terminal::ViMotion, unsigned int): Assertion `terminal.selector()' failed.
`

**Comment by christianparpart** [comment]
Ugh I recently realized that, too. Thanks for creating the ticket. I may be able to look at it at some evening soon (unless you are faster) :).

**Comment by christianparpart** [comment]
I think before going into the why-yank-cranks part would be to figure why the selection drops, even though it's simply just extended. hmm...

**Comment by Utkarsh-khambra** [comment]
ea21ebf30ada066b3f7eb0c6486849778ef3e0c8 this is the commit where it first appears.

**Comment by Utkarsh-khambra** [comment]
> ~[ea21ebf](https://github.com/contour-terminal/contour/commit/ea21ebf30ada066b3f7eb0c6486849778ef3e0c8)~ [1788dd1](https://github.com/contour-terminal/contour/commit/1788dd1b589d4cfb0fee1b49b89f75f8fd4ac41c) this is the commit where it first appears.

Earlier linked wrong commit by mistake :(
