### ISSUE TITLE
A bind-able action to disable autoscroll while the action is active

### ISSUE THREAD

**Issue by Marenz** [contour-terminal/contour#808]
Implement an bindable action that can be used to temporarily disable autoscroll so one can investigate output of a process that is still outputting more lines.

more generic alternative approach: add an action that, while active/key pressed down, switches another configured option.

**Comment by Yaraslaut** [comment]
I think that this can be a default behavior when switching into normal mode. 
If  process is writing something and you go to normal mode, scrolling will stop
