### ISSUE TITLE
Extra padding added to Sixel image

### ISSUE THREAD

**Issue by imsnif** [contour-terminal/contour#809]
### Contour Terminal version

Contour Terminal Emulator 0.3.4-master-e5571bab

### Installer source

something else (please specify below)

### Operating System

Arch Linux

### Architecture

x86-64

### Steps to reproduce

`cat` the attached minimal reproduction.
[hi.txt](https://github.com/contour-terminal/contour/files/9534046/hi.txt)

### Expected Behavior

No padding is added after the image (attached image is from xterm with the --vt340 flag)
![img-2022-09-09-111050](https://user-images.githubusercontent.com/795598/189316096-f5217c28-4a25-4ba8-835a-9ab63b240b56.png)

### Actual Behavior

Several padding lines added after image (as seen in the image, I removed sixel-scrolling (DECSDM) to match the behaviour - I also think the default Contour behaviour is reversed here compared to other terminals, but maybe that's a different issue :) ).
![img-2022-09-09-111204](https://user-images.githubusercontent.com/795598/189317541-dfa372fc-6b98-4e59-a650-cc1df9897c3e.png)

### Additional notes

Hey there! I'm one of the Zellij maintainers and was working on this issue: https://github.com/zellij-org/zellij/issues/1697

I think I managed to narrow it down to the above reproduction. For us in the context of Zellij, this causes our UI to break when we run inside Contour and display a Sixel image.

As I mentioned above, once we solve this there is also the question of whether DECSDM enables or disables Sixel scrolling (I think Contour behaves differently than other terminal emulators in this context).

Happy to provide other reproduction steps or to discuss this further as needed.

**Comment by Utkarsh-khambra** [comment]
@christianparpart  So I think issue is whenever no aspect ratio is passed through the initial sequence to enter "sixel mode", contour just assumes the image size is whatever the max image size in config is set to be.

Here the two sample of same image, one where aspect ratio is passed through the sequence and other where it isn't passed
[with_size.txt](https://github.com/contour-terminal/contour/files/9537771/with_size.txt)
[without_size.txt](https://github.com/contour-terminal/contour/files/9537772/without_size.txt)

**Comment by christianparpart** [comment]
Oha, thanks guys. I remember I noticed that too recently. @Utkarsh-khambra would you want to take a look or shall I? :-)

**Comment by christianparpart** [comment]
@imsnif with dinner internal discussion on discord, it is now pretty clear how to fix this. Thanks for the report.

Wrt DECSDM, if I accidentally flipped it, I apologize, I will check. I somehow barely remember that I strived to comply to the sixel spec but TEs have been doing it the other ways around. Nertheless, I will take a look and converge of course.
