### ISSUE TITLE
text cursor advance from sixel seems wrong

### ISSUE THREAD

**Issue by jerch** [contour-terminal/contour#820]
### Contour Terminal version

0.3.3.204

### Installer source

GitHub: release page

### Operating System

Ubuntu 18 LTS

### Architecture

x86-64

### Steps to reproduce

- run `echo -e '\x1bPq$-$-$-$-\x1b\\'` --> terminal advances full page (seems to be locked to yaml height value?)

### Expected Behavior

The scriptlet inserts 4 empty sixel lines, thus 24px of vertical cursor advance. Terminal text cursor should advance by the same amount in cells. If vt340 cursor mode is enabled, the cursor should stop on the text line which covers the 24px from the original line.

### Actual Behavior

On running the scriptlet terminal advances a full page (seems to be locked to yaml height value?).

### Additional notes

NB: The test is furthermore degenerated in the sense that it does not place any pixel data. In contour this currently does not seem to make any difference (always shows full page advance). Note that most terminals are not sixel/vt340 conform for that no-pixel "image", as most dont move the cursor at all, which is wrong following the sixel spec - the text cursor should stop at the last active sixel line. (xterm seems to respect the empty image correctly, also need to fix it in xterm.js...)

Edit:
I stumbled over this behavior due to this script (can be used to test):
https://raw.githubusercontent.com/jerch/xterm-addon-image/1f68efe07d9404a73fafe5af4769faab42c9da1f/fixture/inspect_palette.sh

**Comment by Utkarsh-khambra** [comment]
Thanks for reporting this. I think this is similar to #809. Can you test the [newest release](https://github.com/contour-terminal/contour/releases/tag/v0.3.4.223) to see if this bug still persist.

**Comment by jerch** [comment]
@Utkarsh-khambra Thx for the pointer - yes the main issue is resolved in latest release. :+1: 

Though `echo -e '\x1bPq$-$-$-$-\x1b\\'` is prolly still wrong (still waiting for confirmation on vt340 behavior, can do another issue by then).
