### ISSUE TITLE
Rendering issues with build compiled from master today

### ISSUE THREAD

**Issue by Glog78** [contour-terminal/contour#821]
### Contour Terminal version

master

### Installer source

Github: source code cloned

### Operating System

arch linux 

### Architecture

x86-64

### Steps to reproduce

https://i.imgur.com/D3CKJ7k.png

interesting font rendering

### Expected Behavior

i think it's obvious

### Actual Behavior

wrong glyph rendering

**Comment by uspasojevic96** [comment]
Thanks for reporting, can you give us copy of your config?

**Comment by Glog78** [comment]
https://termbin.com/7u0z << config

**Comment by christianparpart** [comment]
Here it might be very interesting too see the comments of them texture atlas that can be dumped. It looks like the image is uploaded correctly but rendered squeezed, may e due to wrong internal color format passing. But that is very odd.

**Comment by uspasojevic96** [comment]
Can you post output of `fc-match "JetBrainsMono Nerd Font"` and `fc-match "JetBrainsMono Nerd Font Mono"`?

**Comment by Glog78** [comment]
[archbox ~] fc-match "JetBrainsMono Nerd Font"
JetBrains Mono Regular Nerd Font Complete.ttf: "JetBrainsMono Nerd Font" "Regular"
[archbox ~] fc-match "JetBrainsMono Nerd Font Mono"
JetBrains Mono Regular Nerd Font Complete Mono.ttf: "JetBrainsMono Nerd Font Mono" "Regular"

**Comment by Glog78** [comment]
Btw the w is broken too :)  So it's not only one glyph ...

**Comment by Utkarsh-khambra** [comment]
Does setting `font.render_mode` to gray fixes it for you?

**Comment by Glog78** [comment]
yes it does :+1:

**Comment by christianparpart** [comment]
> Does setting `font.render_mode` to gray fixes it for you?

Sorry guys, i'm a little late to the party (had a family-weekend outside of cellular network). If setting `font.render_mode` to `gray` does fix it for you and you used to use `lcd` before that reproduces the problem. I wonder why does it cause a problem only for a few glyphs.

Would you mind sending us the generated image file for the texture atlas? You can set a keybind to the action `CreateCoreDump`, which will write the latest internal state to `$HOME/.local/state/contour/dump/latest/` and in there you will have a `texture-atlas-rgba.png` file, that one you can simply drag'n'drop into the comment field here, I'm highly curious what that atlas looks like (once you see some faulty glyphs on your screen, not before).

Many thanks,
Christian.

**Comment by Glog78** [comment]
But i need to build debug instead of release ?

**Comment by christianparpart** [comment]
> But i need to build debug instead of release ?

I am sorry, it is called `CreateDebugDump`. No you don't. It should always work

**Comment by Glog78** [comment]
since i edited the older post i will repost.

![screenshot](https://user-images.githubusercontent.com/7598856/190919376-674a59a3-7842-42af-be2f-6786ac4868be.png)
![texture-atlas-rgba](https://user-images.githubusercontent.com/7598856/190919380-16e59b7d-434d-4fa3-9711-36cabad27fcf.png)

**Comment by christianparpart** [comment]
It is already uploaded wrong. Many thanks
 I will check.
