### ISSUE TITLE
qt6 build crashes with stacktrace

### ISSUE THREAD

**Issue by Glog78** [contour-terminal/contour#857]
### Contour Terminal version

latest git

### Installer source

Github: source code cloned

### Operating System

arch linux

### Architecture

x86-64

### Other Software

none

### Steps to reproduce

build with -DCONTOUR_BUILD_WITH_QT6=On

### Expected Behavior

don't crash

### Actual Behavior

crashs with backtrace

### Additional notes

backtrace with debug build.

https://termbin.com/ne37

**Comment by christianparpart** [comment]
Thanks @Glog78 . I'm lately touching Qt 6 a lot (due to the pending PR on porting Contour from QtWidgets to Qt's QML / QtQuick) and realized that I may be only able to support one, either Qt 5 **or** Qt 6.

Your one is new though.

I will keep investigating into Qt 6 for sure though, especially since Qt 5 is eventually fading out sooner or later anyways.

**Comment by christianparpart** [comment]
Just to be generally clear: Contour is working for you when not using Qt 6 (but Qt 5), right?

**Comment by Glog78** [comment]
QT5 is working fine. 
QT6 is crashing with posted stacktrace.

I am fine with whatever you decide, i have no reason to switch to qt6 right now, but in the long term i guess it won't be unavoidable. Since i like your terminal , i try to help whenever possibe , thats why i from time to time test around or report the bugs / nursances.

**Comment by christianparpart** [comment]
Many thanks @Glog78, I really appreciate that.

**Comment by data-man** [comment]
> crashs with backtrace

Immediately after starting? Or after starting an some application in the Contour?
OS?
Qt6 version?
Shell?

**Comment by Glog78** [comment]
immediatly after starting without opening the shell.
OS -> as stated in the bug report arch 
QT6 version -> 6.4.0.0-1 
Shell -> bash
cuustom contour config , which works with QT5 build.

**Comment by data-man** [comment]
> QT6 version -> 6.4.0.0-1

I use Contour-git in Devuan (Qt 6.3.1) without crashes.
@Glog78 Can you downgrade Qt to 6.3?

**Comment by Glog78** [comment]
https://termbin.com/j3ir << here is the config 
downgrade test will at least wait till today afternoon (if possible) i am not sure how long this will take me (could be a few minutes or hours) .. i am not sure what has been already compiled against the newer qt version , also it's not just one package ;) https://archlinux.org/groups/x86_64/qt6/

**Comment by christianparpart** [comment]
I think the config file isn't the problem though. Also, sorry, I think I won't be able to dedicate some time to Qt6 ASAP as I'm currently busy on some backend core parts (grid system) to make it fast and retain/improve stability. When touching QML I'll certainly have to deal with Qt 6 (probably attempting to default to it, since it's inevitable anyways).

**Comment by Glog78** [comment]
Just take your time with qt6 , i am fine with keeping the qt5 build which works. As i said , i just wanted to report. I can however go for a default config test later today (still at work).

**Comment by data-man** [comment]
Qt 6.4 is buggy. E.g. https://github.com/xiaoyifang/goldendict/commit/6d8779442c605448a99d5a581d3b76de99d6e205.

**Comment by Glog78** [comment]
Just for information arch -> qt6-base 6.4.2-1 -> still creates a backtrace for me while 5.x is ok

**Comment by christianparpart** [comment]
Oh this isn't good news. Because we were actually trying to fully move to Qt6 on the `master` branch currently. ;-(

**Comment by Glog78** [comment]
i know that's why i gave this information. Give me a moment i will rebuild and  get a new backtrace.

**Comment by Glog78** [comment]
[gdb.txt](https://github.com/contour-terminal/contour/files/10366352/gdb.txt) << backtrace

**Comment by Glog78** [comment]
[gdb_dev_build.txt](https://github.com/contour-terminal/contour/files/10366404/gdb_dev_build.txt) << here is for the Debug build if it helps more ...

**Comment by Glog78** [comment]
qt6-base 6.4.2-1 + current git 0.3.12-master-c7ef2f40 doesn't crash anymore on startup ;) i guess this one could be closed.
