### ISSUE TITLE
Terminal stays alive with zombified shell when originally started process is backgrounded-disowned

### ISSUE THREAD

**Issue by whisperity** [contour-terminal/contour#866]
### Contour Terminal version

0.3.6.4187

### Installer source

Github: CI actions

### Operating System

Ubuntu 20.04.5

### Architecture

x86-64

### Other Software

 - LibreOffice 6.4.7.2 40(Build:2)
 - lutris-0.5.10.1
 - VLC media player 3.0.9.2 Vetinari
 - zsh 5.8
 - bash 5.0.17(1)

### Steps to reproduce

1. Start a graphical program (e.g. `libreoffice` or `lutris`) in the disowned background in a freshly started terminal: `libreoffice &!`
2. `exit` (or `C-d`) the shell.
3. The started process is disconnected from the terminal and re-owned by `init`: ![Screenshot_20221031_110013](https://user-images.githubusercontent.com/1969470/198987807-ba83f606-4ef0-4337-99c0-77133190b119.png)
4. The shell itself stays as a zombie, and contour is alive! You can still type things into the window. ![Screenshot_20221031_110118](https://user-images.githubusercontent.com/1969470/198987832-8901371b-1d7f-4150-b804-57ead813d02a.png)
5. Once the graphical application is terminated, Contour will close.

### Expected Behavior

The shell, and the contour window, terminates properly.

### Actual Behavior

&nbsp;

### Additional notes

Same behaviour with Bash and ZSH.
It does not matter how deep the shells are spawned.

It can be reproduced with a temporary home (i.e. it does not depend on plugins and shell extensions!) too:

```bash
mkdir ~/tmphome
HOME=$(readlink -f ~/tmphome) bash
vlc &!
exit # This exits the inner shell.

exit # Another time, to exit the shell that was originally started by Contour.
```

-----

Other terminals:
 - GNOME Terminal and Kitty stay alive like Contour
 - Konsole closes immediately

**Comment by Glog78** [comment]
nohup /usr/bin/mpv "$url" >/dev/null 2>&1 & 

I would like to address that this even happens when you try to disconnect a media player from the terminal. You can close contour with the close button on kde and mpv keeps running but i would love to not have an additional button press needed. 
Also this behaivior wasn't there from the start. I remember a time when exit works but please don't asked me when it broke.
