### ISSUE TITLE
Non reversible resize

### ISSUE THREAD

**Issue by Yaraslaut** [contour-terminal/contour#877]
### Contour Terminal version

Contour Terminal Emulator 0.3.5-master-6e047fd9

### Installer source

Github: source code cloned

### Operating System

Manjaro Linux

### Architecture

x86-64

### Steps to reproduce

https://user-images.githubusercontent.com/44506630/201741851-5caebc99-4dab-4cc0-801c-770ebc385a07.mp4

https://user-images.githubusercontent.com/44506630/201741857-f89b235d-fa01-40fe-a31c-268fdceaeb94.mp4

### Actual Behavior

Text will be the same after series of resizes 

### Additional notes

File with the text
[file.txt](https://github.com/contour-terminal/contour/files/10006212/file.txt)

**Comment by christianparpart** [comment]
The first difference I spot (apart from the PAC-MAN style eating of lines) is that your shell is using a multiline prompt. so upon resize it'll probably repaint the current line and the line above. And what I noticed on ZSH is, that it'll *always* clear the content below the prompt, so we don't even see if there would be something.

Is there any chance to watch that video in slow-mo? hmm. The question is, is it worth fixing ASAP or worth waiting for the resize implementation improvement? 🤔

**Comment by Yaraslaut** [comment]
> 
I think it can wait until resize improvements.
Sometimes spaces disappear on resize, and I think that's what we see in the second video.

**Comment by christianparpart** [comment]
>  Sometimes spaces disappear on resize, and I think that's what we see in the second video.

Might be worth knowing. I'm pretty certain these lines are of type trivial. At least initially. Not sure the resize changes that due to automatic line reflow. If it's promoted to an inflated line, than (apart from fixing the actual issue), it should also be made sure both new lines (the first and the wrapped part) will remain trivial. That could even probably implicitly fix the space eating.

**Comment by Yaraslaut** [comment]
> The first difference I spot (apart from the PAC-MAN style eating of lines) is that your shell is using a multiline prompt. so upon resize it'll probably repaint the current line and the line above. And what I noticed on ZSH is, that it'll *always* clear the content below the prompt, so we don't even see if there would be something.
> 
> 
> 
> Is there any chance to watch that video in slow-mo? hmm. The question is, is it worth fixing ASAP or worth waiting for the resize implementation improvement? 🤔 

I think I will look at it now, maybe it will give me some hints on how to refactor resize procedure to make it easier to use another ring structure
