### ISSUE TITLE
Corrupted line width after resize

### ISSUE THREAD

**Issue by Yaraslaut** [contour-terminal/contour#883]
### Contour Terminal version

Contour Terminal Emulator 0.3.7.245

### Installer source

GitHub: release page

### Operating System

Windows 11 21H2

### Architecture

x86-64

### Steps to reproduce

https://user-images.githubusercontent.com/44506630/202843332-882e5af9-18aa-4e49-9a1e-249334f4178a.mp4

### Expected Behavior

Full width of the line available for editing

### Actual Behavior

Line width is corrupter and not completele available for editing

**Comment by christianparpart** [comment]
oh dear, i think we can group them all together, these family of bugs, all related to resize. But many thanks for the report. ;(

**Comment by Yaraslaut** [comment]
> oh dear, i think we can group them all together, these family of bugs, all related to resize. But many thanks for the report. ;(

Are you proposing to use separate label to mark such bugs or to create an issue to monitor other issues with resize ?

**Comment by christianparpart** [comment]
nono. I think after the current think I'm going to tackle resize in a way that I wanted to refactor inflated lines anyways. for this refactor I'd need to re-implement resize anyways.

If I am not mistaken, your ring rewrite is a drop-in replacement (API wise), such that we both won't interfere, right? I'm about to touch only the Line group of APIs plus Grid::resize, I'd say.

**Comment by Yaraslaut** [comment]
> 

Right, this ring can be used as a drop-in replacement (and it already can be used in such way) i also added a function `insert_before( line index , val)` to resize lines in-place instead of creating new ring, unfortunately current resize routines are very rigid to such changes :) and my fast atempt to adjast resize to new way has failed, so maybe we can syncronize at some point our work ?

**Comment by christianparpart** [comment]
## Quick Braindump of our call

- TrivialLine: a view into a PTY read buffer object
- PrimaryLine: a dense vector over complex cell columns (used to be InflatedLine)
- ContinuationLine: a view into a primary inflated line

So when a resize is happening, the continuation lines are dropped and recreated out of the PrimaryLine, based on the new page width.

Whatever we come up with, it must be fully testable on the lowest layer.
