### ISSUE TITLE
Ubuntu 18.04 package links against GLIBCXX_3.4.26 which does not exist on 18.04

### ISSUE THREAD

**Issue by delthas** [contour-terminal/contour#885]
### Contour Terminal version

0.3.7.245

### Installer source

GitHub: release page

### Operating System

Ubuntu 18.04.4 LTS

### Architecture

x86-64

### Steps to reproduce

- Download the Ubuntu 18.04 package from the Github release pages
- Install with apt install ./contour*.deb
- Run contour `./contour`

### Expected Behavior

Contour starts up properly

### Actual Behavior

contour: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.26' not found (required by contour)

Then contour exits.

### Additional notes

Ubuntu 18.04 does not ship this version of libstdc++. Contour should be rebuilt against an older version of libstdc++ for that Ubuntu version.

See: https://github.com/LedgerHQ/ledger-live-desktop/issues/4016 for a similar issue

**Comment by christianparpart** [comment]
This is not just affecting the AppImage then? Oh wow. Many thanks for telling me. We can certainly fix that.

Related question: What distro+versions are you using? (I'm trying to gather some stats here on what users use today). Thanks :)

**Comment by delthas** [comment]
I'm stuck on Ubuntu 18.04.4 LTS (as mentiond in the ticket) on my corporate laptop, which makes Contour one of the only terminal emulators with binaries supporting SIXEL for this Ubuntu version.

But on my misc "leasure" devices I'm running Arch / Debian stable / latest Ubuntu (22.10). Windows 10 too.

**Comment by christianparpart** [comment]
Hey @delthas. You ae not alone. @whisperity is sitting in the same boat and still swimming. I'll take care of it ASAP. :)

**Comment by christianparpart** [comment]
@delthas just a quick thing as it comes into my mind. you should be able to use the Flathub version, right? If that usage suits you and won't give you any negative impacts on your daily routines, you could give it a try. I'm keeping this up-to-date along with all the releases here: https://beta.flathub.org/apps/details/org.contourterminal.Contour

I **will* of course still address the actual issue on the classic .deb packages (AppImage version will take longer, there's a problem also on the AppImage devs side, sadly).

**Comment by delthas** [comment]
Hi, yes when I realized it was a lib issue I just installed the Flathub package and it worked perfectly. So it's fine on my side now, using this workaround. I'm just opening the issue to let you know :)

**Comment by Yaraslaut** [comment]
Since Ubuntu 18.04 is deprecated, we have AppImage for Ubuntu 22.04 now, so i am closing this issue
