### ISSUE TITLE
Auto-highlight matches on selection

### ISSUE THREAD

**Issue by christianparpart** [contour-terminal/contour#889]
When e.g. double-clicking a word, it would be nice if we also highlight equivalent matches in the current viewport.

This sounds like a useful feature that would have just helped me right now. Also, modern IDE's ans LSP's do provide similar functionality.

**Comment by Utkarsh-khambra** [comment]
We have * in vim mode. Which pretty much does this as well as allows jumps too.

**Comment by christianparpart** [comment]
@Utkarsh-khambra exactly. It's just that I was doing something fancy like

```sh
ps -o pid,pgid,sid,comm:40,wchan:21,cmd -a --forest
```

and wanted to quickly double click the PIDs to visualize the similarity between pid/pgid/sid. IDEs support the same. The difference to `*` in vi-like normal mode is, that the latter can be used to search and jump outside the viewport. 

When writing this ticket I also noticed the similarity and maybe we can merge this idea into one. i.e. double-click will word select but also fill the search pattern such that they are highlighted and keybinds outside of normal mode can be used to traverse through the highlights. hmmm

**Comment by christianparpart** [comment]
implemented.
