### ISSUE TITLE
Resize deletes the whole line

### ISSUE THREAD

**Issue by Utkarsh-khambra** [contour-terminal/contour#916]
### Contour Terminal version

Contour Terminal Emulator 0.3.8-master-5097e75c

### Installer source

Github: source code cloned

### Operating System

Fedora 37

### Architecture

x86-64

### Steps to reproduce

1. Run `printf "Apple ball cat dog egg fish gun hat ice cream john kite lion   monument\n"`
2. Resize terminal screen multiple times.

### Expected Behavior

Text should be present after resize.

### Actual Behavior

Text gets deleted.

https://user-images.githubusercontent.com/29328319/208240662-d14c7971-d6c2-4bea-9f7f-7e1de73196b0.mp4

**Comment by Yaraslaut** [comment]
Can reproduce it, but while using `sh` bug is not reproduced, only spaces disappear on resize

**Comment by christianparpart** [comment]
yes, only spaces disappear during joining process. the other problem is probably (again) the cursor placement issue. I am not sure. but the missing space problem should be trivially fixable.
