### ISSUE TITLE
Clock Overlay

### ISSUE THREAD

**Issue by christianparpart** [contour-terminal/contour#92]
Just like tmux, something I really like, to show a clock overlay via shortcut. 

A reasonable default could be <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>T</kbd>,
with the action name: `ClockOverlay` (or name it: `ShowClock`?).

Another question is whether to make this part of terminal library or exclusively for the frontend. I tend to the former with a more generic support for screen overlays (like an alternate buffer to be rendered from).

**Comment by Yaraslaut** [comment]
We now have clock in the status line, so i think this is not needed anymore
