### ISSUE TITLE
Font Antialiasing Issues

### ISSUE THREAD

**Issue by Glog78** [contour-terminal/contour#926]
### Contour Terminal version

0.3.9-master-f05bb1a5

### Installer source

Github: source code cloned

### Operating System

arch linux

### Architecture

x86-64

### Other Software

none

### Steps to reproduce

compiled from source qt5 Increasing Fontsize might make it more obvious used gray as antialiasing setting. Happens after my latest rebuild from git (today)

Config ->  https://termbin.com/34pr6

### Expected Behavior

Glyphs to be rendered smooth

### Actual Behavior

![image](https://user-images.githubusercontent.com/7598856/208452300-d97d58b6-589a-49f3-b026-9c1229351aca.png)

see -> t , corners of the c , o in mastodon , shadow after n in online

**Comment by uspasojevic96** [comment]
Did you try changing AA in contour config? That's why it's there, if no option works for you, this is then a bug

**Comment by Glog78** [comment]
![image](https://user-images.githubusercontent.com/7598856/208459722-5515882a-b6e6-4257-bc72-81513a299a47.png)
render_mode=grey
strict_spacing=false

![image](https://user-images.githubusercontent.com/7598856/208460040-92d65c05-74b1-4945-b754-2d16aba44b3d.png)
render_mode=monochrome
strict_spacing=false

![image](https://user-images.githubusercontent.com/7598856/208460628-d2efc9cc-a354-4803-b024-383b7bb4d553.png)
rendermode=light 
strict_spacing=false
(see the c which isn't completly filled) << currently most likely the best result

![image](https://user-images.githubusercontent.com/7598856/208461006-d72ef870-d18f-44ff-984e-527a854eef03.png)
rendermode=lcd
strict_spacing=false
see the % and the shadows at the edges

If i didn't miss one there should be all off them
also grey was totally fine for a long time , my update today broke it but i have skipped alot of commit's so i can't say which one introduced it.

**Comment by christianparpart** [comment]
I didn't touch font code nor OpenGL rendering code in a long time. That most likely could not have changed. Is this a new problem to you?

I very rarely experience a weirdly rendered character. I remember I fixed that by slightly increasing the font size. I'm using gray-scale AA. 🤔 hmmm....

**Comment by Yaraslaut** [comment]
I don't get any issues 
![image](https://user-images.githubusercontent.com/44506630/208468181-82f06478-49f0-4ea5-b3f6-e78fdfb84fa7.png)

P.S. nice config colors

you can try `contour debug font.render` to give more info

**Comment by Glog78** [comment]
> I didn't touch font code nor OpenGL rendering code in a long time. That most likely could not have changed. Is this a new problem to you?
> 
> I very rarely experience a weirdly rendered character. I remember I fixed that by slightly increasing the font size. I'm using gray-scale AA. thinking hmmm....
> 
> is this problem specific to one glyph and/or one font?

It's basically totally new. I compiled today and had this problem. It is also not only one specific glyph. It's happening depending on background color and or it seems depending also on font resolution which i usually change with hotkeys inside of contour.

**Comment by Glog78** [comment]
> 

Didn't give anything out of the ordenary.  Besides alot of messages like ->
[2022-12-19 17:39:02.319302] [font.render] rasterize (0, 12pt, 63) to rasterized_glyph(0, 5x17+(3, 14), alpha_mask)

Also updating the config doesn't helped -> https://termbin.com/9h52 | same issues

PS: The colorscheme is adapted from gruvbox-material -> 
vim ->
Plug 'sainnhe/gruvbox-material'
set background=dark
colorscheme gruvbox-material

i didn't used the new features like statusline and so on so i never adapted for the new modes but maybe someone want's to ...

**Comment by Glog78** [comment]
i wanted to try the release build but both release branch and master fail for me to build now -> https://termbin.com/obxn

**Comment by rhcher** [comment]
> i wanted to try the release build but both release branch and master fail for me to build now -> https://termbin.com/obxn

Just download from here https://github.com/contour-terminal/contour/releases/tag/v0.3.8.247

**Comment by Glog78** [comment]
> I don't get any issues ![image](https://user-images.githubusercontent.com/44506630/208468181-82f06478-49f0-4ea5-b3f6-e78fdfb84fa7.png)
> 
> P.S. nice config colors
> 
> you can try `contour debug font.render` to give more info

oh btw if it is not an jpeg artifact you got an small strange glyph too -> do you see how the n is rendered different ? ./build/src/co[n]tour (first line) vs all other n's in the text ?

**Comment by Yaraslaut** [comment]
> 

Indeed,  this one `n` is different from the others

**Comment by Glog78** [comment]
i might have found one reason -> resizing the window pixel by pixel in width creates rendering differences ... 

![image](https://user-images.githubusercontent.com/7598856/208483256-ae2ffbd7-dd49-4b58-b707-c3bd906be8a0.png)
![image](https://user-images.githubusercontent.com/7598856/208483308-5a92a9a0-c22d-4e7f-aa54-49dbb61e379f.png)
![image](https://user-images.githubusercontent.com/7598856/208483374-9c3ac824-861a-486f-b0dd-8f6758be6bf9.png)
![image](https://user-images.githubusercontent.com/7598856/208483500-d75deb2e-49b8-4596-b8a1-e04cd12bd1a0.png)

**Comment by Yaraslaut** [comment]
It seems that this commit broke rendering 
`a7bb9385b7e2af62cfdfff6d13c822d93e4cdeb6`
@Glog78  can you confirm this? 
For previous commit `c2ee1a1f244c46650401d57a12f1d74e3dce8b99` i don't see problems in rendering

**Comment by Glog78** [comment]
i can confirm a7bb9385b7e2af62cfdfff6d13c822d93e4cdeb6 broke it , thank you for the help

**Comment by Yaraslaut** [comment]
> i can confirm [a7bb938](https://github.com/contour-terminal/contour/commit/a7bb9385b7e2af62cfdfff6d13c822d93e4cdeb6) broke it , thank you for the help

Great, thanks


@Utkarsh-khambra can you look at why is it happening ?

**Comment by christianparpart** [comment]
Reading through the motivation text of the PR again:

> Because if terminal width is specified to be 80 cols then it should be 80 cols for both scrollbar hidden and visible.

I think one way to solve that would be to touch QOpenGLWidget::sizeHint() instead. I am not a Qt pro (sadly!), and there's still the QML PR open that btw addresses the scrollbar issue entirely differently (i.e. the problem doesn't even apply). but I think it'll take me quite a bit more until I can merge the QML PR, sorry :)

**Comment by Utkarsh-khambra** [comment]
I checked all the text rendering stuff with the default config, where the scrollbar is visible by default, that's why I didn't notice this. I'll look into this.

**Comment by Yaraslaut** [comment]
@Glog78  can you please check on latest master if this is fixed after recent pr https://github.com/contour-terminal/contour/pull/1139 ?

**Comment by Yaraslaut** [comment]
> ![image](https://user-images.githubusercontent.com/7598856/257899510-4d15a879-a74c-4b37-9da7-6f05e3f0ad63.png) i hope this is still visible ... tested lcd instead of grey and there is still a small line behind the @

This issue was fixed here https://github.com/contour-terminal/contour/pull/1213
Can you check @Glog78  if everything is ok now with anitaliasing in your case?

**Comment by Yaraslaut** [comment]
I will close this issue, if you still encounter it @Glog78  just reopen it then
