### ISSUE TITLE
Incorrect font selection with Iosevka TTC fonts

### ISSUE THREAD

**Issue by AlexKurisu** [contour-terminal/contour#939]
### Contour Terminal version

0.3.8.247

### Installer source

something else (please specify below)

### Operating System

Void Linux

### Architecture

x86-64

### Steps to reproduce

1) Install Iosevka font, super-ttc version
2) Set Iosevka Fixed as font family, regular weight
3) Open terminal

### Expected Behavior

Terminal should correctly select Iosevka Fixed Regular as a font (wezterm used for screenshot)
![image](https://user-images.githubusercontent.com/60626727/209185202-442d3655-c94a-4e2a-99c5-16cc0c2dc582.png)

### Actual Behavior

Terminal either incorrectly selects Iosevka Fixed Extralight or breaks rendering entirely
![image](https://user-images.githubusercontent.com/60626727/209185552-1de8799b-9e1c-44f6-95bd-e28fadae17c4.png)

### Additional notes

**Comment by AlexKurisu** [comment]
Problem isn't reproducible with any other terminal, just Contour

**Comment by christianparpart** [comment]
Hey. Many thanks for your interest and feedback on this behavior. We're actually "just" using fontconfig for matching fonts.

If there's anything to fix on our side, I'd like to get that included in a potential christmas release (hohoho!), but for that, maybe you can provide me with the little snipped from contour.yml that shows what you've configured to show that font.

Ideally also with a link to the font file you have downloaded?

I'll be trying to look into this ASAP.

And sorry for the inconviniences.

**Comment by AlexKurisu** [comment]
Sure.
[Iosevka TTC](https://github.com/be5invis/Iosevka/releases/download/v16.8.4/super-ttc-iosevka-16.8.4.zip)
[contour.yml](https://gist.github.com/AlexKurisu/94898cb3f881e1ac958cb25a519f085a)

**Comment by AlexKurisu** [comment]
Also tested with st (which also just uses fontconfig) - everything is correct, so looks like it's not fontconfig problem

**Comment by AlexKurisu** [comment]
@christianparpart tried to set strict_spacing to false. Nothing changed.

**Comment by christianparpart** [comment]
Okay I can reproduce this. I'll look into it ASAP.

**Comment by Utkarsh-khambra** [comment]
If I install Iosevka from ttf files and then these fonts work. But setting weight to ultra light doesn't work which is a weight option that Iosevka comes with.

**Comment by christianparpart** [comment]
<img width="542" alt="image" src="https://user-images.githubusercontent.com/56763/209214473-5a99524a-8241-462e-b291-e6c4cd67ad75.png">

I think this is how it should look like instead. I'll create a PR soon, @AlexKurisu - are you also able to build from source?

**Comment by AlexKurisu** [comment]
@christianparpart yes, I can

**Comment by christianparpart** [comment]
Grreat. You can checkout the branch from #941 (run ./scripts/install-deps.sh first, but we don't have Voice Linux support in that script, maybe you can help us adding it?).

**Comment by AlexKurisu** [comment]
Lol, sorry, I actually forgot that I didn't install Contour from Void repos but made a package myself

**Comment by AlexKurisu** [comment]
@christianparpart #941 fixed the problem, thanks
