### ISSUE TITLE
Wrong Background color

### ISSUE THREAD

**Issue by Glog78** [contour-terminal/contour#945]
### Contour Terminal version

0.3.8-makepkg-c2ee1a1f

### Installer source

Github: source code cloned

### Operating System

arch linux

### Architecture

x86-64

### Other Software

cataclysm dark days ahead curses version
most likely inflicts dwarf fortress too

### Steps to reproduce

i start cataclysm curses goto motd and scroll down (arrow keys down)
config -> https://termbin.com/jqmd | profile used main 

### Expected Behavior

background stays the same color (tested with urxvt for comparsion)

### Actual Behavior

the background color stays under the painted char's but the rest of the line gets the background color from the terminal 
see attached screenshot
![image](https://user-images.githubusercontent.com/7598856/209456516-11d5b1cd-6fbe-4ac1-8a3d-5707e995b84c.png)

**Comment by Utkarsh-khambra** [comment]
A simple way to reproduce this
`printf "\e[36m\e[40mHi This is a test\e[40C\e(0\e[m\e[37m\e[40mx\n"`

**Comment by Utkarsh-khambra** [comment]
One way to reproduce this 
`printf "\e[40m\e[2J\e[12;34r\e[1;45r\e[34;0H\e[34mHi\e[34;5H\e7\e[12;34r\e8\e[12;34r\e8\r\n\e[1;45r\e[34;0H\e[34mBye\n"`

**Comment by christianparpart** [comment]
@Glog78 a fixed was merged to master. Can you confirm it is working for you, too? Merry Christmas! ;-)

**Comment by Glog78** [comment]
Merry Christmas to you all too. Thank you it's fixed.
