### ISSUE TITLE
Migrate to Qt 6 on all platforms

### ISSUE THREAD

**Issue by christianparpart** [contour-terminal/contour#955]
Motivation behind? Supporting multiple **major** Qt versions seems almost impossible. And with the move to QML on the frontend side, it's basically not possible at all.

The idea is to only use Qt 6 only, have all references to Qt 5 completely removed, and then have a much easier time when working on the QML port again.

The only challenge here is the older Linux distributions that either don't have native Qt 6 package or aren't even supported by Qt at all (Ubuntu 18.04!).

## Checklist

- [x] OS/X
- [x] Windows
- [x] FreeBSD
- [x] Fedora Linux
- [x] Arch Linux
- [x] Ubuntu 22.04
- [ ] Ubuntu 20.04
- [ ] RHEL
- [x] AppImage (using Ubuntu 18.04 as base?)
- [ ] Have all support of Qt 5 completely removed.

**Comment by Yaraslaut** [comment]
I have a need to use RHEL on one of the systems which does not allow me to install packages for qt6, we need some sort of solution for this.

Quote @whisperity 
_I'd prefer if qt6 was not embedded into the contour package but available as a separate package...
contour-qt-libs or something_

**Comment by christianparpart** [comment]
yeah, the next release (apart from regular CI is doing) should definitely be Qt5 based. We can adapt release workflow to reflect that. we have enough useful changes in already that are useful to users. :)

Regular CI builds I would leave to be Qt6 based to have as broad test coverage of that as possible - while not removing the backwards compat from the code explictly.

**Comment by Yaraslaut** [comment]
So i think that we are good in this regard, we just need to update AppImage ? (@christianparpart ) and then we can close this issue since we are supporting both Qt versions and can drop Qt5 whenever we want

**Comment by christianparpart** [comment]
I think we should keep the appimage build instructions on CI updated, even though it's currently not executed or uploaded - because there were issues with AppImage, but they should be fixed eventually. So yeah, since actually ALL but AppImage are on Qt6 on CI build/release now, I think we can even close it right now (or after having ensured that AppImage *would* build using Qt6 as well). :)

**Comment by Yaraslaut** [comment]
> I think we should keep the appimage build instructions on CI updated, even though it's currently not executed or uploaded - because there were issues with AppImage, but they should be fixed eventually. So yeah, since actually ALL but AppImage are on Qt6 on CI build/release now, I think we can even close it right now (or after having ensured that AppImage *would* build using Qt6 as well). :)

Great :) 
I will update AppImage build, and if everything will be smooth we can advice people to use it if some distro is not supported

**Comment by Yaraslaut** [comment]
We can compile contour with Qt6 or Qt5 supoprt, difference exist only in qml part only, and we can remove Qt5 support if needed, thus closing this one
