### ISSUE TITLE
Contour built with Qt6 doesn't adhere to terminal size provided in config file

### ISSUE THREAD

**Issue by Utkarsh-khambra** [contour-terminal/contour#959]
### Contour Terminal version

Contour Terminal Emulator 0.3.10-master-f2a0c3d5

### Installer source

Github: source code cloned

### Operating System

Fedora 37

### Architecture

x86-64

### Steps to reproduce

1. Build contour with Qt6.
2.  Run contour with default config.

### Expected Behavior

When default config is used the terminal size should be 25 line high and 80 columns wide.

### Actual Behavior

The contour window that appears is 20 lines high and 56 columns wide.

**Comment by christianparpart** [comment]
ok this is really bad, but if that's the only issue we're having with Qt6 right now, I'm glad. :)

I'm sure that should(tm) be easy to fix. The things to look out for is `sizeHint` in the Qt docs and how that must have changed. Probably involves some trial'n'error and a little bit of research. :)

**Comment by christianparpart** [comment]
NB: Whatever the fix is, I hope the code change can be kept to a minimum, because with the QML port (following right after using Qt 6 on all platforms), this is going to be irrelevant again (because it works entirely different there) :tada:

**Comment by Utkarsh-khambra** [comment]
setting maximized=true in config also doesn't work, still the default window is 20x56.

**Comment by christianparpart** [comment]
I thought it would be sane to first move to qt6 and then to qml. Hmmm. I hope this won't be too intrusive before the move to qml in the frontend. Hmmm

**Comment by Utkarsh-khambra** [comment]
This is issue is somewhat resolve on master. Setting maximized=true works now, only remaining thing is the columns that terminal starts with is one more than specified in config. For example if I set columns to 80 then terminal starts with 81.

**Comment by christianparpart** [comment]
If we don't have that problem on QML PR, then I'd say this ticket is a blocker on the QML PR. Let's have that fixed not multiple times (unless someone has some spare times) :)

IIRC, getting dimensions right was working on QML branch ❓ 🤔

**Comment by Utkarsh-khambra** [comment]
This bug isn't on QML branch, it's only on master.

**Comment by Yaraslaut** [comment]
> This bug isn't on QML branch, it's only on master.

Now once we merged QML into master this can be closed, right?

**Comment by Utkarsh-khambra** [comment]
yep completed in #761
