### ISSUE TITLE
terminfo: improve use of `dsl`/`tsl`/`fsl` (statusline related)

### ISSUE THREAD

**Issue by christianparpart** [contour-terminal/contour#967]
Nice link about it on oldish hardware: https://www.ibm.com/docs/en/zos/2.2.0?topic=capabilities-status-lines

Contour currently uses the way, I think, most terminals are having dsl/fsl/tsl set to. But since we do **actually** support a status line, we could make this change to it.

A first quick look at the link above did indicate to me that they where actually talking about the host writable statusline (not the indicator statusline). Let's see.

**Comment by christianparpart** [comment]
I feel sad being the only TE dev having actual interest in the official status line.  I really like that though she want to improve on that. 

Do actually know of any app that currently makes use of the host writable status line?

**Comment by j4james** [comment]
> Do actually know of any app that currently makes use of the host writable status line?

After a bit of Googling I found these:

- [Neovim](https://github.com/neovim/neovim): It looks like they use the `tsl`/`fsl` capabilities to display status that would typically appear in the title bar (see the code [here](https://github.com/neovim/neovim/blob/90493beb1584b9a99d3a71658bccd536d601e0f7/src/nvim/tui/tui.c#L1366-L1375)).
- [LFTP](https://github.com/lavv17/lftp): Some sort of file transfer application. Again I'm assuming they use the status line just based on what I can see in the source (see the code [here](https://github.com/lavv17/lftp/blob/d67fc14d085849a6b0418bb3e912fea2e94c18d1/src/StatusLine.cc#L58-L61)).
- [sysline](https://www.ibm.com/docs/en/aix/7.2?topic=s-sysline-command): This is a utility that displays system info on the status line according to the documentation. It appears to be a standard command at least on some flavors of Unix.

I've never actually tried any of these things in a terminal with status line support, so I don't know how well they work. It's possible they may require configuration to activate that functionality, but hopefully just having the appropriate terminfo settings will be enough.

**Comment by christianparpart** [comment]
What the hell, for real? That is amazing that Neovim is using that. Sadly that however sounds like a fairly dump use of the (host writable) statusline. I'll give it a try. Many thanks for the research. :)

`sysline` is a tool I'm really curious about now. Gonna give it a try.

So in contour we make pretty decent use of the indicator statusline, e.g. when moving to (vi-like) normal mode, to browse in history like a vim-guy. It looks a little tmux'y, and I wanted to make it a little bit more configurable, such that users can display to their liking and styling preferences.

**Comment by christianparpart** [comment]
sysline: https://www.ibm.com/docs/en/aix/7.2?topic=s-sysline-command

**Comment by christianparpart** [comment]
Fun fact @j4james - with the above PR, I've got https://github.com/acli/sysline to display data. I'll see how much I can play with it. I still need to compare the output against how xterm is displaying it (i have no hardware to test against, sadly) :)

**Comment by j4james** [comment]
> What the hell, for real? That is amazing that Neovim is using that.

I suspect it was because a lot of terminals that didn't support a status line starting using the title setting OSC sequence as a hacky substitute - something like `tsl=\E]0;` plus `fsl=^G`. And then when there were more terminals using that hack than there were real status line terminals, that made it seem like setting the title was the main purpose of `tsl` + `fsl`.

> I've got https://github.com/acli/sysline to display data. 

That's cool. I'd like to do some experimenting with that myself. Did you have to build it from source, or can it be installed with something like APT?

> i have no hardware to test against, sadly

You could always raise an issue on the [vt340test](https://github.com/hackerb9/vt340test) repo if you've got some test cases that you want to verify.

**Comment by christianparpart** [comment]
reading the source code of vim (your above ref), it seems like neovim is using tsl/fsl, but for some reason I didn't get it to do anything. 🤔 not sure yet why.

`sysline` I had to build myself and it was interactive and quite unintuitive. I didn't try on a APT-based system yet, but on Fedora I didn't have it (hence, self compiled).

Maybe I'll fork that repo and put some cmake on top of it, to make it more usable. Not sure yet. But I'd like to play around with it a little more.

Also, I tried `sysline` on xterm very quickly this morning. First, I didn't have a `xterm+sl` terminfo file (as suggested by the readme), but seems like fsl/dsl/hs/... are available in the `xterm-256color` terminfo as well. However, xterm's host writable statusline seems terribly broken. It wasn't even remotely useful and only trashing the screen. Not sure this is know by anyone (give it a try :) )

> You could always raise an issue on the [vt340test](https://github.com/hackerb9/vt340test) repo if you've got some test cases that you want to verify.

This sounds like a brilliant idea. I just changed jobs though and I need to focus a little bit on onboarding stuff and such. I hope we can do something there eventually :)

**Comment by christianparpart** [comment]
@j4james try https://github.com/christianparpart/sysline - i've added a cmake file plus minor other changes. I'm not planning to maintain this or improve upuon it. It's too C'ish and old for me. But it's a good thing to play and try :)

**Comment by j4james** [comment]
> However, xterm's host writable statusline seems terribly broken.

I don't have the latest version of xterm, but the build I'm using definitely worked. I tested your `sysline` fork (thanks for setting that up btw), and I could see it displaying the clock and a couple of other fields in the status line. Did you remember to build xterm with the `--enable-status-line` option?

**Comment by Yaraslaut** [comment]
PR https://github.com/contour-terminal/contour/pull/993 broke status line on zsh

![image](https://user-images.githubusercontent.com/44506630/224533994-9f17bd86-f1d5-4b34-81fd-9d9393f7e2de.png)

Few attempts has been made to fix it https://github.com/contour-terminal/contour/pull/1060 and https://github.com/contour-terminal/contour/pull/1060

but error is still present : 
![image](https://user-images.githubusercontent.com/44506630/224534882-b31ce22a-6101-4a3f-a2e7-8a03a3af7a64.png)

for the reference  expected status line : 
![image](https://user-images.githubusercontent.com/44506630/224535051-d371d9a9-e841-4d65-9c3c-d4765d8e6629.png)

**Comment by whisperity** [comment]
> PR #993 broke status line on zsh

And #1061 did not fix it: https://github.com/contour-terminal/contour/pull/1061#issuecomment-1464894346

**Comment by whisperity** [comment]
Right now, although the "title bar on the bottom" and Contour's own statusline do not conflict (perchance this is the "fix" of #1061), the behaviour is still bonkers, under ZSH at least. Both the current directory and the running program's name (e.g., `vim`) appear at the bottom, the line does not go away (even when entering Vim) and what's worse is that the title bar of the Contour window itself only says `contour` and never updates, making:

 - 1-line heigh dead area that cannot be used for anything and is always there
 - multiple running Contours indistinguishable from each other before consuming the entire contents of the window visually

The title bar of the window is already there and we are not using it to show title-like contents, but instead waste a line in the main viewport for this.

"New" behaviour as of currently latest master build [0.3.12.4904](https://github.com/contour-terminal/contour/actions/runs/4585252222), I just checked and it is still there:
![image](https://user-images.githubusercontent.com/1969470/229750722-542b422a-a52f-4c25-8f5f-42ab23ded6ec.png)

Old behaviour (newest old build I could find working was 0.3.9.4474), where the title bar and thus the program switcher element for the window makes it distinguishable:
![image](https://user-images.githubusercontent.com/1969470/229750869-cb3d2728-5c92-462e-baa5-27e8282cb5ee.png)

(N.b. that the two separate Dolphin windows also try indicating at the earliest glance which directories they are in.)

The `display_host_writable_statusline` permission is not adhered to, neither `allow` nor `deny` make any difference, and setting it to `ask` never triggers any permission query.

**Comment by whisperity** [comment]
* KUbuntu 22, aka: Ubuntu 22.04.2 LTS
 * zsh 5.8.1 (x86_64-ubuntu-linux-gnu)
   * with Oh-My-ZSH (ohmyzsh/ohmyzsh@9233ef75f28423d147a2f9f64a45a77b1886ee5d, just updated)
   * using theme powerlevel10k (romkatv/powerlevel10k@b474978b2e9435c10ca66f8281352ebc825264f4, also just updated before the checks)

Not sure what else of plugins I have that could interfere but my public [configuration is available](http://github.com/whisperity/Dotfiles) and there is even a Dockerfile to run the stuff. :slightly_smiling_face:
(And my private configurations do not contain anything pertaining to shells, it's mostly just build tree and CMake presets I use with LLVM.)

I also have this... not sure how much it might help. Created with `contour debug '*' 2>&1 | tee contour.log`: 
[`contour.log`](http://github.com/contour-terminal/contour/files/11147064/contour.log)

**Comment by j4james** [comment]
@whisperity I think this is really an ohmyzsh issue, since they're deliberately using the status line in place of setting the title. See here:

https://github.com/ohmyzsh/ohmyzsh/blob/9233ef75f28423d147a2f9f64a45a77b1886ee5d/lib/termsupport.zsh#L32-L35

```sh
# Try to use terminfo to set the title if the feature is available
if (( ${+terminfo[fsl]} && ${+terminfo[tsl]} )); then
  print -Pn "${terminfo[tsl]}$1${terminfo[fsl]}"
fi
```

This would assumedly also break in other terminals that support the status line (e.g. XTerm), if it wasn't for the fact that they've also got a hard-coded list of `TERM` values for which use the `OSC` title sequences instead. See here:

https://github.com/ohmyzsh/ohmyzsh/blob/9233ef75f28423d147a2f9f64a45a77b1886ee5d/lib/termsupport.zsh#L19-L23

```sh
case "$TERM" in
  cygwin|xterm*|putty*|rxvt*|konsole*|ansi|mlterm*|alacritty|st*|foot)
    print -Pn "\e]2;${2:q}\a" # set window name
    print -Pn "\e]1;${1:q}\a" # set tab name
    ;;
```

This is why so many terminals just set their `TERM` to some variant of xterm and don't bother trying to do the right.

**Comment by Yaraslaut** [comment]
I will just place it here for the history: https://github.com/ohmyzsh/ohmyzsh/pull/11599
I assume that issue with status line on zsh is solved  @whisperity can you confirm that?

**Comment by whisperity** [comment]
> @whisperity I think this is really an ohmyzsh issue, since they're deliberately using the status line in place of setting the title. See here:

@j4james Oh shoot, I wanted to reply earlier that yes, me, @christianparpart and @uspasojevic96 debugged this on Discord. (The entry to the ticket was only done because we have a history of forgetting stuff because communication on Discord disappears too quickly when new messages happen.)

> I will just place it here for the history: [ohmyzsh/ohmyzsh#11599](https://github.com/ohmyzsh/ohmyzsh/pull/11599) I assume that issue with status line on zsh is solved @whisperity can you confirm that?

@Yaraslaut Side-stepped. As we discussed on Discord, the fact that one plugin that misused the status line as-if it was the title bar is not a true solution because there will be hundreds more programs that use the 30+ years established practice of "status line = title bar in a graphical environment". So Contour needs to at least offer choices to the user if they want to replicate whatever is in the statusline to the titlebar for applications that do not support the other escape sequence.

(There were multiple additional ideas discussed on Discord.)

> This is why so many terminals just set their `TERM` to some variant of xterm and don't bother trying to do the right.

Exactly, but this also means that Contour will have to eventually make way of supporting a proper "Xterm-compatibility" mode and not break existing established practice (even if it is of abuse or pragmatically incorrect as-is), because we will not be able to patch all the programs that have ever existed in the world. And some of these programs will not be scripts but binaries that might take years to be upstreamed into LTS and enterprise package sources...

**Comment by christianparpart** [comment]
There seems to be an issue with `tsl` not effectively being permission-wall protected. For me it does, for you (@whisperity) it doesn't. I'll digg into that. So while oh-my-zsh should not use `tsl`/`fsl` to begin with, I'll keep this ticket here open until I've figured out why the permission configuration did not work for you. :)

**Comment by Yaraslaut** [comment]
> There seems to be an issue with `tsl` not effectively being permission-wall protected. For me it does, for you (@whisperity) it doesn't. I'll digg into that. So while oh-my-zsh should not use `tsl`/`fsl` to begin with, I'll keep this ticket here open until I've figured out why the permission configuration did not work for you. :)

When we will move to qml, requests for permissions will be handled there, so maybe we don't want to investigate what is going on with them on current master but check on qml branch

**Comment by christianparpart** [comment]
Is there anything missing on this ticket? IIRC We've addressed it all and all of the affected people in here should(tm) be happy now. Am I missing something that needs to be addressed in order to close this ticket?

**Comment by Yaraslaut** [comment]
Seems like no updated are required anymore, thus i am closing this one
