### ISSUE TITLE
unreproducable errors with neovim

### ISSUE THREAD

**Issue by Glog78** [contour-terminal/contour#972]
### Contour Terminal version

0.3.10-master-7c8e852e

### Installer source

Github: source code cloned

### Operating System

arch linux

### Architecture

x86-64

### Other Software

NVIM v0.8.2 and NVIM v0.9.0-dev-626+g42afa0369

### Steps to reproduce

I didn't  found a way to make this error happen all the time (aka reproducable). It's more likely to happen once https://github.com/simrat39/lsp-trouble.nvim opened or i did a :make.

### Expected Behavior

Rendering neovim and all elements as expected.

### Actual Behavior

It seems like for some reason and random (aka i can't make it happen) elements get's rendered one line above the line they should be rendered.

See how the statusline Normal is posted above command and the command line is not completly cleared?

![image](https://user-images.githubusercontent.com/7598856/211150283-c0ee6294-2cb2-490e-99f0-499b9ec29078.png)

example picture 2 shows it even more clearly
![image](https://user-images.githubusercontent.com/7598856/211150345-d5582838-1566-42fc-96a3-c8942670d978.png)

### Additional notes

It's less likely to be a plugin issue cause i really tried hard to replicate the behaivior with urxvt but i wasn't able too

**Comment by christianparpart** [comment]
@Glog78 sorry for the inconveniences. Is this with Qt6 or Qt5? Hm... nevertheless, it's certainly not a frontend (Qt) related issue but rather in the backend.

I will be trying to repro that. Are you on our Discord anyhow? That would probably be helpful for some quick forth and back in digging into this issue.

**Comment by Glog78** [comment]
No problem :) it's QT5 and yes i have a discord account.

**Comment by Glog78** [comment]
[nvim.tar.gz](https://github.com/contour-terminal/contour/files/10367791/nvim.tar.gz)
[contour.tar.gz](https://github.com/contour-terminal/contour/files/10367792/contour.tar.gz)

**Comment by Glog78** [comment]
this one can be closed -> the issue only happens if you choose  XTERM=term-256color which should not be the default. 
If you have servers you ssh into to get around distributions which doesn't know contour terminal copy the /usr/share/terminfo/c/contour to your server. Either into ~/.terminfo/c/ or if you can systemwide into /usr/local/share/terminfo/c

**Comment by christianparpart** [comment]
Thanks for the explanation. :)
