### ISSUE TITLE
Lockup related to trying to display invalid UTF-8 sequences

### ISSUE THREAD

**Issue by cqexbesd** [contour-terminal/contour#980]
### Contour Terminal version

0.3.10-master-1c106828

### Installer source

Github: source code cloned

### Operating System

Arch Linux as of a few days ago

### Architecture

x86-64

### Steps to reproduce

If I cat a file containing `21b1 f50c c627 f932` (but the binary, not the hex representation) my terminal locks up. With tracing on, I get an infinite number of:

```
[2023-01-12 14:35:24.109843] [vt.trace.parser] [Unicode] Scanned text: maxCharCount 77; cells 0; bytes 1; UTF-8 (4/0): "\xc6"
```

to contour's stderr (not the terminal's).

### Expected Behavior

Garbage to be printed, or the replacement character (if that's the correct name, the one that shows up as a ? when you are missing glyphs).

### Actual Behavior

Terminal stopped responding. Does not repaint the window if it gets obscured and revealed. Has to be killed using the window manager to force close the window (or probably a straight kill to the process would work as well).

**Comment by cqexbesd** [comment]
A file for catting.

[o8.txt](https://github.com/contour-terminal/contour/files/10402162/o8.txt)

**Comment by christianparpart** [comment]
> A file for catting.
> 
> [o8.txt](https://github.com/contour-terminal/contour/files/10402162/o8.txt)

Yes! I can  repro it, yay. Should be trivial to investigate and fix (famous last words, watch me). I'll keep you posted. And many thanks for your patience @cqexbesd :)

**Comment by christianparpart** [comment]
Found the source, so it seems. This is invalid UTF-8 and it does detect that, but forgot to consume the invalid byte on input. The bug is actually in [libunicode](https://github.com/contour-terminal/libunicode/), so once fixed, most likely you'll need to `./scripts/install-deps.sh` after `git pull` but before `make`-stage. I'll keep you posted.

**Comment by christianparpart** [comment]
auto-closed too quickly. i didn't verify in contour if this is **actually** fixed, sorry. will re-open until verified.

**Comment by Yaraslaut** [comment]
If one will try to cat image file,  contour will just crash

**Comment by christianparpart** [comment]
I am aware of it and have only fixed half of the story on libunicode side. Sorry. U will catch up ASAP.

**Comment by Yaraslaut** [comment]
For given file

> A file for catting.
> 
> [o8.txt](https://github.com/contour-terminal/contour/files/10402162/o8.txt)

contour does not  lockup anymore, unfortunately we still have https://github.com/contour-terminal/contour/issues/1062
So i will close this issue since locking has been resolved
