### ISSUE TITLE
contour.yml YAML schema not up-to-date

### ISSUE THREAD

**Issue by christianparpart** [contour-terminal/contour#981]
The yaml schema for the contour.yml must be really brought up to date. Sorry for all those that have been confused by that.

https://github.com/contour-terminal/contour/blob/master/docs/contour.schema.json

Updating it should be actually easy. It's probably just mapping the example config (along with its documentation for possible values) to the schema file.

Only YAML knowledge needed.

## Checklist

- [ ] bring schema up-to-date
- [ ] add ci to test current default config against the schema

**Comment by Yaraslaut** [comment]
Maybe we can just delete this file ?

**Comment by christianparpart** [comment]
@Yaraslaut yeah, sadly I think it's just the best. we can revive at any time  - along with the config revamp that's planned anyways. :)
