### ISSUE TITLE
Selected text extraction sometimes missing spaces

### ISSUE THREAD

**Issue by christianparpart** [contour-terminal/contour#982]
Quote from @cqexbesd,

```
I just copied (by selecting with my mouse) some text and
when I pasted there are spaces missing (but not all of them).

If I copy the same text front he same window it is always reproduceable
but the same text in a different window is fine

in all cases the text I am copying is from nvim
```

I guess these spaces got lost on wrapped lines and it's the spaces at the wrapping point?

**Comment by whisperity** [comment]
Also if your highlight contains tabs, then the highlight messes up when dragging around the tab.

Try:

```
echo -e "Free memory:\t130 GiB"
```

**Comment by cqexbesd** [comment]
> I guess these spaces got lost on wrapped lines and it's the spaces at the wrapping point?

There should have been no wrapping involved. Both windows were wide enough to accommodate the lines.

**Comment by christianparpart** [comment]
I will check.

**Comment by cqexbesd** [comment]
> then the highlight messes up when dragging around the tab.

Do you mean that if you select from the left to the right, the moment you get to the tab it highlights the rest of the line (and sometimes a bit of the next line under circumstances I can't identify) but then goes back to normal when you get to the word after the tab? If so I can reproduce that as well but its a different issue to the one I was reporting. In my case the right thing is highlighted, it's just not what ends up on the clipboard.

**Comment by cqexbesd** [comment]
Ah but you are right - copying and pasting something with a tab loses the tab, just like my bug loses the spaces. So that's probably a good test case as I imagine the cause is the same.

`printf "a\tb\n"` and copy and paste that, using mouse or vi mode, and the tab is lost.

**Comment by Utkarsh-khambra** [comment]
> Also if your highlight contains tabs, then the highlight messes up when dragging around the tab.

This comes from [here](https://github.com/contour-terminal/contour/blob/520624c157ae44fe029a7fb3e0b6cf27aea2868f/src/vtbackend/Terminal.cpp#L788) that I added in #751. Fix for it is simple, I just need to also check for tab character as well. 
Btw are there any other types of spaces other than a space and tab.
