### ISSUE TITLE
QApplication::beep() broken on many systems. Use another API for `BEL` instead

### ISSUE THREAD

**Issue by christianparpart** [contour-terminal/contour#985]
As reported by @cqexbesd, `BEL` is not working, even though `QApplication::beep()` is being invoked. Googling for that turns out that this doesn't seem to always work and other people's fix was to simply not use it but other APIs, e.g. [QMediaPlayer](https://doc.qt.io/qt-5/qmediaplayer.html) from QtMultimedia.

This seems as simple as:

```cpp
QMediaPlayer player; 

// ...

player.setMedia(QUrl::fromLocalFile("/usr/share/sounds/freedesktop/stereo/bell.oga"));
player.setVolume(50); 

// ...

player.play();
```

But while being at it, why not making it (per profile) configurable, such that users can tweak what's about to be played when `BEL` is being processed.

NB: In case of `BEL` spam, a new sound must not be played if an old one is still playing.

**Comment by uspasojevic96** [comment]
Keep in mind that `/usr/share/sounds/freedesktop/stereo/bell.oga` is platform dependant

**Comment by christianparpart** [comment]
@uspasojevic96 that'll be configurable of course. that's the nice part about it :)

**Comment by christianparpart** [comment]
NB: We'd provide a default sounds - we have one already in the qml branch, we can simply use that as default sound, so it'll always work out of the box on all platforms.
