### ISSUE TITLE
Config option per profile to disable ligatures

### ISSUE THREAD

**Issue by Glog78** [contour-terminal/contour#990]
## Abstract

There are some console app's where you don't want to have ligatures on.  Mostly notable on roguelikes. 

## Motivation

Per profile setting to disable ligatures even if a font offer them.

**Comment by Glog78** [comment]
https://termbin.com/1pdl  << i used this  config


# contour profile rogue
![image](https://user-images.githubusercontent.com/7598856/213316483-b5ec152b-3492-48b6-bbd9-a24cc47dfbed.png)

^^ shouldn't [-liga] remove it

**Comment by christianparpart** [comment]
@Glog78 use `-calt`.
